// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import type * as Vapi from "../../../index.js";

export declare namespace StructuredOutputsClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class StructuredOutputsClient {
    protected readonly _options: StructuredOutputsClient.Options;

    constructor(options: StructuredOutputsClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * @param {Vapi.StructuredOutputControllerFindAllRequest} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerFindAll()
     */
    public structuredOutputControllerFindAll(
        request: Vapi.StructuredOutputControllerFindAllRequest = {},
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutputPaginatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerFindAll(request, requestOptions));
    }

    private async __structuredOutputControllerFindAll(
        request: Vapi.StructuredOutputControllerFindAllRequest = {},
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutputPaginatedResponse>> {
        const {
            id,
            name,
            page,
            sortOrder,
            limit,
            createdAtGt,
            createdAtLt,
            createdAtGe,
            createdAtLe,
            updatedAtGt,
            updatedAtLt,
            updatedAtGe,
            updatedAtLe,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (id != null) {
            _queryParams.id = id;
        }

        if (name != null) {
            _queryParams.name = name;
        }

        if (page != null) {
            _queryParams.page = page.toString();
        }

        if (sortOrder != null) {
            _queryParams.sortOrder = sortOrder;
        }

        if (limit != null) {
            _queryParams.limit = limit.toString();
        }

        if (createdAtGt != null) {
            _queryParams.createdAtGt = createdAtGt;
        }

        if (createdAtLt != null) {
            _queryParams.createdAtLt = createdAtLt;
        }

        if (createdAtGe != null) {
            _queryParams.createdAtGe = createdAtGe;
        }

        if (createdAtLe != null) {
            _queryParams.createdAtLe = createdAtLe;
        }

        if (updatedAtGt != null) {
            _queryParams.updatedAtGt = updatedAtGt;
        }

        if (updatedAtLt != null) {
            _queryParams.updatedAtLt = updatedAtLt;
        }

        if (updatedAtGe != null) {
            _queryParams.updatedAtGe = updatedAtGe;
        }

        if (updatedAtLe != null) {
            _queryParams.updatedAtLe = updatedAtLe;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "structured-output",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Vapi.StructuredOutputPaginatedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling GET /structured-output.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Vapi.CreateStructuredOutputDto} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerCreate({
     *         name: "name",
     *         schema: {
     *             type: "string"
     *         }
     *     })
     */
    public structuredOutputControllerCreate(
        request: Vapi.CreateStructuredOutputDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutput> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerCreate(request, requestOptions));
    }

    private async __structuredOutputControllerCreate(
        request: Vapi.CreateStructuredOutputDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutput>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "structured-output",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.StructuredOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling POST /structured-output.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Vapi.StructuredOutputControllerFindOneRequest} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerFindOne({
     *         id: "id"
     *     })
     */
    public structuredOutputControllerFindOne(
        request: Vapi.StructuredOutputControllerFindOneRequest,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutput> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerFindOne(request, requestOptions));
    }

    private async __structuredOutputControllerFindOne(
        request: Vapi.StructuredOutputControllerFindOneRequest,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutput>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                `structured-output/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.StructuredOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling GET /structured-output/{id}.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Vapi.StructuredOutputControllerRemoveRequest} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerRemove({
     *         id: "id"
     *     })
     */
    public structuredOutputControllerRemove(
        request: Vapi.StructuredOutputControllerRemoveRequest,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutput> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerRemove(request, requestOptions));
    }

    private async __structuredOutputControllerRemove(
        request: Vapi.StructuredOutputControllerRemoveRequest,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutput>> {
        const { id } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                `structured-output/${core.url.encodePathParam(id)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.StructuredOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling DELETE /structured-output/{id}.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Vapi.UpdateStructuredOutputDto} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerUpdate({
     *         id: "id",
     *         schemaOverride: "schemaOverride"
     *     })
     */
    public structuredOutputControllerUpdate(
        request: Vapi.UpdateStructuredOutputDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutput> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerUpdate(request, requestOptions));
    }

    private async __structuredOutputControllerUpdate(
        request: Vapi.UpdateStructuredOutputDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutput>> {
        const { id, schemaOverride, ..._body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams.schemaOverride = schemaOverride;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                `structured-output/${core.url.encodePathParam(id)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.StructuredOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling PATCH /structured-output/{id}.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * @param {Vapi.StructuredOutputRunDto} request
     * @param {StructuredOutputsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.structuredOutputs.structuredOutputControllerRun({
     *         callIds: ["callIds"]
     *     })
     */
    public structuredOutputControllerRun(
        request: Vapi.StructuredOutputRunDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.StructuredOutput> {
        return core.HttpResponsePromise.fromPromise(this.__structuredOutputControllerRun(request, requestOptions));
    }

    private async __structuredOutputControllerRun(
        request: Vapi.StructuredOutputRunDto,
        requestOptions?: StructuredOutputsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.StructuredOutput>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "structured-output/run",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.StructuredOutput, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.VapiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.VapiError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.VapiTimeoutError("Timeout exceeded when calling POST /structured-output/run.");
            case "unknown":
                throw new errors.VapiError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
