// This file was auto-generated by Fern from our API Definition.

export const CampaignControllerFindAllRequestSortBy = {
    CreatedAt: "createdAt",
    Duration: "duration",
    Cost: "cost",
} as const;
export type CampaignControllerFindAllRequestSortBy =
    (typeof CampaignControllerFindAllRequestSortBy)[keyof typeof CampaignControllerFindAllRequestSortBy];
