// This file was auto-generated by Fern from our API Definition.

export const CampaignControllerFindAllV2RequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type CampaignControllerFindAllV2RequestSortOrder =
    (typeof CampaignControllerFindAllV2RequestSortOrder)[keyof typeof CampaignControllerFindAllV2RequestSortOrder];
