// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {}
 *     }
 */
export interface CampaignControllerUpdateV2Request {
    /** The unique identifier for the resource. */
    id: string;
    body: Vapi.UpdateCampaignDto;
}
