// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CampaignControllerRemoveV2Request {
    /** The unique identifier for the resource. */
    id: string;
}
