// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         name: "Q2 Sales Campaign"
 *     }
 */
export interface CreateCampaignDto {
    /** This is the name of the campaign. This is just for your own reference. */
    name: string;
    /** This is the assistant ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    assistantId?: string;
    /** This is the workflow ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    workflowId?: string;
    /** This is the squad ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    squadId?: string;
    /** This is the phone number ID that will be used for the campaign calls. Required if dialPlan is not provided. Note: phoneNumberId and dialPlan are mutually exclusive. */
    phoneNumberId?: string;
    /** This is a list of dial entries, each specifying a phone number and the customers to call using that number. Use this when you want different phone numbers to call different sets of customers. Note: phoneNumberId and dialPlan are mutually exclusive. */
    dialPlan?: Vapi.DialPlanEntry[];
    /** This is the schedule plan for the campaign. Calls will start at startedAt and continue until your organization’s concurrency limit is reached. Any remaining calls will be retried for up to one hour as capacity becomes available. After that hour or after latestAt, whichever comes first, any calls that couldn’t be placed won’t be retried. */
    schedulePlan?: Vapi.SchedulePlan;
    /** These are the customers that will be called in the campaign. Required if dialPlan is not provided. */
    customers?: Vapi.CreateCustomerDto[];
}
