// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface SimulationControllerFindOneRequest {
    /** The unique identifier of the simulation. */
    id: string;
}
