// This file was auto-generated by Fern from our API Definition.

import type { ProviderResourceControllerUpdateProviderResourceRequestProvider } from "../../types/ProviderResourceControllerUpdateProviderResourceRequestProvider.js";
import type { ProviderResourceControllerUpdateProviderResourceRequestResourceName } from "../../types/ProviderResourceControllerUpdateProviderResourceRequestResourceName.js";

/**
 * @example
 *     {
 *         provider: "cartesia",
 *         resourceName: "pronunciation-dictionary",
 *         id: "id"
 *     }
 */
export interface ProviderResourceControllerUpdateProviderResourceRequest {
    /** The provider (e.g., 11labs) */
    provider: ProviderResourceControllerUpdateProviderResourceRequestProvider;
    /** The resource name (e.g., pronunciation-dictionary) */
    resourceName: ProviderResourceControllerUpdateProviderResourceRequestResourceName;
    id: string;
}
