// This file was auto-generated by Fern from our API Definition.

import type { ProviderResourceControllerGetProviderResourceRequestProvider } from "../../types/ProviderResourceControllerGetProviderResourceRequestProvider.js";
import type { ProviderResourceControllerGetProviderResourceRequestResourceName } from "../../types/ProviderResourceControllerGetProviderResourceRequestResourceName.js";

/**
 * @example
 *     {
 *         provider: "cartesia",
 *         resourceName: "pronunciation-dictionary",
 *         id: "id"
 *     }
 */
export interface ProviderResourceControllerGetProviderResourceRequest {
    /** The provider (e.g., 11labs) */
    provider: ProviderResourceControllerGetProviderResourceRequestProvider;
    /** The resource name (e.g., pronunciation-dictionary) */
    resourceName: ProviderResourceControllerGetProviderResourceRequestResourceName;
    id: string;
}
