// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             provider: "byo-phone-number"
 *         }
 *     }
 */
export interface UpdatePhoneNumbersRequest {
    /** The unique identifier of the phone number. */
    id: string;
    body: Vapi.UpdatePhoneNumbersRequestBody;
}
