// This file was auto-generated by Fern from our API Definition.

import type { UpdatePhoneNumbersRequestBody } from "../../types/UpdatePhoneNumbersRequestBody.js";

/**
 * @example
 *     {
 *         id: "id",
 *         body: {
 *             provider: "byo-phone-number"
 *         }
 *     }
 */
export interface UpdatePhoneNumbersRequest {
    id: string;
    body: UpdatePhoneNumbersRequestBody;
}
