// This file was auto-generated by Fern from our API Definition.

export const ScenarioControllerFindAllRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type ScenarioControllerFindAllRequestSortOrder =
    (typeof ScenarioControllerFindAllRequestSortOrder)[keyof typeof ScenarioControllerFindAllRequestSortOrder];
