// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         assistantId: "assistantId"
 *     }
 */
export interface CreateTrafficAllocationDto {
    /** The assistant whose calls this allocation splits. */
    assistantId: string;
    /** 'explicit' splits calls across targets, and is inferred when targets is sent. 'follow-latest' sends every call to the newest published version and is how you stop splitting; it must be sent explicitly. */
    allocationIntent?: Vapi.CreateTrafficAllocationDtoAllocationIntent;
    /** The versions to split calls across. Omit to stop splitting (with allocationIntent 'follow-latest'). Order in this array is the selection order (position). */
    targets?: Vapi.CreateTrafficAllocationTargetDto[];
    /** Optional concurrency guard. Omit it and the write applies unconditionally (last write wins, matching every other Vapi update surface). Provide the id of the allocation you last read and the write applies only while that allocation is still governing; any mismatch is a 409 carrying the actual current id. */
    expectedCurrentAllocationId?: string;
    /** An optional note explaining why you made this change. */
    description?: string;
}
