// This file was auto-generated by Fern from our API Definition.

/** Selects an AI-evaluated workflow edge condition. */
export const AiEdgeConditionType = {
    Ai: "ai",
} as const;
export type AiEdgeConditionType = (typeof AiEdgeConditionType)[keyof typeof AiEdgeConditionType];
