// This file was auto-generated by Fern from our API Definition.

export const AiEdgeConditionType = {
    Ai: "ai",
} as const;
export type AiEdgeConditionType = (typeof AiEdgeConditionType)[keyof typeof AiEdgeConditionType];
