// This file was auto-generated by Fern from our API Definition.

export interface AnalysisCostBreakdown {
    /** This is the cost to summarize the call. */
    summary?: number | undefined;
    /** This is the number of prompt tokens used to summarize the call. */
    summaryPromptTokens?: number | undefined;
    /** This is the number of completion tokens used to summarize the call. */
    summaryCompletionTokens?: number | undefined;
    /** This is the number of cached prompt tokens used to summarize the call. */
    summaryCachedPromptTokens?: number | undefined;
    /** This is the cost to extract structured data from the call. */
    structuredData?: number | undefined;
    /** This is the number of prompt tokens used to extract structured data from the call. */
    structuredDataPromptTokens?: number | undefined;
    /** This is the number of completion tokens used to extract structured data from the call. */
    structuredDataCompletionTokens?: number | undefined;
    /** This is the number of cached prompt tokens used to extract structured data from the call. */
    structuredDataCachedPromptTokens?: number | undefined;
    /** This is the cost to evaluate if the call was successful. */
    successEvaluation?: number | undefined;
    /** This is the number of prompt tokens used to evaluate if the call was successful. */
    successEvaluationPromptTokens?: number | undefined;
    /** This is the number of completion tokens used to evaluate if the call was successful. */
    successEvaluationCompletionTokens?: number | undefined;
    /** This is the number of cached prompt tokens used to evaluate if the call was successful. */
    successEvaluationCachedPromptTokens?: number | undefined;
    /** This is the cost to evaluate structuredOutputs from the call. */
    structuredOutput?: number | undefined;
    /** This is the number of prompt tokens used to evaluate structuredOutputs from the call. */
    structuredOutputPromptTokens?: number | undefined;
    /** This is the number of completion tokens used to evaluate structuredOutputs from the call. */
    structuredOutputCompletionTokens?: number | undefined;
    /** This is the number of cached prompt tokens used to evaluate structuredOutputs from the call. */
    structuredOutputCachedPromptTokens?: number | undefined;
}
