// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Cost for an individual analysis request, including analysis type, model, token usage, and amount.
 */
export interface AnalysisCost {
    /** This is the type of analysis performed. */
    analysisType: Vapi.AnalysisCostAnalysisType;
    /** This is the model that was used to perform the analysis. */
    model: Record<string, unknown>;
    /** This is the number of prompt tokens used in the analysis. */
    promptTokens: number;
    /** This is the number of completion tokens generated in the analysis. */
    completionTokens: number;
    /** This is the number of cached prompt tokens used in the analysis. This is only applicable to certain providers (e.g., OpenAI, Azure OpenAI) that support prompt caching. Cached tokens are billed at a discounted rate. */
    cachedPromptTokens?: number | undefined;
    /**
     * This is the per-structured-output breakdown of this cost. The `cost`, `promptTokens`, `completionTokens` and `cachedPromptTokens` above are the sums of these rows.
     *
     * This is only set when `analysisType` is `structuredOutput`, and it is omitted entirely rather than partially populated, so when it is present the rows always reconcile to the totals above.
     *
     * A structured output that was skipped, or that extracts via regex, makes no LLM call and so has no row here — this is not a complete list of the call's configured structured outputs. There is one row per evaluation, so a `structuredOutputId` can appear more than once if it was evaluated more than once; sum the rows rather than indexing them by id.
     */
    structuredOutputBreakdown?: Vapi.StructuredOutputCostBreakdown[] | undefined;
    /** This is the cost of the component in USD. */
    cost: number;
}
