// This file was auto-generated by Fern from our API Definition.

import type { AnalyticsOperation } from "./AnalyticsOperation.js";
import type { AnalyticsQueryGroupByItem } from "./AnalyticsQueryGroupByItem.js";
import type { AnalyticsQueryTable } from "./AnalyticsQueryTable.js";
import type { TimeRange } from "./TimeRange.js";
import type { VariableValueGroupBy } from "./VariableValueGroupBy.js";

export interface AnalyticsQuery {
    /** This is the table you want to query. */
    table: AnalyticsQueryTable;
    /** This is the list of columns you want to group by. */
    groupBy?: AnalyticsQueryGroupByItem[] | undefined;
    /** This is the list of variable value keys you want to group by. */
    groupByVariableValue?: VariableValueGroupBy[] | undefined;
    /** This is the name of the query. This will be used to identify the query in the response. */
    name: string;
    /** This is the time range for the query. */
    timeRange?: TimeRange | undefined;
    /** This is the list of operations you want to perform. */
    operations: AnalyticsOperation[];
}
