// This file was auto-generated by Fern from our API Definition.

import type { AnthropicBedrockCredentialAuthenticationPlan } from "./AnthropicBedrockCredentialAuthenticationPlan.js";
import type { AnthropicBedrockCredentialProvider } from "./AnthropicBedrockCredentialProvider.js";
import type { AnthropicBedrockCredentialRegion } from "./AnthropicBedrockCredentialRegion.js";
import type { AwsStsAuthenticationArtifact } from "./AwsStsAuthenticationArtifact.js";
import type { AwsStsAuthenticationSession } from "./AwsStsAuthenticationSession.js";

export interface AnthropicBedrockCredential {
    provider: AnthropicBedrockCredentialProvider;
    /** AWS region where Bedrock is configured. */
    region: AnthropicBedrockCredentialRegion;
    /** Authentication method - either direct IAM credentials or cross-account role assumption. */
    authenticationPlan: AnthropicBedrockCredentialAuthenticationPlan;
    /** This is the unique identifier for the credential. */
    id: string;
    /** This is the unique identifier for the org that this credential belongs to. */
    orgId: string;
    /** This is the ISO 8601 date-time string of when the credential was created. */
    createdAt: string;
    /** This is the ISO 8601 date-time string of when the assistant was last updated. */
    updatedAt: string;
    /** Stores the external ID (generated or user-provided) for future AssumeRole calls. */
    authenticationArtifact?: AwsStsAuthenticationArtifact | undefined;
    /**
     * Cached authentication session from AssumeRole (temporary credentials).
     * Managed by the system, auto-refreshed when expired.
     */
    authenticationSession?: AwsStsAuthenticationSession | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
