// This file was auto-generated by Fern from our API Definition.

export const AssemblyAiTranscriberLanguageCodesItem = {
    En: "en",
    Es: "es",
    Fr: "fr",
    De: "de",
    It: "it",
    Pt: "pt",
    Tr: "tr",
    Nl: "nl",
    Sv: "sv",
    No: "no",
    Da: "da",
    Fi: "fi",
    Hi: "hi",
    Vi: "vi",
    Ar: "ar",
    He: "he",
    Ja: "ja",
    Zh: "zh",
} as const;
export type AssemblyAiTranscriberLanguageCodesItem =
    (typeof AssemblyAiTranscriberLanguageCodesItem)[keyof typeof AssemblyAiTranscriberLanguageCodesItem];
