// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Configuration for transcribing speech during assistant conversations with AssemblyAI, including language, streaming model, endpointing, vocabulary, and fallback settings.
 */
export interface AssemblyAiTranscriber {
    /** This is the language that will be set for the transcription. */
    language?: Vapi.AssemblyAiTranscriberLanguage | undefined;
    /**
     * Transcripts below this confidence threshold will be discarded.
     *
     * @default 0.4
     */
    confidenceThreshold?: number | undefined;
    /**
     * This enables formatting of transcripts.
     *
     * @default true
     */
    formatTurns?: boolean | undefined;
    /**
     * This is the end of turn confidence threshold. The minimum confidence that the end of turn is detected.
     * Note: Only used if startSpeakingPlan.smartEndpointingPlan is not set.
     * @min 0
     * @max 1
     * @default 0.7
     */
    endOfTurnConfidenceThreshold?: number | undefined;
    /**
     * This is the minimum end of turn silence when confident in milliseconds.
     * Note: Only used if startSpeakingPlan.smartEndpointingPlan is not set.
     * @default 160
     */
    minEndOfTurnSilenceWhenConfident?: number | undefined;
    wordFinalizationMaxWaitTime?: number | undefined;
    /**
     * This is the maximum turn silence time in milliseconds.
     * Note: Only used if startSpeakingPlan.smartEndpointingPlan is not set.
     * @default 400
     */
    maxTurnSilence?: number | undefined;
    /**
     * Use VAD to assist with endpointing decisions from the transcriber.
     * When enabled, transcriber endpointing will be buffered if VAD detects the user is still speaking, preventing premature turn-taking.
     * When disabled, transcriber endpointing will be used immediately regardless of VAD state, allowing for quicker but more aggressive turn-taking.
     * Note: Only used if startSpeakingPlan.smartEndpointingPlan is not set.
     *
     * @default true
     */
    vadAssistedEndpointingEnabled?: boolean | undefined;
    /**
     * This is the transcription mode used by the `universal-3-5-pro` speech model. Only applies to the `universal-3-5-pro` speech model.
     *
     * @default 'balanced'
     */
    mode?: Vapi.AssemblyAiTranscriberMode | undefined;
    /** This is a prompt that provides additional context to the transcription model. Only applies to the `universal-3-5-pro` speech model. */
    prompt?: string | undefined;
    /** This is context about the voice agent that guides the transcription model. Only applies to the `universal-3-5-pro` speech model. */
    agentContext?: string | undefined;
    /** These are language codes used to steer automatic language detection. Only applies to the `universal-3-5-pro` speech model. */
    languageCodes?: Vapi.AssemblyAiTranscriberLanguageCodesItem[] | undefined;
    /**
     * This is the speech model used for the streaming session.
     * Keyterms prompting is supported on universal-streaming-english and universal-3-5-pro.
     * universal-3-5-pro is AssemblyAI's most accurate voice-agent model.
     * @default 'universal-streaming-english'
     */
    speechModel?: Vapi.AssemblyAiTranscriberSpeechModel | undefined;
    /** The WebSocket URL that the transcriber connects to. */
    realtimeUrl?: string | undefined;
    /** Add up to 2500 characters of custom vocabulary. */
    wordBoost?: string[] | undefined;
    /**
     * Keyterms prompting improves recognition accuracy for specific words and phrases.
     * Can include up to 100 keyterms, each up to 50 characters.
     * Costs an additional $0.04/hour on universal-streaming-english and is included at no extra cost on universal-3-5-pro.
     */
    keytermsPrompt?: string[] | undefined;
    /** The duration of the end utterance silence threshold in milliseconds. */
    endUtteranceSilenceThreshold?: number | undefined;
    /**
     * Disable partial transcripts.
     * Set to `true` to not receive partial transcripts. Defaults to `false`.
     */
    disablePartialTranscripts?: boolean | undefined;
    /** This is the plan for transcriber provider fallbacks in the event that the primary transcriber provider fails. */
    fallbackPlan?: Vapi.FallbackTranscriberPlan | undefined;
}
