// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * These are the options for the assistant's voice.
 */
export type AssistantVoice =
    | Vapi.AssistantVoice.Azure
    | Vapi.AssistantVoice.Cartesia
    | Vapi.AssistantVoice.CustomVoice
    | Vapi.AssistantVoice.Deepgram
    | Vapi.AssistantVoice._11Labs
    | Vapi.AssistantVoice.Hume
    | Vapi.AssistantVoice.Lmnt
    | Vapi.AssistantVoice.Neuphonic
    | Vapi.AssistantVoice.Openai
    | Vapi.AssistantVoice.Playht
    | Vapi.AssistantVoice.Wellsaid
    | Vapi.AssistantVoice.RimeAi
    | Vapi.AssistantVoice.SmallestAi
    | Vapi.AssistantVoice.Tavus
    | Vapi.AssistantVoice.Vapi
    | Vapi.AssistantVoice.Sesame
    | Vapi.AssistantVoice.Inworld
    | Vapi.AssistantVoice.Minimax;

export namespace AssistantVoice {
    export interface Azure extends Vapi.AzureVoice {
        provider: "azure";
    }

    export interface Cartesia extends Vapi.CartesiaVoice {
        provider: "cartesia";
    }

    export interface CustomVoice extends Vapi.CustomVoice {
        provider: "custom-voice";
    }

    export interface Deepgram extends Vapi.DeepgramVoice {
        provider: "deepgram";
    }

    export interface _11Labs extends Vapi.ElevenLabsVoice {
        provider: "11labs";
    }

    export interface Hume extends Vapi.HumeVoice {
        provider: "hume";
    }

    export interface Lmnt extends Vapi.LmntVoice {
        provider: "lmnt";
    }

    export interface Neuphonic extends Vapi.NeuphonicVoice {
        provider: "neuphonic";
    }

    export interface Openai extends Vapi.OpenAiVoice {
        provider: "openai";
    }

    export interface Playht extends Vapi.PlayHtVoice {
        provider: "playht";
    }

    export interface Wellsaid extends Vapi.WellSaidVoice {
        provider: "wellsaid";
    }

    export interface RimeAi extends Vapi.RimeAiVoice {
        provider: "rime-ai";
    }

    export interface SmallestAi extends Vapi.SmallestAiVoice {
        provider: "smallest-ai";
    }

    export interface Tavus extends Vapi.TavusVoice {
        provider: "tavus";
    }

    export interface Vapi extends Vapi.VapiVoice {
        provider: "vapi";
    }

    export interface Sesame extends Vapi.SesameVoice {
        provider: "sesame";
    }

    export interface Inworld extends Vapi.InworldVoice {
        provider: "inworld";
    }

    export interface Minimax extends Vapi.MinimaxVoice {
        provider: "minimax";
    }
}
