// This file was auto-generated by Fern from our API Definition.

export const AssistantBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
export type AssistantBackgroundSoundZero =
    (typeof AssistantBackgroundSoundZero)[keyof typeof AssistantBackgroundSoundZero];
