// This file was auto-generated by Fern from our API Definition.

export const AssistantOverridesVoicemailDetectionZero = {
    Off: "off",
} as const;
export type AssistantOverridesVoicemailDetectionZero =
    (typeof AssistantOverridesVoicemailDetectionZero)[keyof typeof AssistantOverridesVoicemailDetectionZero];
