// This file was auto-generated by Fern from our API Definition.

import type { AzureVoice } from "./AzureVoice.js";
import type { CartesiaVoice } from "./CartesiaVoice.js";
import type { CustomVoice as CustomVoice_ } from "./CustomVoice.js";
import type { DeepgramVoice } from "./DeepgramVoice.js";
import type { ElevenLabsVoice } from "./ElevenLabsVoice.js";
import type { HumeVoice } from "./HumeVoice.js";
import type { InworldVoice } from "./InworldVoice.js";
import type { LmntVoice } from "./LmntVoice.js";
import type { MinimaxVoice } from "./MinimaxVoice.js";
import type { NeuphonicVoice } from "./NeuphonicVoice.js";
import type { OpenAiVoice } from "./OpenAiVoice.js";
import type { PlayHtVoice } from "./PlayHtVoice.js";
import type { RimeAiVoice } from "./RimeAiVoice.js";
import type { SesameVoice } from "./SesameVoice.js";
import type { SmallestAiVoice } from "./SmallestAiVoice.js";
import type { TavusVoice } from "./TavusVoice.js";
import type { VapiVoice } from "./VapiVoice.js";
import type { WellSaidVoice } from "./WellSaidVoice.js";

/**
 * These are the options for the assistant's voice.
 */
export type AssistantOverridesVoice =
    | AssistantOverridesVoice.Azure
    | AssistantOverridesVoice.Cartesia
    | AssistantOverridesVoice.CustomVoice
    | AssistantOverridesVoice.Deepgram
    | AssistantOverridesVoice._11Labs
    | AssistantOverridesVoice.Hume
    | AssistantOverridesVoice.Lmnt
    | AssistantOverridesVoice.Neuphonic
    | AssistantOverridesVoice.Openai
    | AssistantOverridesVoice.Playht
    | AssistantOverridesVoice.Wellsaid
    | AssistantOverridesVoice.RimeAi
    | AssistantOverridesVoice.SmallestAi
    | AssistantOverridesVoice.Tavus
    | AssistantOverridesVoice.Vapi
    | AssistantOverridesVoice.Sesame
    | AssistantOverridesVoice.Inworld
    | AssistantOverridesVoice.Minimax;

export namespace AssistantOverridesVoice {
    export interface Azure extends AzureVoice {
        provider: "azure";
    }

    export interface Cartesia extends CartesiaVoice {
        provider: "cartesia";
    }

    export interface CustomVoice extends CustomVoice_ {
        provider: "custom-voice";
    }

    export interface Deepgram extends DeepgramVoice {
        provider: "deepgram";
    }

    export interface _11Labs extends ElevenLabsVoice {
        provider: "11labs";
    }

    export interface Hume extends HumeVoice {
        provider: "hume";
    }

    export interface Lmnt extends LmntVoice {
        provider: "lmnt";
    }

    export interface Neuphonic extends NeuphonicVoice {
        provider: "neuphonic";
    }

    export interface Openai extends OpenAiVoice {
        provider: "openai";
    }

    export interface Playht extends PlayHtVoice {
        provider: "playht";
    }

    export interface Wellsaid extends WellSaidVoice {
        provider: "wellsaid";
    }

    export interface RimeAi extends RimeAiVoice {
        provider: "rime-ai";
    }

    export interface SmallestAi extends SmallestAiVoice {
        provider: "smallest-ai";
    }

    export interface Tavus extends TavusVoice {
        provider: "tavus";
    }

    export interface Vapi extends VapiVoice {
        provider: "vapi";
    }

    export interface Sesame extends SesameVoice {
        provider: "sesame";
    }

    export interface Inworld extends InworldVoice {
        provider: "inworld";
    }

    export interface Minimax extends MinimaxVoice {
        provider: "minimax";
    }
}
