// This file was auto-generated by Fern from our API Definition.

import type { AnalysisPlan } from "./AnalysisPlan.js";
import type { ArtifactPlan } from "./ArtifactPlan.js";
import type { AssistantOverridesBackgroundSound } from "./AssistantOverridesBackgroundSound.js";
import type { AssistantOverridesClientMessagesItem } from "./AssistantOverridesClientMessagesItem.js";
import type { AssistantOverridesCredentialsItem } from "./AssistantOverridesCredentialsItem.js";
import type { AssistantOverridesFirstMessageMode } from "./AssistantOverridesFirstMessageMode.js";
import type { AssistantOverridesHooksItem } from "./AssistantOverridesHooksItem.js";
import type { AssistantOverridesModel } from "./AssistantOverridesModel.js";
import type { AssistantOverridesServerMessagesItem } from "./AssistantOverridesServerMessagesItem.js";
import type { AssistantOverridesToolsAppendItem } from "./AssistantOverridesToolsAppendItem.js";
import type { AssistantOverridesTranscriber } from "./AssistantOverridesTranscriber.js";
import type { AssistantOverridesVoice } from "./AssistantOverridesVoice.js";
import type { AssistantOverridesVoicemailDetection } from "./AssistantOverridesVoicemailDetection.js";
import type { BackgroundSpeechDenoisingPlan } from "./BackgroundSpeechDenoisingPlan.js";
import type { CompliancePlan } from "./CompliancePlan.js";
import type { KeypadInputPlan } from "./KeypadInputPlan.js";
import type { LangfuseObservabilityPlan } from "./LangfuseObservabilityPlan.js";
import type { MonitorPlan } from "./MonitorPlan.js";
import type { Server } from "./Server.js";
import type { StartSpeakingPlan } from "./StartSpeakingPlan.js";
import type { StopSpeakingPlan } from "./StopSpeakingPlan.js";
import type { TransportConfigurationTwilio } from "./TransportConfigurationTwilio.js";

export interface AssistantOverrides {
    /** These are the options for the assistant's transcriber. */
    transcriber?: AssistantOverridesTranscriber | undefined;
    /** These are the options for the assistant's LLM. */
    model?: AssistantOverridesModel | undefined;
    /** These are the options for the assistant's voice. */
    voice?: AssistantOverridesVoice | undefined;
    /**
     * This is the first message that the assistant will say. This can also be a URL to a containerized audio file (mp3, wav, etc.).
     *
     * If unspecified, assistant will wait for user to speak and use the model to respond once they speak.
     */
    firstMessage?: string | undefined;
    firstMessageInterruptionsEnabled?: boolean | undefined;
    /**
     * This is the mode for the first message. Default is 'assistant-speaks-first'.
     *
     * Use:
     * - 'assistant-speaks-first' to have the assistant speak first.
     * - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
     * - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state. (`assistant.model.messages` at call start, `call.messages` at squad transfer points).
     *
     * @default 'assistant-speaks-first'
     */
    firstMessageMode?: AssistantOverridesFirstMessageMode | undefined;
    /**
     * These are the settings to configure or disable voicemail detection. Alternatively, voicemail detection can be configured using the model.tools=[VoicemailTool].
     * By default, voicemail detection is disabled.
     */
    voicemailDetection?: AssistantOverridesVoicemailDetection | undefined;
    /** These are the messages that will be sent to your Client SDKs. Default is conversation-update,function-call,hang,model-output,speech-update,status-update,transfer-update,transcript,tool-calls,user-interrupted,voice-input,workflow.node.started,assistant.started. You can check the shape of the messages in ClientMessage schema. */
    clientMessages?: AssistantOverridesClientMessagesItem[] | undefined;
    /** These are the messages that will be sent to your Server URL. Default is conversation-update,end-of-call-report,function-call,hang,speech-update,status-update,tool-calls,transfer-destination-request,handoff-destination-request,user-interrupted,assistant.started. You can check the shape of the messages in ServerMessage schema. */
    serverMessages?: AssistantOverridesServerMessagesItem[] | undefined;
    /**
     * This is the maximum number of seconds that the call will last. When the call reaches this duration, it will be ended.
     *
     * @default 600 (10 minutes)
     */
    maxDurationSeconds?: number | undefined;
    /**
     * This is the background sound in the call. Default for phone calls is 'office' and default for web calls is 'off'.
     * You can also provide a custom sound by providing a URL to an audio file.
     */
    backgroundSound?: AssistantOverridesBackgroundSound | undefined;
    /**
     * This determines whether the model's output is used in conversation history rather than the transcription of assistant's speech.
     *
     * @default false
     */
    modelOutputInMessagesEnabled?: boolean | undefined;
    /** These are the configurations to be passed to the transport providers of assistant's calls, like Twilio. You can store multiple configurations for different transport providers. For a call, only the configuration matching the call transport provider is used. */
    transportConfigurations?: TransportConfigurationTwilio[] | undefined;
    /**
     * This is the plan for observability of assistant's calls.
     *
     * Currently, only Langfuse is supported.
     */
    observabilityPlan?: LangfuseObservabilityPlan | undefined;
    /** These are dynamic credentials that will be used for the assistant calls. By default, all the credentials are available for use in the call but you can supplement an additional credentials using this. Dynamic credentials override existing credentials. */
    credentials?: AssistantOverridesCredentialsItem[] | undefined;
    /** This is a set of actions that will be performed on certain events. */
    hooks?: AssistantOverridesHooksItem[] | undefined;
    "tools:append"?: AssistantOverridesToolsAppendItem[] | undefined;
    /**
     * These are values that will be used to replace the template variables in the assistant messages and other text-based fields.
     * This uses LiquidJS syntax. https://liquidjs.com/tutorials/intro-to-liquid.html
     *
     * So for example, `{{ name }}` will be replaced with the value of `name` in `variableValues`.
     * `{{"now" | date: "%b %d, %Y, %I:%M %p", "America/New_York"}}` will be replaced with the current date and time in New York.
     *  Some VAPI reserved defaults:
     *  - *customer* - the customer object
     */
    variableValues?: Record<string, unknown> | undefined;
    /**
     * This is the name of the assistant.
     *
     * This is required when you want to transfer between assistants in a call.
     */
    name?: string | undefined;
    /**
     * This is the message that the assistant will say if the call is forwarded to voicemail.
     *
     * If unspecified, it will hang up.
     */
    voicemailMessage?: string | undefined;
    /**
     * This is the message that the assistant will say if it ends the call.
     *
     * If unspecified, it will hang up without saying anything.
     */
    endCallMessage?: string | undefined;
    /** This list contains phrases that, if spoken by the assistant, will trigger the call to be hung up. Case insensitive. */
    endCallPhrases?: string[] | undefined;
    compliancePlan?: CompliancePlan | undefined;
    /** This is for metadata you want to store on the assistant. */
    metadata?: Record<string, unknown> | undefined;
    /**
     * This enables filtering of noise and background speech while the user is talking.
     *
     * Features:
     * - Smart denoising using Krisp
     * - Fourier denoising
     *
     * Smart denoising can be combined with or used independently of Fourier denoising.
     *
     * Order of precedence:
     * - Smart denoising
     * - Fourier denoising
     */
    backgroundSpeechDenoisingPlan?: BackgroundSpeechDenoisingPlan | undefined;
    /** This is the plan for analysis of assistant's calls. Stored in `call.analysis`. */
    analysisPlan?: AnalysisPlan | undefined;
    /** This is the plan for artifacts generated during assistant's calls. Stored in `call.artifact`. */
    artifactPlan?: ArtifactPlan | undefined;
    /**
     * This is the plan for when the assistant should start talking.
     *
     * You should configure this if you're running into these issues:
     * - The assistant is too slow to start talking after the customer is done speaking.
     * - The assistant is too fast to start talking after the customer is done speaking.
     * - The assistant is so fast that it's actually interrupting the customer.
     */
    startSpeakingPlan?: StartSpeakingPlan | undefined;
    /**
     * This is the plan for when assistant should stop talking on customer interruption.
     *
     * You should configure this if you're running into these issues:
     * - The assistant is too slow to recognize customer's interruption.
     * - The assistant is too fast to recognize customer's interruption.
     * - The assistant is getting interrupted by phrases that are just acknowledgments.
     * - The assistant is getting interrupted by background noises.
     * - The assistant is not properly stopping -- it starts talking right after getting interrupted.
     */
    stopSpeakingPlan?: StopSpeakingPlan | undefined;
    /**
     * This is the plan for real-time monitoring of the assistant's calls.
     *
     * Usage:
     * - To enable live listening of the assistant's calls, set `monitorPlan.listenEnabled` to `true`.
     * - To enable live control of the assistant's calls, set `monitorPlan.controlEnabled` to `true`.
     * - To attach monitors to the assistant, set `monitorPlan.monitorIds` to the set of monitor ids.
     */
    monitorPlan?: MonitorPlan | undefined;
    /** These are the credentials that will be used for the assistant calls. By default, all the credentials are available for use in the call but you can provide a subset using this. */
    credentialIds?: string[] | undefined;
    /**
     * This is where Vapi will send webhooks. You can find all webhooks available along with their shape in ServerMessage schema.
     *
     * The order of precedence is:
     *
     * 1. assistant.server.url
     * 2. phoneNumber.serverUrl
     * 3. org.serverUrl
     */
    server?: Server | undefined;
    keypadInputPlan?: KeypadInputPlan | undefined;
}
