// This file was auto-generated by Fern from our API Definition.

export const AssistantVersionVoicemailDetectionZero = {
    Off: "off",
} as const;
export type AssistantVersionVoicemailDetectionZero =
    (typeof AssistantVersionVoicemailDetectionZero)[keyof typeof AssistantVersionVoicemailDetectionZero];
