// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface AssistantPaginatedResponse {
    results: Vapi.Assistant[];
    metadata: Vapi.PaginationMeta;
}
