// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface AssistantPinnedConflictResponseDto {
    error: Vapi.AssistantPinnedConflictResponseDtoError;
    /** Human-readable reason the parent-assistant delete was rejected. */
    message: string;
}
