// This file was auto-generated by Fern from our API Definition.

/**
 * This is the audio format of the call.
 *
 * @default 'pcm_s16le'
 */
export const AudioFormatFormat = {
    PcmS16Le: "pcm_s16le",
    Mulaw: "mulaw",
} as const;
export type AudioFormatFormat = (typeof AudioFormatFormat)[keyof typeof AudioFormatFormat];
