// This file was auto-generated by Fern from our API Definition.

/** This is the transcription provider that will be used. */
export const AzureSpeechTranscriberProvider = {
    Azure: "azure",
} as const;
export type AzureSpeechTranscriberProvider =
    (typeof AzureSpeechTranscriberProvider)[keyof typeof AzureSpeechTranscriberProvider];
