// This file was auto-generated by Fern from our API Definition.

import type { AzureVoiceId } from "./AzureVoiceId.js";
import type { ChunkPlan } from "./ChunkPlan.js";
import type { FallbackPlan } from "./FallbackPlan.js";

export interface AzureVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean | undefined;
    /** This is the provider-specific ID that will be used. */
    voiceId: AzureVoiceId;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: ChunkPlan | undefined;
    /** This is the speed multiplier that will be used. */
    speed?: number | undefined;
    /** This is the plan for voice provider fallbacks in the event that the primary voice provider fails. */
    fallbackPlan?: FallbackPlan | undefined;
}
