// This file was auto-generated by Fern from our API Definition.

/** Why validation failed. Only present when valid is false. */
export const BackgroundSoundUrlValidationResultReason = {
    InvalidUrl: "invalid-url",
    BlockedAddress: "blocked-address",
    Unreachable: "unreachable",
    Timeout: "timeout",
    TooManyRedirects: "too-many-redirects",
    HttpError: "http-error",
    NotAudio: "not-audio",
} as const;
export type BackgroundSoundUrlValidationResultReason =
    (typeof BackgroundSoundUrlValidationResultReason)[keyof typeof BackgroundSoundUrlValidationResultReason];
