// This file was auto-generated by Fern from our API Definition.

/**
 * Controls retry behavior for failed server requests, including strategy, maximum retries, base delay, and status codes excluded from retries.
 */
export interface BackoffPlan {
    /**
     * This is the type of backoff plan to use. Defaults to fixed.
     *
     * @default fixed
     */
    type: Record<string, unknown>;
    /**
     * This is the maximum number of retries to attempt if the request fails. Defaults to 0 (no retries).
     *
     * @default 0
     */
    maxRetries: number;
    /** Base delay in seconds. For fixed backoff, this is the delay between retries. For exponential backoff, this is the initial delay. */
    baseDelaySeconds: number;
    /** HTTP status codes that should not trigger a retry. By default, any non-2xx status code not listed here can be retried. */
    excludedStatusCodes?: Record<string, unknown>[] | undefined;
}
