// This file was auto-generated by Fern from our API Definition.

export interface BarInsightMetadata {
    xAxisLabel?: string;
    yAxisLabel?: string;
    yAxisMin?: number;
    yAxisMax?: number;
    name?: string;
}
