// This file was auto-generated by Fern from our API Definition.

/** The sub type of tool. */
export const BashToolWithToolCallSubType = {
    Bash20241022: "bash_20241022",
} as const;
export type BashToolWithToolCallSubType =
    (typeof BashToolWithToolCallSubType)[keyof typeof BashToolWithToolCallSubType];
