// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for authenticating outbound requests with a bearer token, including header name and optional `Bearer` prefix.
 */
export interface BearerAuthenticationPlan {
    /** This is the bearer token value. */
    token: string;
    /** This is the header name where the bearer token will be sent. Defaults to 'Authorization'. */
    headerName?: string | undefined;
    /** Whether to include the 'Bearer ' prefix in the header value. Defaults to true. */
    bearerPrefixEnabled?: boolean | undefined;
}
