// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface BoardMetricWidgetItem {
    type: Vapi.BoardMetricWidgetItemType;
    position: Vapi.BoardItemPosition;
    size: Vapi.BoardItemSize;
    insightId?: string | undefined;
    systemKey?: string | undefined;
}
