// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * This is the transport of the call.
 */
export type CallTransport =
    | Vapi.CallTransport.VapiWebsocket
    | Vapi.CallTransport.Vonage
    | Vapi.CallTransport.Twilio
    | Vapi.CallTransport.VapiSip
    | Vapi.CallTransport.Telnyx
    | Vapi.CallTransport.Daily;

export namespace CallTransport {
    export interface VapiWebsocket extends Vapi.VapiWebsocketTransport {
        provider: "vapi.websocket";
    }

    export interface Vonage extends Vapi.VonageTransport {
        provider: "vonage";
    }

    export interface Twilio extends Vapi.TwilioTransport {
        provider: "twilio";
    }

    export interface VapiSip extends Vapi.VapiSipTransport {
        provider: "vapi.sip";
    }

    export interface Telnyx extends Vapi.TelnyxTransport {
        provider: "telnyx";
    }

    export interface Daily extends Vapi.VapiWebCallTransport {
        provider: "daily";
    }
}
