// This file was auto-generated by Fern from our API Definition.

import type { Call } from "./Call.js";
import type { PaginationMeta } from "./PaginationMeta.js";

export interface CallPaginatedResponse {
    results: Call[];
    metadata: PaginationMeta;
}
