// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Runs configured actions when the assistant interrupts the customer's speech.
 */
export interface CallHookCustomerSpeechInterrupted {
    /** This is the event that triggers this hook */
    on: Vapi.CallHookCustomerSpeechInterruptedOn;
    /** This is the set of actions to perform when the hook triggers */
    do: Vapi.CallHookCustomerSpeechInterruptedDoItem[];
}
