// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface CallHookTranscriberEndpointedSpeechLowConfidence {
    /** This is the set of actions to perform when the hook triggers */
    do: Vapi.CallHookTranscriberEndpointedSpeechLowConfidenceDoItem[];
    /** This is the event that triggers this hook */
    on: string;
    /** This is the options for the hook including confidence thresholds */
    options?: Vapi.EndpointedSpeechLowConfidenceOptions;
}
