// This file was auto-generated by Fern from our API Definition.

import type { CallHookCustomerSpeechTimeoutDoItem } from "./CallHookCustomerSpeechTimeoutDoItem.js";
import type { CustomerSpeechTimeoutOptions } from "./CustomerSpeechTimeoutOptions.js";

export interface CallHookCustomerSpeechTimeout {
    /** Must be either "customer.speech.timeout" or match the pattern "customer.speech.timeout[property=value]" */
    on: string;
    /** This is the set of actions to perform when the hook triggers */
    do: CallHookCustomerSpeechTimeoutDoItem[];
    /** This is the set of filters that must match for the hook to trigger */
    options?: CustomerSpeechTimeoutOptions | undefined;
    /**
     * This is the name of the hook, it can be set by the user to identify the hook.
     * If no name is provided, the hook will be auto generated as UUID.
     *
     * @default UUID
     */
    name?: string | undefined;
}
