// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface CampaignContactWithOutcome {
    id: string;
    number: string;
    name?: string | undefined;
    status: Vapi.CampaignContactWithOutcomeStatus;
    callId?: string | undefined;
    dispatchedAt?: string | undefined;
    endedReason?: string | undefined;
}
