// This file was auto-generated by Fern from our API Definition.

export interface CartesiaPronunciationDictItem {
    /** The text to be replaced in pronunciation */
    text: string;
    /**
     * The pronunciation alias or IPA representation
     * Can be a "sounds-like" guidance (e.g., "VAH-pee") or IPA notation (e.g., "<<ˈ|v|ɑ|ˈ|p|i>>")
     */
    alias: string;
}
