// This file was auto-generated by Fern from our API Definition.

export const CartesiaTranscriberModel = {
    InkWhisper: "ink-whisper",
} as const;
export type CartesiaTranscriberModel = (typeof CartesiaTranscriberModel)[keyof typeof CartesiaTranscriberModel];
