// This file was auto-generated by Fern from our API Definition.

export const CartesiaCredentialProvider = {
    Cartesia: "cartesia",
} as const;
export type CartesiaCredentialProvider = (typeof CartesiaCredentialProvider)[keyof typeof CartesiaCredentialProvider];
