// This file was auto-generated by Fern from our API Definition.

import type { CartesiaTranscriberLanguage } from "./CartesiaTranscriberLanguage.js";
import type { CartesiaTranscriberModel } from "./CartesiaTranscriberModel.js";
import type { FallbackTranscriberPlan } from "./FallbackTranscriberPlan.js";

export interface CartesiaTranscriber {
    model?: CartesiaTranscriberModel | undefined;
    language?: CartesiaTranscriberLanguage | undefined;
    /** This is the plan for transcriber provider fallbacks in the event that the primary transcriber provider fails. */
    fallbackPlan?: FallbackTranscriberPlan | undefined;
}
