// This file was auto-generated by Fern from our API Definition.

export const CartesiaSpeedControlZero = {
    Slowest: "slowest",
    Slow: "slow",
    Normal: "normal",
    Fast: "fast",
    Fastest: "fastest",
} as const;
export type CartesiaSpeedControlZero = (typeof CartesiaSpeedControlZero)[keyof typeof CartesiaSpeedControlZero];
