// This file was auto-generated by Fern from our API Definition.

export interface CartesiaGenerationConfigExperimental {
    /** Toggle accent localization for sonic-3: 0 (disabled, default) or 1 (enabled). When enabled, the voice adapts to match the transcript language accent while preserving vocal characteristics. */
    accentLocalization?: number;
}
