// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type CerebrasModelToolsItem =
    | Vapi.CerebrasModelToolsItem.ApiRequest
    | Vapi.CerebrasModelToolsItem.Bash
    | Vapi.CerebrasModelToolsItem.Code
    | Vapi.CerebrasModelToolsItem.Computer
    | Vapi.CerebrasModelToolsItem.Dtmf
    | Vapi.CerebrasModelToolsItem.EndCall
    | Vapi.CerebrasModelToolsItem.Function
    | Vapi.CerebrasModelToolsItem.GohighlevelCalendarAvailabilityCheck
    | Vapi.CerebrasModelToolsItem.GohighlevelCalendarEventCreate
    | Vapi.CerebrasModelToolsItem.GohighlevelContactCreate
    | Vapi.CerebrasModelToolsItem.GohighlevelContactGet
    | Vapi.CerebrasModelToolsItem.GoogleCalendarAvailabilityCheck
    | Vapi.CerebrasModelToolsItem.GoogleCalendarEventCreate
    | Vapi.CerebrasModelToolsItem.GoogleSheetsRowAppend
    | Vapi.CerebrasModelToolsItem.Handoff
    | Vapi.CerebrasModelToolsItem.Mcp
    | Vapi.CerebrasModelToolsItem.Query
    | Vapi.CerebrasModelToolsItem.SlackMessageSend
    | Vapi.CerebrasModelToolsItem.Sms
    | Vapi.CerebrasModelToolsItem.TextEditor
    | Vapi.CerebrasModelToolsItem.TransferCall
    | Vapi.CerebrasModelToolsItem.SipRequest
    | Vapi.CerebrasModelToolsItem.Voicemail;

export namespace CerebrasModelToolsItem {
    export interface ApiRequest extends Vapi.CreateApiRequestToolDto {
        type: "apiRequest";
    }

    export interface Bash extends Vapi.CreateBashToolDto {
        type: "bash";
    }

    export interface Code extends Vapi.CreateCodeToolDto {
        type: "code";
    }

    export interface Computer extends Vapi.CreateComputerToolDto {
        type: "computer";
    }

    export interface Dtmf extends Vapi.CreateDtmfToolDto {
        type: "dtmf";
    }

    export interface EndCall extends Vapi.CreateEndCallToolDto {
        type: "endCall";
    }

    export interface Function extends Vapi.CreateFunctionToolDto {
        type: "function";
    }

    export interface GohighlevelCalendarAvailabilityCheck extends Vapi.CreateGoHighLevelCalendarAvailabilityToolDto {
        type: "gohighlevel.calendar.availability.check";
    }

    export interface GohighlevelCalendarEventCreate extends Vapi.CreateGoHighLevelCalendarEventCreateToolDto {
        type: "gohighlevel.calendar.event.create";
    }

    export interface GohighlevelContactCreate extends Vapi.CreateGoHighLevelContactCreateToolDto {
        type: "gohighlevel.contact.create";
    }

    export interface GohighlevelContactGet extends Vapi.CreateGoHighLevelContactGetToolDto {
        type: "gohighlevel.contact.get";
    }

    export interface GoogleCalendarAvailabilityCheck extends Vapi.CreateGoogleCalendarCheckAvailabilityToolDto {
        type: "google.calendar.availability.check";
    }

    export interface GoogleCalendarEventCreate extends Vapi.CreateGoogleCalendarCreateEventToolDto {
        type: "google.calendar.event.create";
    }

    export interface GoogleSheetsRowAppend extends Vapi.CreateGoogleSheetsRowAppendToolDto {
        type: "google.sheets.row.append";
    }

    export interface Handoff extends Vapi.CreateHandoffToolDto {
        type: "handoff";
    }

    export interface Mcp extends Vapi.CreateMcpToolDto {
        type: "mcp";
    }

    export interface Query extends Vapi.CreateQueryToolDto {
        type: "query";
    }

    export interface SlackMessageSend extends Vapi.CreateSlackSendMessageToolDto {
        type: "slack.message.send";
    }

    export interface Sms extends Vapi.CreateSmsToolDto {
        type: "sms";
    }

    export interface TextEditor extends Vapi.CreateTextEditorToolDto {
        type: "textEditor";
    }

    export interface TransferCall extends Vapi.CreateTransferCallToolDto {
        type: "transferCall";
    }

    export interface SipRequest extends Vapi.CreateSipRequestToolDto {
        type: "sipRequest";
    }

    export interface Voicemail extends Vapi.CreateVoicemailToolDto {
        type: "voicemail";
    }
}
