// This file was auto-generated by Fern from our API Definition.

export const CerebrasCredentialProvider = {
    Cerebras: "cerebras",
} as const;
export type CerebrasCredentialProvider = (typeof CerebrasCredentialProvider)[keyof typeof CerebrasCredentialProvider];
