// This file was auto-generated by Fern from our API Definition.

import type { Call } from "./Call.js";
import type { ClientMessageConversationUpdateMessagesItem } from "./ClientMessageConversationUpdateMessagesItem.js";
import type { ClientMessageConversationUpdatePhoneNumber } from "./ClientMessageConversationUpdatePhoneNumber.js";
import type { ClientMessageConversationUpdateType } from "./ClientMessageConversationUpdateType.js";
import type { CreateAssistantDto } from "./CreateAssistantDto.js";
import type { CreateCustomerDto } from "./CreateCustomerDto.js";
import type { OpenAiMessage } from "./OpenAiMessage.js";

export interface ClientMessageConversationUpdate {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: ClientMessageConversationUpdatePhoneNumber | undefined;
    /** This is the type of the message. "conversation-update" is sent when an update is committed to the conversation history. */
    type: ClientMessageConversationUpdateType;
    /** This is the most up-to-date conversation history at the time the message is sent. */
    messages?: ClientMessageConversationUpdateMessagesItem[] | undefined;
    /** This is the most up-to-date conversation history at the time the message is sent, formatted for OpenAI. */
    messagesOpenAIFormatted: OpenAiMessage[];
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /** This is the call that the message is associated with. */
    call?: Call | undefined;
    /** This is the customer that the message is associated with. */
    customer?: CreateCustomerDto | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: CreateAssistantDto | undefined;
}
