// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface ClientMessageSpeechUpdate {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: Vapi.ClientMessageSpeechUpdatePhoneNumber | undefined;
    /** This is the type of the message. "speech-update" is sent whenever assistant or user start or stop speaking. */
    type: Vapi.ClientMessageSpeechUpdateType;
    /** This is the status of the speech update. */
    status: Vapi.ClientMessageSpeechUpdateStatus;
    /** This is the role which the speech update is for. */
    role: Vapi.ClientMessageSpeechUpdateRole;
    /** This is the turn number of the speech update (0-indexed). */
    turn?: number | undefined;
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /** This is the call that the message is associated with. */
    call?: Vapi.Call | undefined;
    /** This is the customer that the message is associated with. */
    customer?: Vapi.CreateCustomerDto | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: Vapi.CreateAssistantDto | undefined;
}
