// This file was auto-generated by Fern from our API Definition.

import type { Call } from "./Call.js";
import type { Chat } from "./Chat.js";
import type { ClientMessageChatCreatedPhoneNumber } from "./ClientMessageChatCreatedPhoneNumber.js";
import type { ClientMessageChatCreatedType } from "./ClientMessageChatCreatedType.js";
import type { CreateAssistantDto } from "./CreateAssistantDto.js";
import type { CreateCustomerDto } from "./CreateCustomerDto.js";

export interface ClientMessageChatCreated {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: ClientMessageChatCreatedPhoneNumber | undefined;
    /** This is the type of the message. "chat.created" is sent when a new chat is created. */
    type: ClientMessageChatCreatedType;
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /** This is the call that the message is associated with. */
    call?: Call | undefined;
    /** This is the customer that the message is associated with. */
    customer?: CreateCustomerDto | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: CreateAssistantDto | undefined;
    /** This is the chat that was created. */
    chat: Chat;
}
