// This file was auto-generated by Fern from our API Definition.

import type { ClientInboundMessageTransferDestination } from "./ClientInboundMessageTransferDestination.js";

export interface ClientInboundMessageTransfer {
    /** This is the destination to transfer the call to. */
    destination?: ClientInboundMessageTransferDestination | undefined;
    /** This is the content to say. */
    content?: string | undefined;
}
