// This file was auto-generated by Fern from our API Definition.

import type { Call } from "./Call.js";
import type { ClientMessageSessionUpdatedPhoneNumber } from "./ClientMessageSessionUpdatedPhoneNumber.js";
import type { ClientMessageSessionUpdatedType } from "./ClientMessageSessionUpdatedType.js";
import type { CreateAssistantDto } from "./CreateAssistantDto.js";
import type { CreateCustomerDto } from "./CreateCustomerDto.js";
import type { Session } from "./Session.js";

export interface ClientMessageSessionUpdated {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: ClientMessageSessionUpdatedPhoneNumber | undefined;
    /** This is the type of the message. "session.updated" is sent when a session is updated. */
    type: ClientMessageSessionUpdatedType;
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /** This is the call that the message is associated with. */
    call?: Call | undefined;
    /** This is the customer that the message is associated with. */
    customer?: CreateCustomerDto | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: CreateAssistantDto | undefined;
    /** This is the session that was updated. */
    session: Session;
}
