// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * This is the phone number that the message is associated with.
 */
export type ClientMessageToolCallsResultPhoneNumber =
    | Vapi.ClientMessageToolCallsResultPhoneNumber.ByoPhoneNumber
    | Vapi.ClientMessageToolCallsResultPhoneNumber.Twilio
    | Vapi.ClientMessageToolCallsResultPhoneNumber.Vonage
    | Vapi.ClientMessageToolCallsResultPhoneNumber.Vapi
    | Vapi.ClientMessageToolCallsResultPhoneNumber.Telnyx;

export namespace ClientMessageToolCallsResultPhoneNumber {
    export interface ByoPhoneNumber extends Vapi.CreateByoPhoneNumberDto {
        provider: "byo-phone-number";
    }

    export interface Twilio extends Vapi.CreateTwilioPhoneNumberDto {
        provider: "twilio";
    }

    export interface Vonage extends Vapi.CreateVonagePhoneNumberDto {
        provider: "vonage";
    }

    export interface Vapi extends Vapi.CreateVapiPhoneNumberDto {
        provider: "vapi";
    }

    export interface Telnyx extends Vapi.CreateTelnyxPhoneNumberDto {
        provider: "telnyx";
    }
}
