// This file was auto-generated by Fern from our API Definition.

import type { CreateByoPhoneNumberDto } from "./CreateByoPhoneNumberDto.js";
import type { CreateTelnyxPhoneNumberDto } from "./CreateTelnyxPhoneNumberDto.js";
import type { CreateTwilioPhoneNumberDto } from "./CreateTwilioPhoneNumberDto.js";
import type { CreateVapiPhoneNumberDto } from "./CreateVapiPhoneNumberDto.js";
import type { CreateVonagePhoneNumberDto } from "./CreateVonagePhoneNumberDto.js";

/**
 * This is the phone number that the message is associated with.
 */
export type ClientMessageSpeechUpdatePhoneNumber =
    | ClientMessageSpeechUpdatePhoneNumber.ByoPhoneNumber
    | ClientMessageSpeechUpdatePhoneNumber.Twilio
    | ClientMessageSpeechUpdatePhoneNumber.Vonage
    | ClientMessageSpeechUpdatePhoneNumber.Vapi
    | ClientMessageSpeechUpdatePhoneNumber.Telnyx;

export namespace ClientMessageSpeechUpdatePhoneNumber {
    export interface ByoPhoneNumber extends CreateByoPhoneNumberDto {
        provider: "byo-phone-number";
    }

    export interface Twilio extends CreateTwilioPhoneNumberDto {
        provider: "twilio";
    }

    export interface Vonage extends CreateVonagePhoneNumberDto {
        provider: "vonage";
    }

    export interface Vapi extends CreateVapiPhoneNumberDto {
        provider: "vapi";
    }

    export interface Telnyx extends CreateTelnyxPhoneNumberDto {
        provider: "telnyx";
    }
}
