// This file was auto-generated by Fern from our API Definition.

/** This is the type of the message. "chat.deleted" is sent when a chat is deleted. */
export const ClientMessageChatDeletedType = {
    ChatDeleted: "chat.deleted",
} as const;
export type ClientMessageChatDeletedType =
    (typeof ClientMessageChatDeletedType)[keyof typeof ClientMessageChatDeletedType];
