// This file was auto-generated by Fern from our API Definition.

import type { ClientMessageMessage } from "./ClientMessageMessage.js";

export interface ClientMessage {
    /** These are all the messages that can be sent to the client-side SDKs during the call. Configure the messages you'd like to receive in `assistant.clientMessages`. */
    message: ClientMessageMessage;
}
