// This file was auto-generated by Fern from our API Definition.

import type { Call } from "./Call.js";
import type { ClientMessageWorkflowNodeStartedPhoneNumber } from "./ClientMessageWorkflowNodeStartedPhoneNumber.js";
import type { ClientMessageWorkflowNodeStartedType } from "./ClientMessageWorkflowNodeStartedType.js";
import type { CreateAssistantDto } from "./CreateAssistantDto.js";
import type { CreateCustomerDto } from "./CreateCustomerDto.js";

export interface ClientMessageWorkflowNodeStarted {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: ClientMessageWorkflowNodeStartedPhoneNumber | undefined;
    /** This is the type of the message. "workflow.node.started" is sent when the active node changes. */
    type: ClientMessageWorkflowNodeStartedType;
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /** This is the call that the message is associated with. */
    call?: Call | undefined;
    /** This is the customer that the message is associated with. */
    customer?: CreateCustomerDto | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: CreateAssistantDto | undefined;
    /** This is the active node. */
    node: Record<string, unknown>;
}
