// This file was auto-generated by Fern from our API Definition.

import type { ClientMessageAssistantSpeech } from "./ClientMessageAssistantSpeech.js";
import type { ClientMessageAssistantStarted } from "./ClientMessageAssistantStarted.js";
import type { ClientMessageCallDeleted } from "./ClientMessageCallDeleted.js";
import type { ClientMessageCallDeleteFailed } from "./ClientMessageCallDeleteFailed.js";
import type { ClientMessageChatCreated } from "./ClientMessageChatCreated.js";
import type { ClientMessageChatDeleted } from "./ClientMessageChatDeleted.js";
import type { ClientMessageConversationUpdate } from "./ClientMessageConversationUpdate.js";
import type { ClientMessageHang } from "./ClientMessageHang.js";
import type { ClientMessageLanguageChangeDetected } from "./ClientMessageLanguageChangeDetected.js";
import type { ClientMessageMetadata } from "./ClientMessageMetadata.js";
import type { ClientMessageModelOutput } from "./ClientMessageModelOutput.js";
import type { ClientMessageSessionCreated } from "./ClientMessageSessionCreated.js";
import type { ClientMessageSessionDeleted } from "./ClientMessageSessionDeleted.js";
import type { ClientMessageSessionUpdated } from "./ClientMessageSessionUpdated.js";
import type { ClientMessageSpeechUpdate } from "./ClientMessageSpeechUpdate.js";
import type { ClientMessageToolCalls } from "./ClientMessageToolCalls.js";
import type { ClientMessageToolCallsResult } from "./ClientMessageToolCallsResult.js";
import type { ClientMessageTranscript } from "./ClientMessageTranscript.js";
import type { ClientMessageTransferUpdate } from "./ClientMessageTransferUpdate.js";
import type { ClientMessageUserInterrupted } from "./ClientMessageUserInterrupted.js";
import type { ClientMessageVoiceInput } from "./ClientMessageVoiceInput.js";
import type { ClientMessageWorkflowNodeStarted } from "./ClientMessageWorkflowNodeStarted.js";

/**
 * These are all the messages that can be sent to the client-side SDKs during the call. Configure the messages you'd like to receive in `assistant.clientMessages`.
 */
export type ClientMessageMessage =
    | ClientMessageWorkflowNodeStarted
    | ClientMessageAssistantStarted
    | ClientMessageConversationUpdate
    | ClientMessageHang
    | ClientMessageMetadata
    | ClientMessageModelOutput
    | ClientMessageSpeechUpdate
    | ClientMessageTranscript
    | ClientMessageToolCalls
    | ClientMessageToolCallsResult
    | ClientMessageTransferUpdate
    | ClientMessageUserInterrupted
    | ClientMessageLanguageChangeDetected
    | ClientMessageVoiceInput
    | ClientMessageAssistantSpeech
    | ClientMessageChatCreated
    | ClientMessageChatDeleted
    | ClientMessageSessionCreated
    | ClientMessageSessionUpdated
    | ClientMessageSessionDeleted
    | ClientMessageCallDeleted
    | ClientMessageCallDeleteFailed;
