// This file was auto-generated by Fern from our API Definition.

import type { ClientInboundMessageControlControl } from "./ClientInboundMessageControlControl.js";

export interface ClientInboundMessageControl {
    /** This is the control action */
    control: ClientInboundMessageControlControl;
}
