// This file was auto-generated by Fern from our API Definition.

export interface CloudflareR2BucketPlan {
    /** Cloudflare R2 Access key ID. */
    accessKeyId?: string | undefined;
    /** Cloudflare R2 access key secret. This is not returned in the API. */
    secretAccessKey?: string | undefined;
    /** Cloudflare R2 base url. */
    url?: string | undefined;
    /** This is the name of the bucket. */
    name: string;
    /**
     * This is the path where call artifacts will be stored.
     *
     * Usage:
     * - To store call artifacts in a specific folder, set this to the full path. Eg. "/folder-name1/folder-name2".
     * - To store call artifacts in the root of the bucket, leave this blank.
     *
     * @default "/"
     */
    path?: string | undefined;
}
