// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Compliance information captured for a call, including recording consent.
 */
export interface Compliance {
    /** This is the recording consent of the call. Configure in `assistant.compliancePlan.recordingConsentPlan`. */
    recordingConsent?: Vapi.RecordingConsent | undefined;
}
