// This file was auto-generated by Fern from our API Definition.

export interface ContextEngineeringPlanLastNMessages {
    /** This is the maximum number of messages to include in the context engineering plan. */
    maxMessages: number;
}
