// This file was auto-generated by Fern from our API Definition.

/**
 * Excludes prior conversation messages when constructing context for a handoff.
 */
export type ContextEngineeringPlanNone = {};
