// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface CreateSupabaseCredentialDto {
    /** This is the order in which this storage provider is tried during upload retries. Lower numbers are tried first in increasing order. */
    fallbackIndex?: number | undefined;
    bucketPlan?: Vapi.SupabaseBucketPlan | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
