// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Configuration used to create an outbound calling campaign. Choose an assistant, squad, or workflow, then provide customers, phone-number or dial-plan settings, and an optional schedule.
 */
export interface CreateCampaignDto {
    /** This is the name of the campaign. This is just for your own reference. */
    name: string;
    /** This is the assistant ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    assistantId?: string | undefined;
    /** This is the workflow ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    workflowId?: string | undefined;
    /** This is the squad ID that will be used for the campaign calls. Note: Only one of assistantId, workflowId, or squadId can be used. */
    squadId?: string | undefined;
    /** This is the phone number ID that will be used for the campaign calls. Required if dialPlan is not provided. Note: phoneNumberId and dialPlan are mutually exclusive. */
    phoneNumberId?: string | undefined;
    /** This is a list of dial entries, each specifying a phone number and the customers to call using that number. Use this when you want different phone numbers to call different sets of customers. Note: phoneNumberId and dialPlan are mutually exclusive. */
    dialPlan?: Vapi.DialPlanEntry[] | undefined;
    /** This is the schedule plan for the campaign. Calls will start at startedAt and continue until your organization’s concurrency limit is reached. Any remaining calls will be retried for up to one hour as capacity becomes available. After that hour or after latestAt, whichever comes first, any calls that couldn’t be placed won’t be retried. */
    schedulePlan?: Vapi.SchedulePlan | undefined;
    /** These are the customers that will be called in the campaign. Required if dialPlan is not provided. Maximum of 10000 customers per campaign. */
    customers?: Vapi.CreateCustomerDto[] | undefined;
    /** This is the maximum number of concurrent calls that will be made for the campaign. Defaults to 10. Maximum of 500, and may not exceed your organization's concurrency limit. */
    maxConcurrency?: number | undefined;
    /** These are the overrides for the assistant's settings and template variables for the campaign. Use this when the campaign targets an `assistantId`. */
    assistantOverrides?: Vapi.AssistantOverrides | undefined;
    /** These are the overrides for the squad and template variables for the campaign. Use this when the campaign targets a `squadId`. Per-contact `squadOverrides` are deep-merged on top of this at dispatch time. */
    squadOverrides?: Vapi.AssistantOverrides | undefined;
    /** This is the server (URL, auth headers, timeout, etc.) for the campaign webhooks. */
    server?: Vapi.Server | undefined;
    /** These are the messages that will be sent to your Server URL. */
    serverMessages?: Vapi.CreateCampaignDtoServerMessagesItem[] | undefined;
    /** This opts the campaign into the blocking `campaign.predial` eligibility webhook. When set, every contact triggers a `campaign.predial` POST to the Server URL before dialing, and the response `{ eligible: boolean }` decides whether the call is placed. Requires `server`. When unset, no pre-dial webhook is sent. */
    predialPlan?: Vapi.CampaignPredialPlan | undefined;
    /** Optional campaign ID to duplicate config from. Provided fields in the request override the source. If `customers` is omitted, contacts are copied from the source. */
    duplicateFromCampaignId?: string | undefined;
}
