// This file was auto-generated by Fern from our API Definition.

import type { CreateTestSuiteTestVoiceDtoType } from "./CreateTestSuiteTestVoiceDtoType.js";
import type { TestSuiteTestScorerAi } from "./TestSuiteTestScorerAi.js";

export interface CreateTestSuiteTestVoiceDto {
    /** These are the scorers used to evaluate the test. */
    scorers: TestSuiteTestScorerAi[];
    /** This is the type of the test, which must be voice. */
    type: CreateTestSuiteTestVoiceDtoType;
    /** This is the script to be used for the voice test. */
    script: string;
    /** This is the number of attempts allowed for the test. */
    numAttempts?: number | undefined;
    /** This is the name of the test. */
    name?: string | undefined;
}
