// This file was auto-generated by Fern from our API Definition.

/**
 * Credentials for authenticating telephony requests with Vonage.
 */
export interface CreateVonageCredentialDto {
    /** This is not returned in the API. */
    apiSecret: string;
    /** Vonage API key associated with the credential. */
    apiKey: string;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
