// This file was auto-generated by Fern from our API Definition.

/** This is the SIP method to send (sip-request tool). */
export const CreateToolDraftDtoVerb = {
    Info: "INFO",
    Message: "MESSAGE",
    Notify: "NOTIFY",
} as const;
export type CreateToolDraftDtoVerb = (typeof CreateToolDraftDtoVerb)[keyof typeof CreateToolDraftDtoVerb];
