// This file was auto-generated by Fern from our API Definition.

export interface CreateSimulationDto {
    /** This is an optional friendly name for the simulation. */
    name?: string | undefined;
    /** This is the ID of the scenario to use for this simulation. */
    scenarioId: string;
    /** This is the ID of the personality to use for this simulation. */
    personalityId: string;
    /**
     * Optional folder path for organizing simulations.
     * Supports up to 3 levels (e.g., "dept/feature/variant").
     * Maps to GitOps resource folder structure.
     */
    path?: (string | null) | undefined;
}
