// This file was auto-generated by Fern from our API Definition.

import type { CreateAnthropicBedrockCredentialDto } from "./CreateAnthropicBedrockCredentialDto.js";
import type { CreateAnthropicCredentialDto } from "./CreateAnthropicCredentialDto.js";
import type { CreateAnyscaleCredentialDto } from "./CreateAnyscaleCredentialDto.js";
import type { CreateAssemblyAiCredentialDto } from "./CreateAssemblyAiCredentialDto.js";
import type { CreateAzureCredentialDto } from "./CreateAzureCredentialDto.js";
import type { CreateAzureOpenAiCredentialDto } from "./CreateAzureOpenAiCredentialDto.js";
import type { CreateByoSipTrunkCredentialDto } from "./CreateByoSipTrunkCredentialDto.js";
import type { CreateCartesiaCredentialDto } from "./CreateCartesiaCredentialDto.js";
import type { CreateCerebrasCredentialDto } from "./CreateCerebrasCredentialDto.js";
import type { CreateCloudflareCredentialDto } from "./CreateCloudflareCredentialDto.js";
import type { CreateCustomCredentialDto } from "./CreateCustomCredentialDto.js";
import type { CreateCustomLlmCredentialDto } from "./CreateCustomLlmCredentialDto.js";
import type { CreateDeepgramCredentialDto } from "./CreateDeepgramCredentialDto.js";
import type { CreateDeepInfraCredentialDto } from "./CreateDeepInfraCredentialDto.js";
import type { CreateDeepSeekCredentialDto } from "./CreateDeepSeekCredentialDto.js";
import type { CreateElevenLabsCredentialDto } from "./CreateElevenLabsCredentialDto.js";
import type { CreateEmailCredentialDto } from "./CreateEmailCredentialDto.js";
import type { CreateGcpCredentialDto } from "./CreateGcpCredentialDto.js";
import type { CreateGladiaCredentialDto } from "./CreateGladiaCredentialDto.js";
import type { CreateGoHighLevelCredentialDto } from "./CreateGoHighLevelCredentialDto.js";
import type { CreateGoHighLevelMcpCredentialDto } from "./CreateGoHighLevelMcpCredentialDto.js";
import type { CreateGoogleCalendarOAuth2AuthorizationCredentialDto } from "./CreateGoogleCalendarOAuth2AuthorizationCredentialDto.js";
import type { CreateGoogleCalendarOAuth2ClientCredentialDto } from "./CreateGoogleCalendarOAuth2ClientCredentialDto.js";
import type { CreateGoogleCredentialDto } from "./CreateGoogleCredentialDto.js";
import type { CreateGoogleSheetsOAuth2AuthorizationCredentialDto } from "./CreateGoogleSheetsOAuth2AuthorizationCredentialDto.js";
import type { CreateGroqCredentialDto } from "./CreateGroqCredentialDto.js";
import type { CreateHumeCredentialDto } from "./CreateHumeCredentialDto.js";
import type { CreateInflectionAiCredentialDto } from "./CreateInflectionAiCredentialDto.js";
import type { CreateInworldCredentialDto } from "./CreateInworldCredentialDto.js";
import type { CreateLangfuseCredentialDto } from "./CreateLangfuseCredentialDto.js";
import type { CreateLmntCredentialDto } from "./CreateLmntCredentialDto.js";
import type { CreateMakeCredentialDto } from "./CreateMakeCredentialDto.js";
import type { CreateMinimaxCredentialDto } from "./CreateMinimaxCredentialDto.js";
import type { CreateMistralCredentialDto } from "./CreateMistralCredentialDto.js";
import type { CreateNeuphonicCredentialDto } from "./CreateNeuphonicCredentialDto.js";
import type { CreateOpenAiCredentialDto } from "./CreateOpenAiCredentialDto.js";
import type { CreateOpenRouterCredentialDto } from "./CreateOpenRouterCredentialDto.js";
import type { CreatePerplexityAiCredentialDto } from "./CreatePerplexityAiCredentialDto.js";
import type { CreatePlayHtCredentialDto } from "./CreatePlayHtCredentialDto.js";
import type { CreateRimeAiCredentialDto } from "./CreateRimeAiCredentialDto.js";
import type { CreateRunpodCredentialDto } from "./CreateRunpodCredentialDto.js";
import type { CreateS3CredentialDto } from "./CreateS3CredentialDto.js";
import type { CreateSlackOAuth2AuthorizationCredentialDto } from "./CreateSlackOAuth2AuthorizationCredentialDto.js";
import type { CreateSlackWebhookCredentialDto } from "./CreateSlackWebhookCredentialDto.js";
import type { CreateSmallestAiCredentialDto } from "./CreateSmallestAiCredentialDto.js";
import type { CreateSonioxCredentialDto } from "./CreateSonioxCredentialDto.js";
import type { CreateSpeechmaticsCredentialDto } from "./CreateSpeechmaticsCredentialDto.js";
import type { CreateSupabaseCredentialDto } from "./CreateSupabaseCredentialDto.js";
import type { CreateTavusCredentialDto } from "./CreateTavusCredentialDto.js";
import type { CreateTogetherAiCredentialDto } from "./CreateTogetherAiCredentialDto.js";
import type { CreateTrieveCredentialDto } from "./CreateTrieveCredentialDto.js";
import type { CreateTwilioCredentialDto } from "./CreateTwilioCredentialDto.js";
import type { CreateVonageCredentialDto } from "./CreateVonageCredentialDto.js";
import type { CreateWebhookCredentialDto } from "./CreateWebhookCredentialDto.js";
import type { CreateWellSaidCredentialDto } from "./CreateWellSaidCredentialDto.js";
import type { CreateXAiCredentialDto } from "./CreateXAiCredentialDto.js";

export type CreateAssistantDtoCredentialsItem =
    | CreateAssistantDtoCredentialsItem._11Labs
    | CreateAssistantDtoCredentialsItem.Anthropic
    | CreateAssistantDtoCredentialsItem.AnthropicBedrock
    | CreateAssistantDtoCredentialsItem.Anyscale
    | CreateAssistantDtoCredentialsItem.AssemblyAi
    | CreateAssistantDtoCredentialsItem.AzureOpenai
    | CreateAssistantDtoCredentialsItem.Azure
    | CreateAssistantDtoCredentialsItem.ByoSipTrunk
    | CreateAssistantDtoCredentialsItem.Cartesia
    | CreateAssistantDtoCredentialsItem.Cerebras
    | CreateAssistantDtoCredentialsItem.Cloudflare
    | CreateAssistantDtoCredentialsItem.CustomLlm
    | CreateAssistantDtoCredentialsItem.Deepgram
    | CreateAssistantDtoCredentialsItem.Deepinfra
    | CreateAssistantDtoCredentialsItem.DeepSeek
    | CreateAssistantDtoCredentialsItem.Gcp
    | CreateAssistantDtoCredentialsItem.Gladia
    | CreateAssistantDtoCredentialsItem.Gohighlevel
    | CreateAssistantDtoCredentialsItem.Google
    | CreateAssistantDtoCredentialsItem.Groq
    | CreateAssistantDtoCredentialsItem.InflectionAi
    | CreateAssistantDtoCredentialsItem.Langfuse
    | CreateAssistantDtoCredentialsItem.Lmnt
    | CreateAssistantDtoCredentialsItem.Make
    | CreateAssistantDtoCredentialsItem.Openai
    | CreateAssistantDtoCredentialsItem.Openrouter
    | CreateAssistantDtoCredentialsItem.PerplexityAi
    | CreateAssistantDtoCredentialsItem.Playht
    | CreateAssistantDtoCredentialsItem.RimeAi
    | CreateAssistantDtoCredentialsItem.Runpod
    | CreateAssistantDtoCredentialsItem.S3
    | CreateAssistantDtoCredentialsItem.Supabase
    | CreateAssistantDtoCredentialsItem.SmallestAi
    | CreateAssistantDtoCredentialsItem.Tavus
    | CreateAssistantDtoCredentialsItem.TogetherAi
    | CreateAssistantDtoCredentialsItem.Twilio
    | CreateAssistantDtoCredentialsItem.Vonage
    | CreateAssistantDtoCredentialsItem.Webhook
    | CreateAssistantDtoCredentialsItem.CustomCredential
    | CreateAssistantDtoCredentialsItem.Xai
    | CreateAssistantDtoCredentialsItem.Neuphonic
    | CreateAssistantDtoCredentialsItem.Hume
    | CreateAssistantDtoCredentialsItem.Mistral
    | CreateAssistantDtoCredentialsItem.Speechmatics
    | CreateAssistantDtoCredentialsItem.Soniox
    | CreateAssistantDtoCredentialsItem.Trieve
    | CreateAssistantDtoCredentialsItem.GoogleCalendarOauth2Client
    | CreateAssistantDtoCredentialsItem.GoogleCalendarOauth2Authorization
    | CreateAssistantDtoCredentialsItem.GoogleSheetsOauth2Authorization
    | CreateAssistantDtoCredentialsItem.SlackOauth2Authorization
    | CreateAssistantDtoCredentialsItem.GhlOauth2Authorization
    | CreateAssistantDtoCredentialsItem.Inworld
    | CreateAssistantDtoCredentialsItem.Minimax
    | CreateAssistantDtoCredentialsItem.Wellsaid
    | CreateAssistantDtoCredentialsItem.Email
    | CreateAssistantDtoCredentialsItem.SlackWebhook;

export namespace CreateAssistantDtoCredentialsItem {
    export interface _11Labs extends CreateElevenLabsCredentialDto {
        provider: "11labs";
    }

    export interface Anthropic extends CreateAnthropicCredentialDto {
        provider: "anthropic";
    }

    export interface AnthropicBedrock extends CreateAnthropicBedrockCredentialDto {
        provider: "anthropic-bedrock";
    }

    export interface Anyscale extends CreateAnyscaleCredentialDto {
        provider: "anyscale";
    }

    export interface AssemblyAi extends CreateAssemblyAiCredentialDto {
        provider: "assembly-ai";
    }

    export interface AzureOpenai extends CreateAzureOpenAiCredentialDto {
        provider: "azure-openai";
    }

    export interface Azure extends CreateAzureCredentialDto {
        provider: "azure";
    }

    export interface ByoSipTrunk extends CreateByoSipTrunkCredentialDto {
        provider: "byo-sip-trunk";
    }

    export interface Cartesia extends CreateCartesiaCredentialDto {
        provider: "cartesia";
    }

    export interface Cerebras extends CreateCerebrasCredentialDto {
        provider: "cerebras";
    }

    export interface Cloudflare extends CreateCloudflareCredentialDto {
        provider: "cloudflare";
    }

    export interface CustomLlm extends CreateCustomLlmCredentialDto {
        provider: "custom-llm";
    }

    export interface Deepgram extends CreateDeepgramCredentialDto {
        provider: "deepgram";
    }

    export interface Deepinfra extends CreateDeepInfraCredentialDto {
        provider: "deepinfra";
    }

    export interface DeepSeek extends CreateDeepSeekCredentialDto {
        provider: "deep-seek";
    }

    export interface Gcp extends CreateGcpCredentialDto {
        provider: "gcp";
    }

    export interface Gladia extends CreateGladiaCredentialDto {
        provider: "gladia";
    }

    export interface Gohighlevel extends CreateGoHighLevelCredentialDto {
        provider: "gohighlevel";
    }

    export interface Google extends CreateGoogleCredentialDto {
        provider: "google";
    }

    export interface Groq extends CreateGroqCredentialDto {
        provider: "groq";
    }

    export interface InflectionAi extends CreateInflectionAiCredentialDto {
        provider: "inflection-ai";
    }

    export interface Langfuse extends CreateLangfuseCredentialDto {
        provider: "langfuse";
    }

    export interface Lmnt extends CreateLmntCredentialDto {
        provider: "lmnt";
    }

    export interface Make extends CreateMakeCredentialDto {
        provider: "make";
    }

    export interface Openai extends CreateOpenAiCredentialDto {
        provider: "openai";
    }

    export interface Openrouter extends CreateOpenRouterCredentialDto {
        provider: "openrouter";
    }

    export interface PerplexityAi extends CreatePerplexityAiCredentialDto {
        provider: "perplexity-ai";
    }

    export interface Playht extends CreatePlayHtCredentialDto {
        provider: "playht";
    }

    export interface RimeAi extends CreateRimeAiCredentialDto {
        provider: "rime-ai";
    }

    export interface Runpod extends CreateRunpodCredentialDto {
        provider: "runpod";
    }

    export interface S3 extends CreateS3CredentialDto {
        provider: "s3";
    }

    export interface Supabase extends CreateSupabaseCredentialDto {
        provider: "supabase";
    }

    export interface SmallestAi extends CreateSmallestAiCredentialDto {
        provider: "smallest-ai";
    }

    export interface Tavus extends CreateTavusCredentialDto {
        provider: "tavus";
    }

    export interface TogetherAi extends CreateTogetherAiCredentialDto {
        provider: "together-ai";
    }

    export interface Twilio extends CreateTwilioCredentialDto {
        provider: "twilio";
    }

    export interface Vonage extends CreateVonageCredentialDto {
        provider: "vonage";
    }

    export interface Webhook extends CreateWebhookCredentialDto {
        provider: "webhook";
    }

    export interface CustomCredential extends CreateCustomCredentialDto {
        provider: "custom-credential";
    }

    export interface Xai extends CreateXAiCredentialDto {
        provider: "xai";
    }

    export interface Neuphonic extends CreateNeuphonicCredentialDto {
        provider: "neuphonic";
    }

    export interface Hume extends CreateHumeCredentialDto {
        provider: "hume";
    }

    export interface Mistral extends CreateMistralCredentialDto {
        provider: "mistral";
    }

    export interface Speechmatics extends CreateSpeechmaticsCredentialDto {
        provider: "speechmatics";
    }

    export interface Soniox extends CreateSonioxCredentialDto {
        provider: "soniox";
    }

    export interface Trieve extends CreateTrieveCredentialDto {
        provider: "trieve";
    }

    export interface GoogleCalendarOauth2Client extends CreateGoogleCalendarOAuth2ClientCredentialDto {
        provider: "google.calendar.oauth2-client";
    }

    export interface GoogleCalendarOauth2Authorization
        extends CreateGoogleCalendarOAuth2AuthorizationCredentialDto {
        provider: "google.calendar.oauth2-authorization";
    }

    export interface GoogleSheetsOauth2Authorization extends CreateGoogleSheetsOAuth2AuthorizationCredentialDto {
        provider: "google.sheets.oauth2-authorization";
    }

    export interface SlackOauth2Authorization extends CreateSlackOAuth2AuthorizationCredentialDto {
        provider: "slack.oauth2-authorization";
    }

    export interface GhlOauth2Authorization extends CreateGoHighLevelMcpCredentialDto {
        provider: "ghl.oauth2-authorization";
    }

    export interface Inworld extends CreateInworldCredentialDto {
        provider: "inworld";
    }

    export interface Minimax extends CreateMinimaxCredentialDto {
        provider: "minimax";
    }

    export interface Wellsaid extends CreateWellSaidCredentialDto {
        provider: "wellsaid";
    }

    export interface Email extends CreateEmailCredentialDto {
        provider: "email";
    }

    export interface SlackWebhook extends CreateSlackWebhookCredentialDto {
        provider: "slack-webhook";
    }
}
