// This file was auto-generated by Fern from our API Definition.

import type { CreateSimulationRunDtoSimulationsItem } from "./CreateSimulationRunDtoSimulationsItem.js";
import type { CreateSimulationRunDtoTarget } from "./CreateSimulationRunDtoTarget.js";
import type { SimulationRunTransportConfiguration } from "./SimulationRunTransportConfiguration.js";

export interface CreateSimulationRunDto {
    /** Array of simulations and/or suites to run */
    simulations: CreateSimulationRunDtoSimulationsItem[];
    /** Target to test against */
    target: CreateSimulationRunDtoTarget;
    /** Number of times to run each simulation (default: 1) */
    iterations?: number | undefined;
    /** Transport configuration for the simulation runs */
    transport?: SimulationRunTransportConfiguration | undefined;
}
