// This file was auto-generated by Fern from our API Definition.

import type { OAuth2AuthenticationPlan } from "./OAuth2AuthenticationPlan.js";

export interface CreateCustomLlmCredentialDto {
    /** This is not returned in the API. */
    apiKey: string;
    /** This is the authentication plan. Currently supports OAuth2 RFC 6749. To use Bearer authentication, use apiKey */
    authenticationPlan?: OAuth2AuthenticationPlan | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
