// This file was auto-generated by Fern from our API Definition.

/** The type of tool. "output" for Output tool. */
export const CreateOutputToolDtoType = {
    Output: "output",
} as const;
export type CreateOutputToolDtoType = (typeof CreateOutputToolDtoType)[keyof typeof CreateOutputToolDtoType];
