// This file was auto-generated by Fern from our API Definition.

/**
 * Credentials for authenticating voice synthesis requests with PlayHT, including the PlayHT user identifier.
 */
export interface CreatePlayHtCredentialDto {
    /** This is not returned in the API. */
    apiKey: string;
    /** PlayHT user identifier associated with the API key. */
    userId: string;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
