// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type CreateAssistantDraftDtoCredentialsItem =
    | Vapi.CreateAssistantDraftDtoCredentialsItem._11Labs
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Anthropic
    | Vapi.CreateAssistantDraftDtoCredentialsItem.AnthropicBedrock
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Anyscale
    | Vapi.CreateAssistantDraftDtoCredentialsItem.AssemblyAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.AzureOpenai
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Azure
    | Vapi.CreateAssistantDraftDtoCredentialsItem.ByoSipTrunk
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Cartesia
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Cerebras
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Cloudflare
    | Vapi.CreateAssistantDraftDtoCredentialsItem.CustomLlm
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Deepgram
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Deepinfra
    | Vapi.CreateAssistantDraftDtoCredentialsItem.DeepSeek
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Gcp
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Gladia
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Gohighlevel
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Google
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Groq
    | Vapi.CreateAssistantDraftDtoCredentialsItem.InflectionAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Langfuse
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Lmnt
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Make
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Openai
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Openrouter
    | Vapi.CreateAssistantDraftDtoCredentialsItem.PerplexityAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Playht
    | Vapi.CreateAssistantDraftDtoCredentialsItem.RimeAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Runpod
    | Vapi.CreateAssistantDraftDtoCredentialsItem.S3
    | Vapi.CreateAssistantDraftDtoCredentialsItem.S3Compatible
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Supabase
    | Vapi.CreateAssistantDraftDtoCredentialsItem.SmallestAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Tavus
    | Vapi.CreateAssistantDraftDtoCredentialsItem.TogetherAi
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Twilio
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Vonage
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Webhook
    | Vapi.CreateAssistantDraftDtoCredentialsItem.CustomCredential
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Xai
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Microsoft
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Neuphonic
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Hume
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Mistral
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Speechmatics
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Soniox
    | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleCalendarOauth2Client
    | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleCalendarOauth2Authorization
    | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleSheetsOauth2Authorization
    | Vapi.CreateAssistantDraftDtoCredentialsItem.SlackOauth2Authorization
    | Vapi.CreateAssistantDraftDtoCredentialsItem.GhlOauth2Authorization
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Inworld
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Minimax
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Wellsaid
    | Vapi.CreateAssistantDraftDtoCredentialsItem.Email
    | Vapi.CreateAssistantDraftDtoCredentialsItem.SlackWebhook;

export namespace CreateAssistantDraftDtoCredentialsItem {
    export interface _11Labs extends Vapi.CreateElevenLabsCredentialDto {
        provider: "11labs";
    }

    export interface Anthropic extends Vapi.CreateAnthropicCredentialDto {
        provider: "anthropic";
    }

    export interface AnthropicBedrock extends Vapi.CreateAnthropicBedrockCredentialDto {
        provider: "anthropic-bedrock";
    }

    export interface Anyscale extends Vapi.CreateAnyscaleCredentialDto {
        provider: "anyscale";
    }

    export interface AssemblyAi extends Vapi.CreateAssemblyAiCredentialDto {
        provider: "assembly-ai";
    }

    export interface AzureOpenai extends Vapi.CreateAzureOpenAiCredentialDto {
        provider: "azure-openai";
    }

    export interface Azure extends Vapi.CreateAzureCredentialDto {
        provider: "azure";
    }

    export interface ByoSipTrunk extends Vapi.CreateByoSipTrunkCredentialDto {
        provider: "byo-sip-trunk";
    }

    export interface Cartesia extends Vapi.CreateCartesiaCredentialDto {
        provider: "cartesia";
    }

    export interface Cerebras extends Vapi.CreateCerebrasCredentialDto {
        provider: "cerebras";
    }

    export interface Cloudflare extends Vapi.CreateCloudflareCredentialDto {
        provider: "cloudflare";
    }

    export interface CustomLlm extends Vapi.CreateCustomLlmCredentialDto {
        provider: "custom-llm";
    }

    export interface Deepgram extends Vapi.CreateDeepgramCredentialDto {
        provider: "deepgram";
    }

    export interface Deepinfra extends Vapi.CreateDeepInfraCredentialDto {
        provider: "deepinfra";
    }

    export interface DeepSeek extends Vapi.CreateDeepSeekCredentialDto {
        provider: "deep-seek";
    }

    export interface Gcp extends Vapi.CreateGcpCredentialDto {
        provider: "gcp";
    }

    export interface Gladia extends Vapi.CreateGladiaCredentialDto {
        provider: "gladia";
    }

    export interface Gohighlevel extends Vapi.CreateGoHighLevelCredentialDto {
        provider: "gohighlevel";
    }

    export interface Google extends Vapi.CreateGoogleCredentialDto {
        provider: "google";
    }

    export interface Groq extends Vapi.CreateGroqCredentialDto {
        provider: "groq";
    }

    export interface InflectionAi extends Vapi.CreateInflectionAiCredentialDto {
        provider: "inflection-ai";
    }

    export interface Langfuse extends Vapi.CreateLangfuseCredentialDto {
        provider: "langfuse";
    }

    export interface Lmnt extends Vapi.CreateLmntCredentialDto {
        provider: "lmnt";
    }

    export interface Make extends Vapi.CreateMakeCredentialDto {
        provider: "make";
    }

    export interface Openai extends Vapi.CreateOpenAiCredentialDto {
        provider: "openai";
    }

    export interface Openrouter extends Vapi.CreateOpenRouterCredentialDto {
        provider: "openrouter";
    }

    export interface PerplexityAi extends Vapi.CreatePerplexityAiCredentialDto {
        provider: "perplexity-ai";
    }

    export interface Playht extends Vapi.CreatePlayHtCredentialDto {
        provider: "playht";
    }

    export interface RimeAi extends Vapi.CreateRimeAiCredentialDto {
        provider: "rime-ai";
    }

    export interface Runpod extends Vapi.CreateRunpodCredentialDto {
        provider: "runpod";
    }

    export interface S3 extends Vapi.CreateS3CredentialDto {
        provider: "s3";
    }

    export interface S3Compatible extends Vapi.CreateS3CompatibleCredentialDto {
        provider: "s3-compatible";
    }

    export interface Supabase extends Vapi.CreateSupabaseCredentialDto {
        provider: "supabase";
    }

    export interface SmallestAi extends Vapi.CreateSmallestAiCredentialDto {
        provider: "smallest-ai";
    }

    export interface Tavus extends Vapi.CreateTavusCredentialDto {
        provider: "tavus";
    }

    export interface TogetherAi extends Vapi.CreateTogetherAiCredentialDto {
        provider: "together-ai";
    }

    export interface Twilio extends Vapi.CreateTwilioCredentialDto {
        provider: "twilio";
    }

    export interface Vonage extends Vapi.CreateVonageCredentialDto {
        provider: "vonage";
    }

    export interface Webhook extends Vapi.CreateWebhookCredentialDto {
        provider: "webhook";
    }

    export interface CustomCredential extends Vapi.CreateCustomCredentialDto {
        provider: "custom-credential";
    }

    export interface Xai extends Vapi.CreateXAiCredentialDto {
        provider: "xai";
    }

    export interface Microsoft extends Vapi.CreateMicrosoftCredentialDto {
        provider: "microsoft";
    }

    export interface Neuphonic extends Vapi.CreateNeuphonicCredentialDto {
        provider: "neuphonic";
    }

    export interface Hume extends Vapi.CreateHumeCredentialDto {
        provider: "hume";
    }

    export interface Mistral extends Vapi.CreateMistralCredentialDto {
        provider: "mistral";
    }

    export interface Speechmatics extends Vapi.CreateSpeechmaticsCredentialDto {
        provider: "speechmatics";
    }

    export interface Soniox extends Vapi.CreateSonioxCredentialDto {
        provider: "soniox";
    }

    export interface GoogleCalendarOauth2Client extends Vapi.CreateGoogleCalendarOAuth2ClientCredentialDto {
        provider: "google.calendar.oauth2-client";
    }

    export interface GoogleCalendarOauth2Authorization
        extends Vapi.CreateGoogleCalendarOAuth2AuthorizationCredentialDto {
        provider: "google.calendar.oauth2-authorization";
    }

    export interface GoogleSheetsOauth2Authorization extends Vapi.CreateGoogleSheetsOAuth2AuthorizationCredentialDto {
        provider: "google.sheets.oauth2-authorization";
    }

    export interface SlackOauth2Authorization extends Vapi.CreateSlackOAuth2AuthorizationCredentialDto {
        provider: "slack.oauth2-authorization";
    }

    export interface GhlOauth2Authorization extends Vapi.CreateGoHighLevelMcpCredentialDto {
        provider: "ghl.oauth2-authorization";
    }

    export interface Inworld extends Vapi.CreateInworldCredentialDto {
        provider: "inworld";
    }

    export interface Minimax extends Vapi.CreateMinimaxCredentialDto {
        provider: "minimax";
    }

    export interface Wellsaid extends Vapi.CreateWellSaidCredentialDto {
        provider: "wellsaid";
    }

    export interface Email extends Vapi.CreateEmailCredentialDto {
        provider: "email";
    }

    export interface SlackWebhook extends Vapi.CreateSlackWebhookCredentialDto {
        provider: "slack-webhook";
    }

    export type Response =
        | Vapi.CreateAssistantDraftDtoCredentialsItem._11Labs
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Anthropic
        | Vapi.CreateAssistantDraftDtoCredentialsItem.AnthropicBedrock
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Anyscale
        | Vapi.CreateAssistantDraftDtoCredentialsItem.AssemblyAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.AzureOpenai
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Azure
        | Vapi.CreateAssistantDraftDtoCredentialsItem.ByoSipTrunk
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Cartesia
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Cerebras
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Cloudflare
        | Vapi.CreateAssistantDraftDtoCredentialsItem.CustomLlm
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Deepgram
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Deepinfra
        | Vapi.CreateAssistantDraftDtoCredentialsItem.DeepSeek
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Gcp
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Gladia
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Gohighlevel
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Google
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Groq
        | Vapi.CreateAssistantDraftDtoCredentialsItem.InflectionAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Langfuse
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Lmnt
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Make
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Openai
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Openrouter
        | Vapi.CreateAssistantDraftDtoCredentialsItem.PerplexityAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Playht
        | Vapi.CreateAssistantDraftDtoCredentialsItem.RimeAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Runpod
        | Vapi.CreateAssistantDraftDtoCredentialsItem.S3
        | Vapi.CreateAssistantDraftDtoCredentialsItem.S3Compatible
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Supabase
        | Vapi.CreateAssistantDraftDtoCredentialsItem.SmallestAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Tavus
        | Vapi.CreateAssistantDraftDtoCredentialsItem.TogetherAi
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Twilio
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Vonage
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Webhook
        | Vapi.CreateAssistantDraftDtoCredentialsItem.CustomCredential
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Xai
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Microsoft
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Neuphonic
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Hume
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Mistral
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Speechmatics
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Soniox
        | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleCalendarOauth2Client
        | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleCalendarOauth2Authorization
        | Vapi.CreateAssistantDraftDtoCredentialsItem.GoogleSheetsOauth2Authorization
        | Vapi.CreateAssistantDraftDtoCredentialsItem.SlackOauth2Authorization
        | Vapi.CreateAssistantDraftDtoCredentialsItem.GhlOauth2Authorization
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Inworld
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Minimax
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Wellsaid
        | Vapi.CreateAssistantDraftDtoCredentialsItem.Email
        | Vapi.CreateAssistantDraftDtoCredentialsItem.SlackWebhook;
}
