// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface CreateScenarioDto {
    /** The display name of the scenario, for example `Book an appointment`. */
    name: string;
    /** What the AI tester should try to accomplish in the conversation. Write it as the AI tester's goal, for example `Book an appointment for next week and confirm the time.` */
    instructions: string;
    /** The checks that decide whether a run passes. Each evaluation compares a structured output against an expected value. At least one evaluation is required to run. */
    evaluations: Vapi.EvaluationPlanItem[];
    /** Hooks to run on simulation lifecycle events */
    hooks?: Vapi.CreateScenarioDtoHooksItem[] | undefined;
    /** Overrides to inject into the simulated target assistant or squad */
    targetOverrides?: Vapi.AssistantOverrides | undefined;
    /** Mock results for the assistant or squad's tools during the simulation, so the run stays deterministic without calling real services. */
    toolMocks?: Vapi.ScenarioToolMock[] | undefined;
    /**
     * Optional folder path for organizing scenarios.
     * Supports up to 3 levels (e.g., "dept/feature/variant").
     * Maps to GitOps resource folder structure.
     */
    path?: (string | null) | undefined;
}
