// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type CreateStructuredOutputDtoConditionsItem =
    | Vapi.CreateStructuredOutputDtoConditionsItem.MinMessages
    | Vapi.CreateStructuredOutputDtoConditionsItem.MinCallDuration
    | Vapi.CreateStructuredOutputDtoConditionsItem.EndedReason;

export namespace CreateStructuredOutputDtoConditionsItem {
    export interface MinMessages extends Vapi.MinMessagesCondition {
        type: "minMessages";
    }

    export interface MinCallDuration extends Vapi.MinCallDurationCondition {
        type: "minCallDuration";
    }

    export interface EndedReason extends Vapi.EndedReasonCondition {
        type: "endedReason";
    }
}
