// This file was auto-generated by Fern from our API Definition.

import type { WorkflowAnthropicBedrockModel } from "./WorkflowAnthropicBedrockModel.js";
import type { WorkflowAnthropicModel } from "./WorkflowAnthropicModel.js";
import type { WorkflowCustomModel } from "./WorkflowCustomModel.js";
import type { WorkflowGoogleModel } from "./WorkflowGoogleModel.js";
import type { WorkflowOpenAiModel } from "./WorkflowOpenAiModel.js";

/**
 * This is the model for the workflow.
 *
 * This can be overridden at node level using `nodes[n].model`.
 */
export type CreateWorkflowDtoModel =
    | CreateWorkflowDtoModel.Openai
    | CreateWorkflowDtoModel.Anthropic
    | CreateWorkflowDtoModel.AnthropicBedrock
    | CreateWorkflowDtoModel.Google
    | CreateWorkflowDtoModel.CustomLlm;

export namespace CreateWorkflowDtoModel {
    export interface Openai extends WorkflowOpenAiModel {
        provider: "openai";
    }

    export interface Anthropic extends WorkflowAnthropicModel {
        provider: "anthropic";
    }

    export interface AnthropicBedrock extends WorkflowAnthropicBedrockModel {
        provider: "anthropic-bedrock";
    }

    export interface Google extends WorkflowGoogleModel {
        provider: "google";
    }

    export interface CustomLlm extends WorkflowCustomModel {
        provider: "custom-llm";
    }
}
