// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type CreateSimulationRunDtoSimulationsItem =
    | Vapi.CreateSimulationRunDtoSimulationsItem.Simulation
    | Vapi.CreateSimulationRunDtoSimulationsItem.SimulationSuite;

export namespace CreateSimulationRunDtoSimulationsItem {
    export interface Simulation extends Vapi.SimulationRunSimulationEntry {
        type: "simulation";
    }

    export interface SimulationSuite extends Vapi.SimulationRunSuiteEntry {
        type: "simulationSuite";
    }
}
