// This file was auto-generated by Fern from our API Definition.

/**
 * Credentials for authenticating assistant model requests with Perplexity AI.
 */
export interface CreatePerplexityAiCredentialDto {
    /** This is not returned in the API. */
    apiKey: string;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
