// This file was auto-generated by Fern from our API Definition.

import type { CredentialEndUser } from "./CredentialEndUser.js";
import type { CredentialSessionError } from "./CredentialSessionError.js";
import type { CredentialWebhookDtoAuthMode } from "./CredentialWebhookDtoAuthMode.js";
import type { CredentialWebhookDtoOperation } from "./CredentialWebhookDtoOperation.js";
import type { CredentialWebhookDtoType } from "./CredentialWebhookDtoType.js";

export interface CredentialWebhookDto {
    type: CredentialWebhookDtoType;
    operation: CredentialWebhookDtoOperation;
    from: string;
    connectionId: string;
    authMode: CredentialWebhookDtoAuthMode;
    providerConfigKey: string;
    provider: string;
    environment: string;
    success: boolean;
    endUser: CredentialEndUser;
    error?: CredentialSessionError | undefined;
    tags?: Record<string, unknown> | undefined;
}
