// This file was auto-generated by Fern from our API Definition.

export const CredentialWebhookDtoOperation = {
    Creation: "creation",
    Override: "override",
    Refresh: "refresh",
} as const;
export type CredentialWebhookDtoOperation =
    (typeof CredentialWebhookDtoOperation)[keyof typeof CredentialWebhookDtoOperation];
