// This file was auto-generated by Fern from our API Definition.

import type { CustomMessageType } from "./CustomMessageType.js";
import type { TextContent } from "./TextContent.js";

export interface CustomMessage {
    /**
     * This is an alternative to the `content` property. It allows to specify variants of the same content, one per language.
     *
     * Usage:
     * - If your assistants are multilingual, you can provide content for each language.
     * - If you don't provide content for a language, the first item in the array will be automatically translated to the active language at that moment.
     *
     * This will override the `content` property.
     */
    contents?: TextContent[] | undefined;
    /** This is a custom message. */
    type: CustomMessageType;
    /** This is the content that the assistant will say when this message is triggered. */
    content?: string | undefined;
}
