// This file was auto-generated by Fern from our API Definition.

/** This is the role of the message author */
export const DeveloperMessageRole = {
    Developer: "developer",
} as const;
export type DeveloperMessageRole = (typeof DeveloperMessageRole)[keyof typeof DeveloperMessageRole];
