// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Associates a phone number with the customers to dial through that number in a batch call plan.
 */
export interface DialPlanEntry {
    /** The phone number ID to use for calling the customers in this entry. */
    phoneNumberId: string;
    /** The list of customers to call using this phone number. */
    customers: Vapi.CreateCustomerDto[];
}
