// This file was auto-generated by Fern from our API Definition.

export const ElevenLabsTranscriberModel = {
    ScribeV1: "scribe_v1",
    ScribeV2: "scribe_v2",
    ScribeV2Realtime: "scribe_v2_realtime",
} as const;
export type ElevenLabsTranscriberModel = (typeof ElevenLabsTranscriberModel)[keyof typeof ElevenLabsTranscriberModel];
