// This file was auto-generated by Fern from our API Definition.

/**
 * This is the membership operator applied against `values`.
 *
 * - 'oneOf': the structured output runs only if the call's ended reason is in `values`.
 * - 'notOneOf': the structured output runs only if the call's ended reason is NOT in `values`.
 */
export const EndedReasonConditionOperator = {
    OneOf: "oneOf",
    NotOneOf: "notOneOf",
} as const;
export type EndedReasonConditionOperator =
    (typeof EndedReasonConditionOperator)[keyof typeof EndedReasonConditionOperator];
