// This file was auto-generated by Fern from our API Definition.

import type { ChatEvalAssistantMessageEvaluation } from "./ChatEvalAssistantMessageEvaluation.js";
import type { ChatEvalAssistantMessageMock } from "./ChatEvalAssistantMessageMock.js";
import type { ChatEvalSystemMessageMock } from "./ChatEvalSystemMessageMock.js";
import type { ChatEvalToolResponseMessageEvaluation } from "./ChatEvalToolResponseMessageEvaluation.js";
import type { ChatEvalToolResponseMessageMock } from "./ChatEvalToolResponseMessageMock.js";
import type { ChatEvalUserMessageMock } from "./ChatEvalUserMessageMock.js";

export type EvalMessagesItem =
    | ChatEvalAssistantMessageMock
    | ChatEvalSystemMessageMock
    | ChatEvalToolResponseMessageMock
    | ChatEvalToolResponseMessageEvaluation
    | ChatEvalUserMessageMock
    | ChatEvalAssistantMessageEvaluation;
