// This file was auto-generated by Fern from our API Definition.

import type { EvalRun } from "./EvalRun.js";
import type { PaginationMeta } from "./PaginationMeta.js";

export interface EvalRunPaginatedResponse {
    results: EvalRun[];
    metadata: PaginationMeta;
}
