// This file was auto-generated by Fern from our API Definition.

/** How the structured output value is compared against `value`. Available operators depend on the output type. Boolean and string support `=` and `!=`; number and integer support `=`, `!=`, `>`, `<`, `>=`, `<=`. */
export const EvaluationPlanItemComparator = {
    EqualTo: "=",
    NotEquals: "!=",
    GreaterThan: ">",
    LessThan: "<",
    GreaterThanOrEqualTo: ">=",
    LessThanOrEqualTo: "<=",
} as const;
export type EvaluationPlanItemComparator =
    (typeof EvaluationPlanItemComparator)[keyof typeof EvaluationPlanItemComparator];
