// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface EventsTableBooleanCondition {
    /** The boolean field name from the event data */
    column: string;
    /** Boolean comparison operator */
    operator: Vapi.EventsTableBooleanConditionOperator;
    /** The boolean value to compare */
    value: boolean;
}
