// This file was auto-generated by Fern from our API Definition.

/** Number comparison operator */
export const EventsTableNumberConditionOperator = {
    EqualTo: "=",
    NotEquals: "!=",
    GreaterThan: ">",
    GreaterThanOrEqualTo: ">=",
    LessThan: "<",
    LessThanOrEqualTo: "<=",
} as const;
export type EventsTableNumberConditionOperator =
    (typeof EventsTableNumberConditionOperator)[keyof typeof EventsTableNumberConditionOperator];
