// This file was auto-generated by Fern from our API Definition.

/** Columns to include in the CSV export */
export const ExportChatDtoColumns = {
    Id: "id",
    AssistantId: "assistantId",
    SquadId: "squadId",
    SessionId: "sessionId",
    PreviousChatId: "previousChatId",
    Cost: "cost",
    Messages: "messages",
    Output: "output",
    CreatedAt: "createdAt",
    UpdatedAt: "updatedAt",
} as const;
export type ExportChatDtoColumns = (typeof ExportChatDtoColumns)[keyof typeof ExportChatDtoColumns];
