// This file was auto-generated by Fern from our API Definition.

/**
 * This is the speech model used for the streaming session.
 * Note: Keyterms prompting is not supported with multilingual streaming.
 * @default 'universal-streaming-english'
 */
export const FallbackAssemblyAiTranscriberSpeechModel = {
    UniversalStreamingEnglish: "universal-streaming-english",
    UniversalStreamingMultilingual: "universal-streaming-multilingual",
} as const;
export type FallbackAssemblyAiTranscriberSpeechModel =
    (typeof FallbackAssemblyAiTranscriberSpeechModel)[keyof typeof FallbackAssemblyAiTranscriberSpeechModel];
