// This file was auto-generated by Fern from our API Definition.

/** This is the model that will be used. Defaults to 'aura-2' when not specified. */
export const FallbackDeepgramVoiceModel = {
    Aura: "aura",
    Aura2: "aura-2",
} as const;
export type FallbackDeepgramVoiceModel = (typeof FallbackDeepgramVoiceModel)[keyof typeof FallbackDeepgramVoiceModel];
