// This file was auto-generated by Fern from our API Definition.

/** This is the voice provider that will be used. */
export const FallbackRimeAiVoiceProvider = {
    RimeAi: "rime-ai",
} as const;
export type FallbackRimeAiVoiceProvider =
    (typeof FallbackRimeAiVoiceProvider)[keyof typeof FallbackRimeAiVoiceProvider];
