// This file was auto-generated by Fern from our API Definition.

/** This is the voice provider that will be used. */
export const FallbackLmntVoiceProvider = {
    Lmnt: "lmnt",
} as const;
export type FallbackLmntVoiceProvider = (typeof FallbackLmntVoiceProvider)[keyof typeof FallbackLmntVoiceProvider];
