// This file was auto-generated by Fern from our API Definition.

/** This is the transcription provider that will be used. */
export const FallbackGladiaTranscriberProvider = {
    Gladia: "gladia",
} as const;
export type FallbackGladiaTranscriberProvider =
    (typeof FallbackGladiaTranscriberProvider)[keyof typeof FallbackGladiaTranscriberProvider];
