// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface FallbackMicrosoftVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean | undefined;
    /** MAI-Voice-2 voice ID. Built-in voices listed in enum. */
    voiceId: Vapi.FallbackMicrosoftVoiceVoiceId;
    /** Speaking style applied via mstts:express-as on every request. Unknown styles are ignored by Azure and fall back to neutral. */
    style?: Vapi.FallbackMicrosoftVoiceStyle | undefined;
    /** Style intensity (0.01–2). Default 1 = the predefined style strength. Only applies when `style` is set. */
    styleDegree?: number | undefined;
    /** Role-play (age/gender imitation). Requires `style` to be set; ignored otherwise. */
    role?: Vapi.FallbackMicrosoftVoiceRole | undefined;
    /** This is the speed multiplier that will be used. */
    speed?: number | undefined;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: Vapi.ChunkPlan | undefined;
}
