// This file was auto-generated by Fern from our API Definition.

/** The region for Minimax API. Defaults to "worldwide". */
export const FallbackMinimaxVoiceRegion = {
    Worldwide: "worldwide",
    China: "china",
} as const;
export type FallbackMinimaxVoiceRegion = (typeof FallbackMinimaxVoiceRegion)[keyof typeof FallbackMinimaxVoiceRegion];
