// This file was auto-generated by Fern from our API Definition.

export const FallbackAzureVoiceIdZero = {
    Andrew: "andrew",
    Brian: "brian",
    Emma: "emma",
} as const;
export type FallbackAzureVoiceIdZero = (typeof FallbackAzureVoiceIdZero)[keyof typeof FallbackAzureVoiceIdZero];
