// This file was auto-generated by Fern from our API Definition.

/** This is the voice provider that will be used. */
export const FallbackInworldVoiceProvider = {
    Inworld: "inworld",
} as const;
export type FallbackInworldVoiceProvider =
    (typeof FallbackInworldVoiceProvider)[keyof typeof FallbackInworldVoiceProvider];
