// This file was auto-generated by Fern from our API Definition.

import type { ChunkPlan } from "./ChunkPlan.js";
import type { FallbackAzureVoiceId } from "./FallbackAzureVoiceId.js";

export interface FallbackAzureVoice {
    /** This is the flag to toggle voice caching for the assistant. */
    cachingEnabled?: boolean | undefined;
    /** This is the provider-specific ID that will be used. */
    voiceId: FallbackAzureVoiceId;
    /** This is the speed multiplier that will be used. */
    speed?: number | undefined;
    /** This is the plan for chunking the model output before it is sent to the voice provider. */
    chunkPlan?: ChunkPlan | undefined;
    oneOf?: unknown | undefined;
}
