// This file was auto-generated by Fern from our API Definition.

/** The Soniox model to use for transcription. */
export const FallbackSonioxTranscriberModel = {
    SttRtV4: "stt-rt-v4",
} as const;
export type FallbackSonioxTranscriberModel =
    (typeof FallbackSonioxTranscriberModel)[keyof typeof FallbackSonioxTranscriberModel];
