// This file was auto-generated by Fern from our API Definition.

import type { FallbackAzureSpeechTranscriberLanguage } from "./FallbackAzureSpeechTranscriberLanguage.js";
import type { FallbackAzureSpeechTranscriberSegmentationStrategy } from "./FallbackAzureSpeechTranscriberSegmentationStrategy.js";

export interface FallbackAzureSpeechTranscriber {
    /** This is the language that will be set for the transcription. The list of languages Azure supports can be found here: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=stt */
    language?: FallbackAzureSpeechTranscriberLanguage | undefined;
    /** Controls how phrase boundaries are detected, enabling either simple time/silence heuristics or more advanced semantic segmentation. */
    segmentationStrategy?: FallbackAzureSpeechTranscriberSegmentationStrategy | undefined;
    /** Duration of detected silence after which the service finalizes a phrase. Configure to adjust sensitivity to pauses in speech. */
    segmentationSilenceTimeoutMs?: number | undefined;
    /** Maximum duration a segment can reach before being cut off when using time-based segmentation. */
    segmentationMaximumTimeMs?: number | undefined;
}
