// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface FallbackXaiTranscriber {
    /** The xAI speech-to-text model to use. xAI currently exposes a single STT model — placeholder for future model selection. */
    model?: Vapi.FallbackXaiTranscriberModel | undefined;
    /** Single language for transcription as an ISO 639-1 code (e.g., `en`, `es`). Defaults to `en` if not set. xAI auto-detects when omitted via the API but Vapi defaults to English for deterministic behavior. */
    language?: Vapi.FallbackXaiTranscriberLanguage | undefined;
}
