// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Filters call records by comparing a numeric field with a value.
 */
export interface FilterNumberTypeColumnOnCallTable {
    /**
     * This is the column in the call table that will be filtered on.
     * Number Type columns are columns where the rows store data as a number.
     * Must be a valid column for the selected table.
     */
    column: Vapi.FilterNumberTypeColumnOnCallTableColumn;
    /**
     * This is the operator to use for the filter.
     * For number type columns, the operator must be "=", ">", "<", ">=", "<="
     */
    operator: Vapi.FilterNumberTypeColumnOnCallTableOperator;
    /** This is the value to filter on. */
    value: number;
}
