// This file was auto-generated by Fern from our API Definition.

/**
 * This is the operator to use for the filter.
 * The operator must be `in` or `not_in`.
 */
export const FilterStringArrayTypeColumnOnCallTableOperator = {
    In: "in",
    NotIn: "not_in",
} as const;
export type FilterStringArrayTypeColumnOnCallTableOperator =
    (typeof FilterStringArrayTypeColumnOnCallTableOperator)[keyof typeof FilterStringArrayTypeColumnOnCallTableOperator];
