// This file was auto-generated by Fern from our API Definition.

import type { ExactReplacement } from "./ExactReplacement.js";
import type { RegexReplacement } from "./RegexReplacement.js";

export type FormatPlanReplacementsItem = FormatPlanReplacementsItem.Exact | FormatPlanReplacementsItem.Regex;

export namespace FormatPlanReplacementsItem {
    export interface Exact extends ExactReplacement {
        type: "exact";
    }

    export interface Regex extends RegexReplacement {
        type: "regex";
    }
}
