// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type FunctionToolWithToolCallMessagesItem =
    | Vapi.FunctionToolWithToolCallMessagesItem.RequestStart
    | Vapi.FunctionToolWithToolCallMessagesItem.RequestComplete
    | Vapi.FunctionToolWithToolCallMessagesItem.RequestFailed
    | Vapi.FunctionToolWithToolCallMessagesItem.RequestResponseDelayed;

export namespace FunctionToolWithToolCallMessagesItem {
    export interface RequestStart extends Vapi.ToolMessageStart {
        type: "request-start";
    }

    export interface RequestComplete extends Vapi.ToolMessageComplete {
        type: "request-complete";
    }

    export interface RequestFailed extends Vapi.ToolMessageFailed {
        type: "request-failed";
    }

    export interface RequestResponseDelayed extends Vapi.ToolMessageDelayed {
        type: "request-response-delayed";
    }
}
