// This file was auto-generated by Fern from our API Definition.

import type { GeminiMultimodalLivePrebuiltVoiceConfigVoiceName } from "./GeminiMultimodalLivePrebuiltVoiceConfigVoiceName.js";

export interface GeminiMultimodalLivePrebuiltVoiceConfig {
    voiceName: GeminiMultimodalLivePrebuiltVoiceConfigVoiceName;
}
