// This file was auto-generated by Fern from our API Definition.

import type { GeminiMultimodalLivePrebuiltVoiceConfig } from "./GeminiMultimodalLivePrebuiltVoiceConfig.js";

export interface GeminiMultimodalLiveVoiceConfig {
    prebuiltVoiceConfig: GeminiMultimodalLivePrebuiltVoiceConfig;
}
