// This file was auto-generated by Fern from our API Definition.

import type { GeneratedScenarioCategory } from "./GeneratedScenarioCategory.js";

export interface GeneratedScenario {
    /** Short descriptive name */
    name: string;
    /** Instructions for the tester */
    instructions: string;
    /** Scenario category */
    category: GeneratedScenarioCategory;
    /** Why this scenario is valuable */
    reasoning: string;
}
