// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface GeneratedScenario {
    /** Short descriptive name */
    name: string;
    /** Instructions for the tester */
    instructions: string;
    /** Scenario category */
    category: Vapi.GeneratedScenarioCategory;
    /** Why this scenario is valuable */
    reasoning: string;
}
