// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface GetChatPaginatedDto {
    /** This is the unique identifier for the chat to filter by. */
    id?: string | undefined;
    /** This is the unique identifier for the assistant that will be used for the chat. */
    assistantId?: string | undefined;
    /** Filter by multiple assistant IDs. Provide as comma-separated values. */
    assistantIdAny?: string | undefined;
    /** This is the unique identifier for the squad that will be used for the chat. */
    squadId?: string | undefined;
    /** This is the unique identifier for the session that will be used for the chat. */
    sessionId?: string | undefined;
    /** This is the unique identifier for the previous chat to filter by. */
    previousChatId?: string | undefined;
    /** This is the page number to return. Defaults to 1. */
    page?: number | undefined;
    /** This is the sort order for pagination. Defaults to 'DESC'. */
    sortOrder?: Vapi.GetChatPaginatedDtoSortOrder | undefined;
    /** This is the maximum number of items to return. Defaults to 100. */
    limit?: number | undefined;
    /** This will return items where the createdAt is greater than the specified value. */
    createdAtGt?: string | undefined;
    /** This will return items where the createdAt is less than the specified value. */
    createdAtLt?: string | undefined;
    /** This will return items where the createdAt is greater than or equal to the specified value. */
    createdAtGe?: string | undefined;
    /** This will return items where the createdAt is less than or equal to the specified value. */
    createdAtLe?: string | undefined;
    /** This will return items where the updatedAt is greater than the specified value. */
    updatedAtGt?: string | undefined;
    /** This will return items where the updatedAt is less than the specified value. */
    updatedAtLt?: string | undefined;
    /** This will return items where the updatedAt is greater than or equal to the specified value. */
    updatedAtGe?: string | undefined;
    /** This will return items where the updatedAt is less than or equal to the specified value. */
    updatedAtLe?: string | undefined;
}
