// This file was auto-generated by Fern from our API Definition.

export const GetEvalRunPaginatedDtoSortBy = {
    CreatedAt: "createdAt",
} as const;
export type GetEvalRunPaginatedDtoSortBy =
    (typeof GetEvalRunPaginatedDtoSortBy)[keyof typeof GetEvalRunPaginatedDtoSortBy];
