// This file was auto-generated by Fern from our API Definition.

/** This is the column to sort by. Defaults to 'createdAt'. */
export const GetEvalPaginatedDtoSortBy = {
    CreatedAt: "createdAt",
    Duration: "duration",
    Cost: "cost",
} as const;
export type GetEvalPaginatedDtoSortBy = (typeof GetEvalPaginatedDtoSortBy)[keyof typeof GetEvalPaginatedDtoSortBy];
