/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the sort order for pagination. Defaults to 'DESC'.
 */
export type GetEvalPaginatedDtoSortOrder = "ASC" | "DESC";
export const GetEvalPaginatedDtoSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
