// This file was auto-generated by Fern from our API Definition.

/**
 * GHL workflow and location identifiers attached to a tool.
 */
export interface GhlToolMetadata {
    /** GHL workflow identifier associated with the tool. */
    workflowId?: string | undefined;
    /** GHL location identifier associated with the tool. */
    locationId?: string | undefined;
}
