// This file was auto-generated by Fern from our API Definition.

import type { GladiaVocabularyItemDto } from "./GladiaVocabularyItemDto.js";

export type GladiaCustomVocabularyConfigDtoVocabularyItem = string | GladiaVocabularyItemDto;
