// This file was auto-generated by Fern from our API Definition.

/** The type of tool. "gohighlevel.contact.get" for GoHighLevel Contact Get tool. */
export const GoHighLevelContactGetToolWithToolCallType = {
    GohighlevelContactGet: "gohighlevel.contact.get",
} as const;
export type GoHighLevelContactGetToolWithToolCallType =
    (typeof GoHighLevelContactGetToolWithToolCallType)[keyof typeof GoHighLevelContactGetToolWithToolCallType];
