// This file was auto-generated by Fern from our API Definition.

/** The type of tool. "gohighlevel.contact.create" for GoHighLevel Contact Create tool. */
export const GoHighLevelContactCreateToolWithToolCallType = {
    GohighlevelContactCreate: "gohighlevel.contact.create",
} as const;
export type GoHighLevelContactCreateToolWithToolCallType =
    (typeof GoHighLevelContactCreateToolWithToolCallType)[keyof typeof GoHighLevelContactCreateToolWithToolCallType];
