// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface GoogleSheetsRowAppendToolProviderDetails {
    /** This is the Template URL or the Snapshot URL corresponding to the Template. */
    templateUrl?: string | undefined;
    setupInstructions?: Vapi.ToolTemplateSetup[] | undefined;
}
