// This file was auto-generated by Fern from our API Definition.

export const GroqModelProvider = {
    Groq: "groq",
} as const;
export type GroqModelProvider = (typeof GroqModelProvider)[keyof typeof GroqModelProvider];
