// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Combines nested regular-expression, Liquid, or grouped conditions with an `AND` or `OR` operator.
 */
export interface GroupCondition {
    /** This is the logical operator for combining conditions in this group */
    operator: Vapi.GroupConditionOperator;
    /**
     * This is the list of nested conditions to evaluate.
     * Supports recursive nesting of groups for complex logic.
     */
    conditions: Vapi.GroupConditionConditionsItem[];
}
