// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type HandoffToolMessagesItem =
    | Vapi.HandoffToolMessagesItem.RequestStart
    | Vapi.HandoffToolMessagesItem.RequestComplete
    | Vapi.HandoffToolMessagesItem.RequestFailed
    | Vapi.HandoffToolMessagesItem.RequestResponseDelayed;

export namespace HandoffToolMessagesItem {
    export interface RequestStart extends Vapi.ToolMessageStart {
        type: "request-start";
    }

    export interface RequestComplete extends Vapi.ToolMessageComplete {
        type: "request-complete";
    }

    export interface RequestFailed extends Vapi.ToolMessageFailed {
        type: "request-failed";
    }

    export interface RequestResponseDelayed extends Vapi.ToolMessageDelayed {
        type: "request-response-delayed";
    }
}
