// This file was auto-generated by Fern from our API Definition.

export const HandoffDestinationAssistantType = {
    Assistant: "assistant",
} as const;
export type HandoffDestinationAssistantType =
    (typeof HandoffDestinationAssistantType)[keyof typeof HandoffDestinationAssistantType];
