// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface HandoffDestinationDynamic {
    /**
     * This is where Vapi will send the handoff-destination-request webhook in a dynamic handoff.
     *
     * The order of precedence is:
     *
     * 1. tool.server.url
     * 2. assistant.server.url
     * 3. phoneNumber.server.url
     * 4. org.server.url
     */
    server?: Vapi.Server | undefined;
    /** This is the description of the destination, used by the AI to choose when and how to transfer the call. */
    description?: string | undefined;
}
