/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Vapi from "../index.js";

/**
 * This is the plan for manipulating the message context before handing off the call to the next assistant.
 */
export type HandoffDestinationAssistantContextEngineeringPlan =
    | Vapi.ContextEngineeringPlanLastNMessages
    | Vapi.ContextEngineeringPlanNone
    | Vapi.ContextEngineeringPlanAll;
