// This file was auto-generated by Fern from our API Definition.

export const HangupNodeType = {
    Hangup: "hangup",
} as const;
export type HangupNodeType = (typeof HangupNodeType)[keyof typeof HangupNodeType];
