// This file was auto-generated by Fern from our API Definition.

export const HumeCredentialProvider = {
    Hume: "hume",
} as const;
export type HumeCredentialProvider = (typeof HumeCredentialProvider)[keyof typeof HumeCredentialProvider];
