// This file was auto-generated by Fern from our API Definition.

export const InviteUserDtoRole = {
    Admin: "admin",
    Editor: "editor",
    Viewer: "viewer",
} as const;
export type InviteUserDtoRole = (typeof InviteUserDtoRole)[keyof typeof InviteUserDtoRole];
