// This file was auto-generated by Fern from our API Definition.

export const InworldCredentialProvider = {
    Inworld: "inworld",
} as const;
export type InworldCredentialProvider = (typeof InworldCredentialProvider)[keyof typeof InworldCredentialProvider];
