// This file was auto-generated by Fern from our API Definition.

/**
 * This is the aggregation operation to perform on the column.
 * When the column is a string type, the operation must be "count".
 */
export const JsonQueryOnCallTableWithStringTypeColumnOperation = {
    Count: "count",
} as const;
export type JsonQueryOnCallTableWithStringTypeColumnOperation =
    (typeof JsonQueryOnCallTableWithStringTypeColumnOperation)[keyof typeof JsonQueryOnCallTableWithStringTypeColumnOperation];
