// This file was auto-generated by Fern from our API Definition.

import type { JsonQueryOnCallTableWithStringTypeColumnColumn } from "./JsonQueryOnCallTableWithStringTypeColumnColumn.js";
import type { JsonQueryOnCallTableWithStringTypeColumnFiltersItem } from "./JsonQueryOnCallTableWithStringTypeColumnFiltersItem.js";
import type { JsonQueryOnCallTableWithStringTypeColumnOperation } from "./JsonQueryOnCallTableWithStringTypeColumnOperation.js";
import type { JsonQueryOnCallTableWithStringTypeColumnTable } from "./JsonQueryOnCallTableWithStringTypeColumnTable.js";
import type { JsonQueryOnCallTableWithStringTypeColumnType } from "./JsonQueryOnCallTableWithStringTypeColumnType.js";

export interface JsonQueryOnCallTableWithStringTypeColumn {
    /** This is the type of query. Only allowed type is "vapiql-json". */
    type: JsonQueryOnCallTableWithStringTypeColumnType;
    /** This is the table that will be queried. */
    table: JsonQueryOnCallTableWithStringTypeColumnTable;
    /**
     * This is the filters to apply to the insight.
     * The discriminator automatically selects the correct filter type based on column and operator.
     */
    filters?: JsonQueryOnCallTableWithStringTypeColumnFiltersItem[] | undefined;
    /**
     * This is the column that will be queried in the selected table.
     * Available columns depend on the selected table.
     * String Type columns are columns where the rows store String data
     */
    column: JsonQueryOnCallTableWithStringTypeColumnColumn;
    /**
     * This is the aggregation operation to perform on the column.
     * When the column is a string type, the operation must be "count".
     */
    operation: JsonQueryOnCallTableWithStringTypeColumnOperation;
    /**
     * This is the name of the query.
     * It will be used to label the query in the insight board on the UI.
     */
    name?: string | undefined;
}
