// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface KnowledgeBaseV2WithFiles {
    name: string;
    description?: (string | null) | undefined;
    id: string;
    orgId: string;
    createdAt: string;
    updatedAt: string;
    files: Vapi.KnowledgeBaseV2File[];
    /** Id of the tool that searches this knowledge base (at most one per base; provisioned on creation). Attach it to an assistant via model.toolIds. Null when the base has no search tool yet. */
    toolId: string | null;
}
