// This file was auto-generated by Fern from our API Definition.

export const KnowledgeBaseV2FileStatus = {
    Indexing: "indexing",
    Ready: "ready",
    Failed: "failed",
} as const;
export type KnowledgeBaseV2FileStatus = (typeof KnowledgeBaseV2FileStatus)[keyof typeof KnowledgeBaseV2FileStatus];
