// This file was auto-generated by Fern from our API Definition.

export const LangfuseObservabilityPlanProvider = {
    Langfuse: "langfuse",
} as const;
export type LangfuseObservabilityPlanProvider =
    (typeof LangfuseObservabilityPlanProvider)[keyof typeof LangfuseObservabilityPlanProvider];
