// This file was auto-generated by Fern from our API Definition.

/** This is how the per-turn latencies were aggregated. */
export const LatencyEvaluationResultAggregation = {
    Mean: "mean",
    Median: "median",
    P95: "p95",
    Max: "max",
} as const;
export type LatencyEvaluationResultAggregation =
    (typeof LatencyEvaluationResultAggregation)[keyof typeof LatencyEvaluationResultAggregation];
