// This file was auto-generated by Fern from our API Definition.

/**
 * This is the type of the Insight.
 * It is required to be `line` to create a line insight.
 */
export const LineInsightFromCallTableType = {
    Line: "line",
} as const;
export type LineInsightFromCallTableType =
    (typeof LineInsightFromCallTableType)[keyof typeof LineInsightFromCallTableType];
