// This file was auto-generated by Fern from our API Definition.

/** This is the type discriminator for liquid condition */
export const LiquidConditionType = {
    Liquid: "liquid",
} as const;
export type LiquidConditionType = (typeof LiquidConditionType)[keyof typeof LiquidConditionType];
