// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface McpToolMessages {
    /** The name of the tool from the MCP server. */
    name: string;
    /** Custom messages for this specific tool. Set to an empty array to suppress all messages for this tool. If not provided, the tool will use the default messages from the parent MCP tool configuration. */
    messages?: Vapi.McpToolMessagesMessagesItem[] | undefined;
}
