// This file was auto-generated by Fern from our API Definition.

/** This is the name of the model. Ex. cognitivecomputations/dolphin-mixtral-8x7b */
export const MinimaxLlmModelModel = {
    MiniMaxM27: "MiniMax-M2.7",
} as const;
export type MinimaxLlmModelModel = (typeof MinimaxLlmModelModel)[keyof typeof MinimaxLlmModelModel];
