// This file was auto-generated by Fern from our API Definition.

/** This is the voice provider that will be used. */
export const MinimaxVoiceProvider = {
    Minimax: "minimax",
} as const;
export type MinimaxVoiceProvider = (typeof MinimaxVoiceProvider)[keyof typeof MinimaxVoiceProvider];
