/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The region for Minimax API. Defaults to "worldwide".
 */
export type MinimaxVoiceRegion = "worldwide" | "china";
export const MinimaxVoiceRegion = {
    Worldwide: "worldwide",
    China: "china",
} as const;
