// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type NodeArtifactMessagesItem =
    | Vapi.UserMessage
    | Vapi.SystemMessage
    | Vapi.BotMessage
    | Vapi.ToolCallMessage
    | Vapi.ToolCallResultMessage;
