// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface NumberComparatorScorecardMetricCondition {
    /** This is the type of the condition. Currently only 'comparator' is supported. */
    type: Vapi.NumberComparatorScorecardMetricConditionType;
    /**
     * This is the comparator that will be used to compare the result of the structured output with the value specified.
     * Only '=', '!=', '>', '<', '>=', and '<=' are supported for number conditions
     * Only '=' is supported for boolean conditions.
     */
    comparator: Vapi.NumberComparatorScorecardMetricConditionComparator;
    /**
     * This is the value that will be used to compare the result of the structured output with the comparator.
     * If the result of the comparison is true, the points will be added to the overall score.
     */
    value: number;
    /**
     * These are the points that will be added to the overall score if the condition is met.
     * The points must be between 0 and 100.
     */
    points: number;
}
