// This file was auto-generated by Fern from our API Definition.

export const OpenAiVoiceIdEnum = {
    Alloy: "alloy",
    Echo: "echo",
    Fable: "fable",
    Onyx: "onyx",
    Nova: "nova",
    Shimmer: "shimmer",
    Marin: "marin",
    Cedar: "cedar",
} as const;
export type OpenAiVoiceIdEnum = (typeof OpenAiVoiceIdEnum)[keyof typeof OpenAiVoiceIdEnum];
