// This file was auto-generated by Fern from our API Definition.

export const OpenAiSpeakerPersonalityPacksItem = {
    EagerListener: "eager-listener",
    IdleHummer: "idle-hummer",
    Bouncy: "bouncy",
    Unhurried: "unhurried",
} as const;
export type OpenAiSpeakerPersonalityPacksItem =
    (typeof OpenAiSpeakerPersonalityPacksItem)[keyof typeof OpenAiSpeakerPersonalityPacksItem];
