// This file was auto-generated by Fern from our API Definition.

export const OpenRouterModelProvider = {
    Openrouter: "openrouter",
} as const;
export type OpenRouterModelProvider = (typeof OpenRouterModelProvider)[keyof typeof OpenRouterModelProvider];
