// This file was auto-generated by Fern from our API Definition.

export interface OrgApiLimitsDto {
    /** Approximate number of API requests counted against the rate limit in the current minute, in the region that served this request. The count lives in a tumbling one-minute window aligned to the UTC clock (unix seconds / 60), so it resets to zero at the top of every minute; there is no reset header — the next boundary is (floor(now / 60) + 1) * 60. */
    rateLimitUsage: number;
    /** Maximum number of standard API requests allowed per minute, in the region that served this request. Live call media traffic is limited separately and is not reflected here. */
    rateLimitMax: number;
}
