// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface OrgLimitsResponseDto {
    /** Call concurrency limits for the subscription. Unlike the call create response, remainingConcurrentCalls does not reserve a slot for a new call: it is the plain headroom at the time of the read. Covers the concurrency gate only — credits, frozen subscriptions, included minutes, and the billing limit are not reflected here, so call create can still refuse. Omitted when the limits could not be computed, and for an org with no subscription at all (legacy ungated orgs), which has no concurrency ceiling. */
    subscriptionLimits?: Vapi.OrgConcurrencyLimitsDto | undefined;
    /** API rate limit usage for the org. Approximate, per region, and scoped to the current minute. Omitted when the limit information is unavailable. */
    apiLimits?: Vapi.OrgApiLimitsDto | undefined;
}
