// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Pagination and retention metadata returned with a paginated list of phone numbers.
 */
export interface PaginationMeta {
    /** The number of phone numbers returned per page. */
    itemsPerPage: number;
    /** The total number of phone numbers matching the request. */
    totalItems: number;
    /** The current page number. */
    currentPage: number;
    totalPages?: number | undefined;
    hasNextPage?: boolean | undefined;
    /**
     * Opaque cursor for the next page under keyset pagination (PRO-3163). Pass it
     * back as the `cursor` query param to fetch the next page without an OFFSET
     * scan. Present only when a further page likely exists.
     */
    nextCursor?: string | undefined;
    sortOrder?: Vapi.PaginationMetaSortOrder | undefined;
    /** Whether additional matching phone numbers exist beyond the organization's data-retention window. */
    itemsBeyondRetention?: boolean | undefined;
    /** The inclusive upper creation-time boundary applied to the result set. */
    createdAtLe?: string | undefined;
    /** The inclusive lower creation-time boundary applied to the result set. */
    createdAtGe?: string | undefined;
}
