// This file was auto-generated by Fern from our API Definition.

export const PaginationMetaSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type PaginationMetaSortOrder = (typeof PaginationMetaSortOrder)[keyof typeof PaginationMetaSortOrder];
