// This file was auto-generated by Fern from our API Definition.

import type { PhoneNumberCallEndingHookFilterKey } from "./PhoneNumberCallEndingHookFilterKey.js";
import type { PhoneNumberCallEndingHookFilterOneOfItem } from "./PhoneNumberCallEndingHookFilterOneOfItem.js";
import type { PhoneNumberCallEndingHookFilterType } from "./PhoneNumberCallEndingHookFilterType.js";

export interface PhoneNumberCallEndingHookFilter {
    /** This is the type of filter - currently only "oneOf" is supported */
    type: PhoneNumberCallEndingHookFilterType;
    /** This is the key to filter on - only "call.endedReason" is allowed for phone number call ending hooks */
    key: PhoneNumberCallEndingHookFilterKey;
    /** This is the array of assistant-request related ended reasons to match against */
    oneOf: PhoneNumberCallEndingHookFilterOneOfItem[];
}
