// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * A paginated collection of phone numbers and metadata describing the result set.
 */
export interface PhoneNumberPaginatedResponse {
    /** A list of phone numbers, which can be of any provider type. */
    results: Vapi.PhoneNumberPaginatedResponseResultsItem[];
    /** Metadata about the pagination. */
    metadata: Vapi.PaginationMeta;
}
