// This file was auto-generated by Fern from our API Definition.

/** This is the event to trigger the hook on */
export const PhoneNumberHookCallEndingOn = {
    CallEnding: "call.ending",
} as const;
export type PhoneNumberHookCallEndingOn =
    (typeof PhoneNumberHookCallEndingOn)[keyof typeof PhoneNumberHookCallEndingOn];
