// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface PhoneNumberHookCallRinging {
    /** Optional filters to decide when to trigger the hook. Currently supports filtering by caller country code. */
    filters?: Vapi.PhoneNumberCallRingingHookFilter[] | undefined;
    /** Only the first action will be executed. Additional actions will be ignored. */
    do: Vapi.PhoneNumberHookCallRingingDoItem[];
}
