// This file was auto-generated by Fern from our API Definition.

/** The encryption algorithm to use. */
export const PublicKeyEncryptionPlanAlgorithm = {
    RsaOaep256: "RSA-OAEP-256",
} as const;
export type PublicKeyEncryptionPlanAlgorithm =
    (typeof PublicKeyEncryptionPlanAlgorithm)[keyof typeof PublicKeyEncryptionPlanAlgorithm];
