// This file was auto-generated by Fern from our API Definition.

import type { SpkiPemPublicKeyConfig } from "./SpkiPemPublicKeyConfig.js";

/**
 * The public key configuration.
 */
export type PublicKeyEncryptionPlanPublicKey = PublicKeyEncryptionPlanPublicKey.SpkiPem;

export namespace PublicKeyEncryptionPlanPublicKey {
    export interface SpkiPem extends SpkiPemPublicKeyConfig {
        format: "spki-pem";
    }
}
