// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * The public key configuration.
 */
export type PublicKeyEncryptionPlanPublicKey = Vapi.PublicKeyEncryptionPlanPublicKey.SpkiPem;

export namespace PublicKeyEncryptionPlanPublicKey {
    export interface SpkiPem extends Vapi.SpkiPemPublicKeyConfig {
        format: "spki-pem";
    }
}
