// This file was auto-generated by Fern from our API Definition.

import type { RceSecurityFilterType } from "./RceSecurityFilterType.js";

export interface RceSecurityFilter {
    /** The type of security threat to filter. */
    type: RceSecurityFilterType;
}
