/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RecordingConsent {
    /** This is the type of recording consent. */
    type: Record<string, unknown>;
    /**
     * This is the date and time the recording consent was granted.
     * If not specified, it means the recording consent was not granted.
     */
    grantedAt?: string;
}
