// This file was auto-generated by Fern from our API Definition.

import type { RelayCommandNote } from "./RelayCommandNote.js";
import type { RelayCommandSay } from "./RelayCommandSay.js";

export type RelayRequestCommandsItem = RelayRequestCommandsItem.Say | RelayRequestCommandsItem.MessageAdd;

export namespace RelayRequestCommandsItem {
    export interface Say extends RelayCommandSay {
        type: "say";
    }

    export interface MessageAdd extends RelayCommandNote {
        type: "message.add";
    }
}
