// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface RelayResponse {
    /** The status of the relay request */
    status: Vapi.RelayResponseStatus;
    /** The unique identifier of the call, if delivered to a live call */
    callId?: string | undefined;
    /** The unique identifier of the session, if delivered to a headless session */
    sessionId?: string | undefined;
    chatId?: string | undefined;
}
