// This file was auto-generated by Fern from our API Definition.

import type { RelayCommandOptionsType } from "./RelayCommandOptionsType.js";

export interface RelayCommandOptions {
    type: RelayCommandOptionsType;
}
