// This file was auto-generated by Fern from our API Definition.

/** The type of the output text */
export const ResponseOutputTextType = {
    OutputText: "output_text",
} as const;
export type ResponseOutputTextType = (typeof ResponseOutputTextType)[keyof typeof ResponseOutputTextType];
