// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface ResponseCompletedEvent {
    /** The completed response */
    response: Vapi.ResponseObject;
    /** Event type */
    type: Vapi.ResponseCompletedEventType;
}
