// This file was auto-generated by Fern from our API Definition.

import type { ResponseOutputMessageRole } from "./ResponseOutputMessageRole.js";
import type { ResponseOutputMessageStatus } from "./ResponseOutputMessageStatus.js";
import type { ResponseOutputMessageType } from "./ResponseOutputMessageType.js";
import type { ResponseOutputText } from "./ResponseOutputText.js";

export interface ResponseOutputMessage {
    /** The unique ID of the output message */
    id: string;
    /** Content of the output message */
    content: ResponseOutputText[];
    /** The role of the output message */
    role: ResponseOutputMessageRole;
    /** The status of the message */
    status: ResponseOutputMessageStatus;
    /** The type of the output message */
    type: ResponseOutputMessageType;
}
