// This file was auto-generated by Fern from our API Definition.

/** Event type */
export const ResponseCompletedEventType = {
    ResponseCompleted: "response.completed",
} as const;
export type ResponseCompletedEventType = (typeof ResponseCompletedEventType)[keyof typeof ResponseCompletedEventType];
