// This file was auto-generated by Fern from our API Definition.

/** Language for speech synthesis. Uses ISO 639 codes. Supported: en, es, de, fr, ar, hi, ja, he, pt, ta, si. */
export const RimeAiVoiceLanguage = {
    En: "en",
    Es: "es",
    De: "de",
    Fr: "fr",
    Ar: "ar",
    Hi: "hi",
    Ja: "ja",
    He: "he",
    Pt: "pt",
    Ta: "ta",
    Si: "si",
} as const;
export type RimeAiVoiceLanguage = (typeof RimeAiVoiceLanguage)[keyof typeof RimeAiVoiceLanguage];
