/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This is the model that will be used. Defaults to 'arcana' when not specified.
 */
export type RimeAiVoiceModel = "arcana" | "mistv2" | "mist";
export const RimeAiVoiceModel = {
    Arcana: "arcana",
    Mistv2: "mistv2",
    Mist: "mist",
} as const;
