// This file was auto-generated by Fern from our API Definition.

/** This is for S3-compatible storage such as MinIO, Garage, Ceph, or Backblaze B2. */
export const S3CompatibleStorageCredentialProvider = {
    S3Compatible: "s3-compatible",
} as const;
export type S3CompatibleStorageCredentialProvider =
    (typeof S3CompatibleStorageCredentialProvider)[keyof typeof S3CompatibleStorageCredentialProvider];
