// This file was auto-generated by Fern from our API Definition.

/**
 * A phone-number hook action that speaks an exact message to the caller.
 */
export interface SayPhoneNumberHookAction {
    /** This is the message to say */
    exact: string;
}
