// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type ScenarioHooksItem = Vapi.ScenarioHooksItem.SimulationRunStarted | Vapi.ScenarioHooksItem.SimulationRunEnded;

export namespace ScenarioHooksItem {
    export interface SimulationRunStarted extends Vapi.SimulationHookCallStarted {
        on: "simulation.run.started";
    }

    export interface SimulationRunEnded extends Vapi.SimulationHookCallEnded {
        on: "simulation.run.ended";
    }
}
