// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface ServerMessageKnowledgeBaseRequest {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: Vapi.ServerMessageKnowledgeBaseRequestPhoneNumber | undefined;
    /** This is the type of the message. "knowledge-base-request" is sent to request knowledge base documents. To enable, use `assistant.knowledgeBase.provider=custom-knowledge-base`. */
    type: Vapi.ServerMessageKnowledgeBaseRequestType;
    /** These are the messages that are going to be sent to the `model` right after the `knowledge-base-request` webhook completes. */
    messages?: Vapi.ServerMessageKnowledgeBaseRequestMessagesItem[] | undefined;
    /** This is just `messages` formatted for OpenAI. */
    messagesOpenAIFormatted: Vapi.OpenAiMessage[];
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /**
     * This is a live version of the `call.artifact`.
     *
     * This matches what is stored on `call.artifact` after the call.
     */
    artifact?: Vapi.Artifact | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: Vapi.CreateAssistantDto | undefined;
    /** This is the customer that the message is associated with. */
    customer?: Vapi.CreateCustomerDto | undefined;
    /** This is the call that the message is associated with. */
    call?: Vapi.Call | undefined;
    /** This is the chat object. */
    chat?: Vapi.Chat | undefined;
}
