// This file was auto-generated by Fern from our API Definition.

/** This is the type of the message. "assistant-speech" is sent as assistant audio is being played. */
export const ServerMessageAssistantSpeechType = {
    AssistantSpeechStarted: "assistant.speechStarted",
} as const;
export type ServerMessageAssistantSpeechType =
    (typeof ServerMessageAssistantSpeechType)[keyof typeof ServerMessageAssistantSpeechType];
