// This file was auto-generated by Fern from our API Definition.

import type { ToolCallResult } from "./ToolCallResult.js";

export interface ServerMessageResponseToolCalls {
    /** These are the results of the "tool-calls" message. */
    results?: ToolCallResult[] | undefined;
    /** This is the error message if the tool call was not successful. */
    error?: string | undefined;
}
