// This file was auto-generated by Fern from our API Definition.

import type { Artifact } from "./Artifact.js";
import type { Call } from "./Call.js";
import type { Chat } from "./Chat.js";
import type { CreateAssistantDto } from "./CreateAssistantDto.js";
import type { CreateCustomerDto } from "./CreateCustomerDto.js";
import type { ServerMessageSessionDeletedPhoneNumber } from "./ServerMessageSessionDeletedPhoneNumber.js";
import type { ServerMessageSessionDeletedType } from "./ServerMessageSessionDeletedType.js";
import type { Session } from "./Session.js";

export interface ServerMessageSessionDeleted {
    /** This is the phone number that the message is associated with. */
    phoneNumber?: ServerMessageSessionDeletedPhoneNumber | undefined;
    /** This is the type of the message. "session.deleted" is sent when a session is deleted. */
    type: ServerMessageSessionDeletedType;
    /** This is the timestamp of the message. */
    timestamp?: number | undefined;
    /**
     * This is a live version of the `call.artifact`.
     *
     * This matches what is stored on `call.artifact` after the call.
     */
    artifact?: Artifact | undefined;
    /** This is the assistant that the message is associated with. */
    assistant?: CreateAssistantDto | undefined;
    /** This is the customer that the message is associated with. */
    customer?: CreateCustomerDto | undefined;
    /** This is the call that the message is associated with. */
    call?: Call | undefined;
    /** This is the chat object. */
    chat?: Chat | undefined;
    /** This is the session that was deleted. */
    session: Session;
}
