// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * This is the phone number that the message is associated with.
 */
export type ServerMessageAssistantSpeechPhoneNumber =
    | Vapi.ServerMessageAssistantSpeechPhoneNumber.ByoPhoneNumber
    | Vapi.ServerMessageAssistantSpeechPhoneNumber.Twilio
    | Vapi.ServerMessageAssistantSpeechPhoneNumber.Vonage
    | Vapi.ServerMessageAssistantSpeechPhoneNumber.Vapi
    | Vapi.ServerMessageAssistantSpeechPhoneNumber.Telnyx;

export namespace ServerMessageAssistantSpeechPhoneNumber {
    export interface ByoPhoneNumber extends Vapi.CreateByoPhoneNumberDto {
        provider: "byo-phone-number";
    }

    export interface Twilio extends Vapi.CreateTwilioPhoneNumberDto {
        provider: "twilio";
    }

    export interface Vonage extends Vapi.CreateVonagePhoneNumberDto {
        provider: "vonage";
    }

    export interface Vapi extends Vapi.CreateVapiPhoneNumberDto {
        provider: "vapi";
    }

    export interface Telnyx extends Vapi.CreateTelnyxPhoneNumberDto {
        provider: "telnyx";
    }
}
