// This file was auto-generated by Fern from our API Definition.

/**
 * Whether `confidence` came directly from the transcriber ('provider') or
 * was computed by Vapi ('derived').
 *
 * 'derived' means Vapi computed the score from the transcriber's per-word
 * scores; the exact aggregation is provider-specific (an average, a median
 * or a minimum, depending on the transcriber).
 *
 * Absent means no trustworthy score was available for this transcript:
 * either the transcriber does not report one, or the value it reported was
 * invalid and was dropped.
 */
export const ServerMessageTranscriptConfidenceSource = {
    Provider: "provider",
    Derived: "derived",
} as const;
export type ServerMessageTranscriptConfidenceSource =
    (typeof ServerMessageTranscriptConfidenceSource)[keyof typeof ServerMessageTranscriptConfidenceSource];
