// This file was auto-generated by Fern from our API Definition.

/** This is the type of the transcript. */
export const ServerMessageTranscriptTranscriptType = {
    Partial: "partial",
    Final: "final",
} as const;
export type ServerMessageTranscriptTranscriptType =
    (typeof ServerMessageTranscriptTranscriptType)[keyof typeof ServerMessageTranscriptTranscriptType];
