// This file was auto-generated by Fern from our API Definition.

import type { ServerMessageResponseAssistantRequest } from "./ServerMessageResponseAssistantRequest.js";
import type { ServerMessageResponseCallEndpointingRequest } from "./ServerMessageResponseCallEndpointingRequest.js";
import type { ServerMessageResponseHandoffDestinationRequest } from "./ServerMessageResponseHandoffDestinationRequest.js";
import type { ServerMessageResponseKnowledgeBaseRequest } from "./ServerMessageResponseKnowledgeBaseRequest.js";
import type { ServerMessageResponseToolCalls } from "./ServerMessageResponseToolCalls.js";
import type { ServerMessageResponseTransferDestinationRequest } from "./ServerMessageResponseTransferDestinationRequest.js";
import type { ServerMessageResponseVoiceRequest } from "./ServerMessageResponseVoiceRequest.js";

/**
 * This is the response that is expected from the server to the message.
 *
 * Note: Most messages don't expect a response. Only "assistant-request", "tool-calls" and "transfer-destination-request" do.
 */
export type ServerMessageResponseMessageResponse =
    | ServerMessageResponseAssistantRequest
    | ServerMessageResponseHandoffDestinationRequest
    | ServerMessageResponseKnowledgeBaseRequest
    | ServerMessageResponseToolCalls
    | ServerMessageResponseTransferDestinationRequest
    | ServerMessageResponseVoiceRequest
    | ServerMessageResponseCallEndpointingRequest;
