// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * This is the destination to transfer the inbound call to. This will immediately transfer without using any assistants.
 *
 * If this is sent, `assistantId`, `assistant`, `squadId`, and `squad` are ignored.
 */
export type ServerMessageResponseAssistantRequestDestination =
    | Vapi.ServerMessageResponseAssistantRequestDestination.Number
    | Vapi.ServerMessageResponseAssistantRequestDestination.Sip;

export namespace ServerMessageResponseAssistantRequestDestination {
    export interface Number extends Vapi.TransferDestinationNumber {
        type: "number";
    }

    export interface Sip extends Vapi.TransferDestinationSip {
        type: "sip";
    }
}
