// This file was auto-generated by Fern from our API Definition.

import type { TransferDestinationAssistant } from "./TransferDestinationAssistant.js";
import type { TransferDestinationNumber } from "./TransferDestinationNumber.js";
import type { TransferDestinationSip } from "./TransferDestinationSip.js";

/**
 * This is the destination you'd like the call to be transferred to.
 */
export type ServerMessageResponseTransferDestinationRequestDestination =
    | ServerMessageResponseTransferDestinationRequestDestination.Assistant
    | ServerMessageResponseTransferDestinationRequestDestination.Number
    | ServerMessageResponseTransferDestinationRequestDestination.Sip;

export namespace ServerMessageResponseTransferDestinationRequestDestination {
    export interface Assistant extends TransferDestinationAssistant {
        type: "assistant";
    }

    export interface Number extends TransferDestinationNumber {
        type: "number";
    }

    export interface Sip extends TransferDestinationSip {
        type: "sip";
    }
}
