// This file was auto-generated by Fern from our API Definition.

import type { SessionCreatedHookOn } from "./SessionCreatedHookOn.js";
import type { ToolCallHookAction } from "./ToolCallHookAction.js";

export interface SessionCreatedHook {
    /** This is the event that triggers this hook */
    on: SessionCreatedHookOn;
    /** This is the set of actions to perform when the hook triggers. */
    do: ToolCallHookAction[];
    /**
     * Optional name for this hook instance.
     * If no name is provided, the hook will be auto generated as UUID.
     *
     * @default UUID
     */
    name?: string | undefined;
}
