// This file was auto-generated by Fern from our API Definition.

import type { CreatePersonalityDto } from "./CreatePersonalityDto.js";
import type { CreateScenarioDto } from "./CreateScenarioDto.js";

export interface SimulationRunSimulationEntry {
    /** ID of an existing simulation to run. When provided, scenarioId/personalityId/inline fields are ignored. */
    simulationId?: string | undefined;
    /** ID of an existing scenario. Cannot be combined with inline scenario. */
    scenarioId?: string | undefined;
    /** Inline scenario configuration. Cannot be combined with scenarioId. */
    scenario?: CreateScenarioDto | undefined;
    /** ID of an existing personality. Cannot be combined with inline personality. */
    personalityId?: string | undefined;
    /** Inline personality configuration. Cannot be combined with personalityId. */
    personality?: CreatePersonalityDto | undefined;
    /** Optional name for this simulation entry */
    name?: string | undefined;
}
