// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface SimulationRun {
    /** Unique identifier for the run */
    id: string;
    /** Organization ID */
    orgId: string;
    /** Current status of the run */
    status: Vapi.SimulationRunStatus;
    /** When the run was queued */
    queuedAt: string;
    /** When the run started */
    startedAt?: string | undefined;
    /** When the run ended */
    endedAt?: string | undefined;
    /** Reason the run ended */
    endedReason?: string | undefined;
    /** ISO 8601 date-time when created */
    createdAt: string;
    /** ISO 8601 date-time when last updated */
    updatedAt: string;
    /** Aggregate counts of run items by status */
    itemCounts?: Vapi.SimulationRunItemCounts | undefined;
    /** Array of simulations and/or suites to run */
    simulations: Vapi.SimulationRunSimulationsItem[];
    /** Target to test against */
    target: Vapi.SimulationRunTarget;
    /** Number of times to run each simulation (default: 1) */
    iterations?: number | undefined;
    /** Transport configuration for the simulation runs */
    transport?: Vapi.SimulationRunTransportConfiguration | undefined;
}
