// This file was auto-generated by Fern from our API Definition.

export const SimulationHookWebhookActionType = {
    Webhook: "webhook",
} as const;
export type SimulationHookWebhookActionType =
    (typeof SimulationHookWebhookActionType)[keyof typeof SimulationHookWebhookActionType];
