// This file was auto-generated by Fern from our API Definition.

/** Current status of the run */
export const SimulationRunListItemStatus = {
    Queued: "queued",
    Running: "running",
    Ended: "ended",
} as const;
export type SimulationRunListItemStatus =
    (typeof SimulationRunListItemStatus)[keyof typeof SimulationRunListItemStatus];
