// This file was auto-generated by Fern from our API Definition.

export interface SimulationRunSuiteEntry {
    /** ID of the simulation suite to run */
    simulationSuiteId?: string | undefined;
    /** Historical suite name captured when the run was created */
    name?: string | undefined;
    suiteId?: string | undefined;
}
