// This file was auto-generated by Fern from our API Definition.

export interface SipTrunkOutboundSipRegisterPlan {
    domain?: string | undefined;
    username?: string | undefined;
    realm?: string | undefined;
}
