/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * This controls how numbers are formatted in the transcription output.
 *
 * @default 'written'
 */
export type SpeechmaticsTranscriberNumeralStyle = "written" | "spoken";
export const SpeechmaticsTranscriberNumeralStyle = {
    Written: "written",
    Spoken: "spoken",
} as const;
