// This file was auto-generated by Fern from our API Definition.

export const SpeechmaticsCredentialProvider = {
    Speechmatics: "speechmatics",
} as const;
export type SpeechmaticsCredentialProvider =
    (typeof SpeechmaticsCredentialProvider)[keyof typeof SpeechmaticsCredentialProvider];
