// This file was auto-generated by Fern from our API Definition.

/**
 * An SPKI public key in PEM format used to encrypt sensitive request data.
 */
export interface SpkiPemPublicKeyConfig {
    /** Optional name of the key for identification purposes. */
    name?: string | undefined;
    /** The PEM-encoded public key. */
    pem: string;
}
