// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * A saved squad configuration that coordinates a group of assistants during a conversation. The first member starts the call, and member destinations control transfers between assistants.
 */
export interface Squad {
    /**
     * This is the latest version label (e.g. `v3`) of the squad in the version
     * history. `null` while the org is not yet onboarded to versioning, or for
     * squads that have not yet been published under it.
     */
    latestVersion?: (string | null) | undefined;
    /** Read-only. Present only when a model this configuration uses is deprecated or retired in Vapi's model deprecation registry, judged on the day of the response. Each entry names the slot that carries the model (for example `model` or `model.fallbackModels[1]`), the deprecation and retirement dates as `YYYY-MM-DD` in UTC, and the recommended replacement model: the registry's replacement, followed through any further retirements as of the response date, so it names a model that is alive on that day. Ignored if sent back in a create or update request. */
    modelDeprecations?: Vapi.ModelDeprecationNotice[] | undefined;
    /** This is the name of the squad. */
    name?: string | undefined;
    /**
     * This is the list of assistants that make up the squad.
     *
     * The call will start with the first assistant in the list.
     */
    members: Vapi.SquadMemberDto[];
    /**
     * This can be used to override all the assistants' settings and provide values for their template variables.
     *
     * Both `membersOverrides` and `members[n].assistantOverrides` can be used together. First, `members[n].assistantOverrides` is applied. Then, `membersOverrides` is applied as a global override.
     */
    membersOverrides?: Vapi.AssistantOverrides | undefined;
    /** This is the unique identifier for the squad. */
    id: string;
    /** This is the unique identifier for the org that this squad belongs to. */
    orgId: string;
    /** This is the ISO 8601 date-time string of when the squad was created. */
    createdAt: string;
    /** This is the ISO 8601 date-time string of when the squad was last updated. */
    updatedAt: string;
}
