// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface SsrfSecurityFilter {
    /** The type of security threat to filter. */
    type: Vapi.SsrfSecurityFilterType;
}
