// This file was auto-generated by Fern from our API Definition.

/**
 * This is the expected value that was defined in the evaluation plan.
 */
export type StructuredOutputEvaluationResultExpectedValue = number | string | boolean;
