// This file was auto-generated by Fern from our API Definition.

/** This is the comparison operator used for evaluation. */
export const StructuredOutputEvaluationResultComparator = {
    EqualTo: "=",
    NotEquals: "!=",
    GreaterThan: ">",
    LessThan: "<",
    GreaterThanOrEqualTo: ">=",
    LessThanOrEqualTo: "<=",
} as const;
export type StructuredOutputEvaluationResultComparator =
    (typeof StructuredOutputEvaluationResultComparator)[keyof typeof StructuredOutputEvaluationResultComparator];
