// This file was auto-generated by Fern from our API Definition.

import type { StructuredDataPlan } from "./StructuredDataPlan.js";

export interface StructuredDataMultiPlan {
    /** This is the key of the structured data plan in the catalog. */
    key: string;
    /** This is an individual structured data plan in the catalog. */
    plan: StructuredDataPlan;
}
