// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type StructuredOutputConditionsItem =
    | Vapi.StructuredOutputConditionsItem.MinMessages
    | Vapi.StructuredOutputConditionsItem.MinCallDuration
    | Vapi.StructuredOutputConditionsItem.EndedReason;

export namespace StructuredOutputConditionsItem {
    export interface MinMessages extends Vapi.MinMessagesCondition {
        type: "minMessages";
    }

    export interface MinCallDuration extends Vapi.MinCallDurationCondition {
        type: "minCallDuration";
    }

    export interface EndedReason extends Vapi.EndedReasonCondition {
        type: "endedReason";
    }
}
