// This file was auto-generated by Fern from our API Definition.

import type { TavusVoiceVoiceIdZero } from "./TavusVoiceVoiceIdZero.js";

/**
 * This is the provider-specific ID that will be used.
 */
export type TavusVoiceVoiceId = TavusVoiceVoiceIdZero | string;
