// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type TelnyxPhoneNumberHooksItem =
    | Vapi.TelnyxPhoneNumberHooksItem.CallRinging
    | Vapi.TelnyxPhoneNumberHooksItem.CallEnding;

export namespace TelnyxPhoneNumberHooksItem {
    export interface CallRinging extends Vapi.PhoneNumberHookCallRinging {
        on: "call.ringing";
    }

    export interface CallEnding extends Vapi.PhoneNumberHookCallEnding {
        on: "call.ending";
    }
}
