// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface TelnyxTransport {
    /** This is the conversation type of the call (ie, voice or chat). */
    conversationType?: Vapi.TelnyxTransportConversationType | undefined;
    /** This is the call control ID of the Telnyx call. */
    callControlId?: string | undefined;
    /** This is the call leg ID of the Telnyx call. */
    callLegId?: string | undefined;
    /** This is the call session ID of the Telnyx call. */
    callSessionId?: string | undefined;
}
