// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type TemplateProviderDetails =
    | Vapi.TemplateProviderDetails.Make
    | Vapi.TemplateProviderDetails.Ghl
    | Vapi.TemplateProviderDetails.Function
    | Vapi.TemplateProviderDetails.GoogleCalendarEventCreate
    | Vapi.TemplateProviderDetails.GoogleSheetsRowAppend
    | Vapi.TemplateProviderDetails.GohighlevelCalendarAvailabilityCheck
    | Vapi.TemplateProviderDetails.GohighlevelCalendarEventCreate
    | Vapi.TemplateProviderDetails.GohighlevelContactCreate
    | Vapi.TemplateProviderDetails.GohighlevelContactGet;

export namespace TemplateProviderDetails {
    export interface Make extends Vapi.MakeToolProviderDetails {
        type: "make";
    }

    export interface Ghl extends Vapi.GhlToolProviderDetails {
        type: "ghl";
    }

    export interface Function extends Vapi.FunctionToolProviderDetails {
        type: "function";
    }

    export interface GoogleCalendarEventCreate extends Vapi.GoogleCalendarCreateEventToolProviderDetails {
        type: "google.calendar.event.create";
    }

    export interface GoogleSheetsRowAppend extends Vapi.GoogleSheetsRowAppendToolProviderDetails {
        type: "google.sheets.row.append";
    }

    export interface GohighlevelCalendarAvailabilityCheck
        extends Vapi.GoHighLevelCalendarAvailabilityToolProviderDetails {
        type: "gohighlevel.calendar.availability.check";
    }

    export interface GohighlevelCalendarEventCreate extends Vapi.GoHighLevelCalendarEventCreateToolProviderDetails {
        type: "gohighlevel.calendar.event.create";
    }

    export interface GohighlevelContactCreate extends Vapi.GoHighLevelContactCreateToolProviderDetails {
        type: "gohighlevel.contact.create";
    }

    export interface GohighlevelContactGet extends Vapi.GoHighLevelContactGetToolProviderDetails {
        type: "gohighlevel.contact.get";
    }
}
