// This file was auto-generated by Fern from our API Definition.

import type { FunctionToolProviderDetails } from "./FunctionToolProviderDetails.js";
import type { GhlToolProviderDetails } from "./GhlToolProviderDetails.js";
import type { GoHighLevelCalendarAvailabilityToolProviderDetails } from "./GoHighLevelCalendarAvailabilityToolProviderDetails.js";
import type { GoHighLevelCalendarEventCreateToolProviderDetails } from "./GoHighLevelCalendarEventCreateToolProviderDetails.js";
import type { GoHighLevelContactCreateToolProviderDetails } from "./GoHighLevelContactCreateToolProviderDetails.js";
import type { GoHighLevelContactGetToolProviderDetails } from "./GoHighLevelContactGetToolProviderDetails.js";
import type { GoogleCalendarCreateEventToolProviderDetails } from "./GoogleCalendarCreateEventToolProviderDetails.js";
import type { GoogleSheetsRowAppendToolProviderDetails } from "./GoogleSheetsRowAppendToolProviderDetails.js";
import type { MakeToolProviderDetails } from "./MakeToolProviderDetails.js";

export type TemplateProviderDetails =
    | TemplateProviderDetails.Make
    | TemplateProviderDetails.Ghl
    | TemplateProviderDetails.Function
    | TemplateProviderDetails.GoogleCalendarEventCreate
    | TemplateProviderDetails.GoogleSheetsRowAppend
    | TemplateProviderDetails.GohighlevelCalendarAvailabilityCheck
    | TemplateProviderDetails.GohighlevelCalendarEventCreate
    | TemplateProviderDetails.GohighlevelContactCreate
    | TemplateProviderDetails.GohighlevelContactGet;

export namespace TemplateProviderDetails {
    export interface Make extends MakeToolProviderDetails {
        type: "make";
    }

    export interface Ghl extends GhlToolProviderDetails {
        type: "ghl";
    }

    export interface Function extends FunctionToolProviderDetails {
        type: "function";
    }

    export interface GoogleCalendarEventCreate extends GoogleCalendarCreateEventToolProviderDetails {
        type: "google.calendar.event.create";
    }

    export interface GoogleSheetsRowAppend extends GoogleSheetsRowAppendToolProviderDetails {
        type: "google.sheets.row.append";
    }

    export interface GohighlevelCalendarAvailabilityCheck
        extends GoHighLevelCalendarAvailabilityToolProviderDetails {
        type: "gohighlevel.calendar.availability.check";
    }

    export interface GohighlevelCalendarEventCreate extends GoHighLevelCalendarEventCreateToolProviderDetails {
        type: "gohighlevel.calendar.event.create";
    }

    export interface GohighlevelContactCreate extends GoHighLevelContactCreateToolProviderDetails {
        type: "gohighlevel.contact.create";
    }

    export interface GohighlevelContactGet extends GoHighLevelContactGetToolProviderDetails {
        type: "gohighlevel.contact.get";
    }
}
