// This file was auto-generated by Fern from our API Definition.

import type { TestSuitePhoneNumberProvider } from "./TestSuitePhoneNumberProvider.js";

export interface TestSuitePhoneNumber {
    /** This is the provider of the phone number. */
    provider: TestSuitePhoneNumberProvider;
    /** This is the phone number that is being tested. */
    number: string;
}
