// This file was auto-generated by Fern from our API Definition.

export const TextContentType = {
    Text: "text",
} as const;
export type TextContentType = (typeof TextContentType)[keyof typeof TextContentType];
