// This file was auto-generated by Fern from our API Definition.

/**
 * The function name and serialized arguments associated with a tool call.
 */
export interface ToolCallFunction {
    /** This is the arguments to call the function with */
    arguments: string;
    /** This is the name of the function to call */
    name: string;
}
