// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface ToolNode {
    /** This is the tool to call. To use an existing tool, send `toolId` instead. */
    tool?: Vapi.ToolNodeTool | undefined;
    /** This is the tool to call. To use a transient tool, send `tool` instead. */
    toolId?: string | undefined;
    name: string;
    /** This is whether or not the node is the start of the workflow. */
    isStart?: boolean | undefined;
    /** This is for metadata you want to store on the task. */
    metadata?: Record<string, unknown> | undefined;
}
