// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface ToolParameter {
    /** This is the key of the parameter. */
    key: string;
    /** The value of the parameter. Any JSON type. String values support Liquid templates. */
    value: Vapi.ToolParameterValue;
}
