// This file was auto-generated by Fern from our API Definition.

export const ToolPinnedConflictResponseDtoError = {
    ToolPinned: "tool_pinned",
} as const;
export type ToolPinnedConflictResponseDtoError =
    (typeof ToolPinnedConflictResponseDtoError)[keyof typeof ToolPinnedConflictResponseDtoError];
