// This file was auto-generated by Fern from our API Definition.

/**
 * The value of the parameter. Any JSON type. String values support Liquid templates.
 */
export type ToolParameterValue = string | number | boolean | Record<string, unknown> | unknown[];
