// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface TrafficAllocationLatestResponseDto {
    /** The source's current configuration: the newest allocation row with its targets. Absent when the source has never been configured. */
    allocation?: Vapi.TrafficAllocation | undefined;
}
