// This file was auto-generated by Fern from our API Definition.

/** 'explicit' splits calls across this allocation's targets. 'follow-latest' sends every call to the newest published version. */
export const TrafficAllocationAllocationIntent = {
    FollowLatest: "follow-latest",
    Explicit: "explicit",
} as const;
export type TrafficAllocationAllocationIntent =
    (typeof TrafficAllocationAllocationIntent)[keyof typeof TrafficAllocationAllocationIntent];
