// This file was auto-generated by Fern from our API Definition.

import type { TransferPhoneNumberHookActionDestination } from "./TransferPhoneNumberHookActionDestination.js";

export interface TransferPhoneNumberHookAction {
    /** This is the destination details for the transfer - can be a phone number or SIP URI */
    destination?: TransferPhoneNumberHookActionDestination | undefined;
}
