// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * Telephony transport cost for a call, including provider, billable minutes, and amount.
 */
export interface TransportCost {
    /** Telephony or transport provider that generated the cost. */
    provider?: Vapi.TransportCostProvider | undefined;
    /** This is the minutes of `transport` usage. This should match `call.endedAt` - `call.startedAt`. */
    minutes: number;
    /** This is the cost of the component in USD. */
    cost: number;
}
