// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface TransferArtifact {
    /** The transfer destination (phone number or SIP URI). */
    destination: Vapi.TransferArtifactDestination;
    /** The transfer mode (e.g. warm-transfer-experimental, blind-transfer). */
    mode?: Vapi.TransferArtifactMode | undefined;
    /** Flat-text transcript / announcement preview of the transfer. */
    transcript?: string | undefined;
    /** The terminal status of the transfer, rendered as the status line. */
    status?: Vapi.TransferArtifactStatus | undefined;
    /**
     * The agent↔operator conversation captured during a
     * warm-transfer-experimental, rendered as bubbles.
     */
    messages?: Vapi.TransferArtifactMessagesItem[] | undefined;
}
