// This file was auto-generated by Fern from our API Definition.

import type { TransferHookActionDestination } from "./TransferHookActionDestination.js";
import type { TransferHookActionType } from "./TransferHookActionType.js";

export interface TransferHookAction {
    /** This is the type of action - must be "transfer" */
    type: TransferHookActionType;
    /** This is the destination details for the transfer - can be a phone number or SIP URI */
    destination?: TransferHookActionDestination | undefined;
}
