// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type TransferCallToolDestinationsItem =
    | Vapi.TransferDestinationAssistant
    | Vapi.TransferDestinationNumber
    | Vapi.TransferDestinationSip;
