// This file was auto-generated by Fern from our API Definition.

export const UpdateWorkflowDtoVoicemailDetectionZero = {
    Off: "off",
} as const;
export type UpdateWorkflowDtoVoicemailDetectionZero =
    (typeof UpdateWorkflowDtoVoicemailDetectionZero)[keyof typeof UpdateWorkflowDtoVoicemailDetectionZero];
