// This file was auto-generated by Fern from our API Definition.

import type { PhoneNumberHookCallEnding } from "./PhoneNumberHookCallEnding.js";
import type { PhoneNumberHookCallRinging } from "./PhoneNumberHookCallRinging.js";

export type UpdateVapiPhoneNumberDtoHooksItem =
    | UpdateVapiPhoneNumberDtoHooksItem.CallRinging
    | UpdateVapiPhoneNumberDtoHooksItem.CallEnding;

export namespace UpdateVapiPhoneNumberDtoHooksItem {
    export interface CallRinging extends PhoneNumberHookCallRinging {
        on: "call.ringing";
    }

    export interface CallEnding extends PhoneNumberHookCallEnding {
        on: "call.ending";
    }
}
