// This file was auto-generated by Fern from our API Definition.

export const UpdateAssistantDraftDtoBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
export type UpdateAssistantDraftDtoBackgroundSoundZero =
    (typeof UpdateAssistantDraftDtoBackgroundSoundZero)[keyof typeof UpdateAssistantDraftDtoBackgroundSoundZero];
