// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface UpdateVonageCredentialDto {
    provider?: Vapi.UpdateVonageCredentialDtoProvider | undefined;
    /** This is not returned in the API. */
    apiSecret?: string | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
    apiKey?: string | undefined;
}
