// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type UpdateVapiPhoneNumberDtoHooksItem =
    | Vapi.UpdateVapiPhoneNumberDtoHooksItem.CallRinging
    | Vapi.UpdateVapiPhoneNumberDtoHooksItem.CallEnding;

export namespace UpdateVapiPhoneNumberDtoHooksItem {
    export interface CallRinging extends Vapi.PhoneNumberHookCallRinging {
        on: "call.ringing";
    }

    export interface CallEnding extends Vapi.PhoneNumberHookCallEnding {
        on: "call.ending";
    }
}
