// This file was auto-generated by Fern from our API Definition.

export const UpdateTogetherAiCredentialDtoProvider = {
    TogetherAi: "together-ai",
} as const;
export type UpdateTogetherAiCredentialDtoProvider =
    (typeof UpdateTogetherAiCredentialDtoProvider)[keyof typeof UpdateTogetherAiCredentialDtoProvider];
