// This file was auto-generated by Fern from our API Definition.

export const UpdateAzureOpenAiCredentialDtoProvider = {
    AzureOpenai: "azure-openai",
} as const;
export type UpdateAzureOpenAiCredentialDtoProvider =
    (typeof UpdateAzureOpenAiCredentialDtoProvider)[keyof typeof UpdateAzureOpenAiCredentialDtoProvider];
