// This file was auto-generated by Fern from our API Definition.

export const UpdateCustomLlmCredentialDtoProvider = {
    CustomLlm: "custom-llm",
} as const;
export type UpdateCustomLlmCredentialDtoProvider =
    (typeof UpdateCustomLlmCredentialDtoProvider)[keyof typeof UpdateCustomLlmCredentialDtoProvider];
