// This file was auto-generated by Fern from our API Definition.

export const UpdateUserRoleDtoRole = {
    Admin: "admin",
    Editor: "editor",
    Viewer: "viewer",
} as const;
export type UpdateUserRoleDtoRole = (typeof UpdateUserRoleDtoRole)[keyof typeof UpdateUserRoleDtoRole];
