// This file was auto-generated by Fern from our API Definition.

/** The type of tool. "code" for Code tool. */
export const UpdateCodeToolDtoType = {
    Code: "code",
} as const;
export type UpdateCodeToolDtoType = (typeof UpdateCodeToolDtoType)[keyof typeof UpdateCodeToolDtoType];
