// This file was auto-generated by Fern from our API Definition.

export const UpdateMakeCredentialDtoProvider = {
    Make: "make",
} as const;
export type UpdateMakeCredentialDtoProvider =
    (typeof UpdateMakeCredentialDtoProvider)[keyof typeof UpdateMakeCredentialDtoProvider];
