// This file was auto-generated by Fern from our API Definition.

export interface UpdateVonageCredentialDto {
    /** This is not returned in the API. */
    apiSecret?: string | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
    apiKey?: string | undefined;
}
