// This file was auto-generated by Fern from our API Definition.

/** This knowledge base is bring your own knowledge base implementation. */
export const UpdateCustomKnowledgeBaseDtoProvider = {
    CustomKnowledgeBase: "custom-knowledge-base",
} as const;
export type UpdateCustomKnowledgeBaseDtoProvider =
    (typeof UpdateCustomKnowledgeBaseDtoProvider)[keyof typeof UpdateCustomKnowledgeBaseDtoProvider];
