// This file was auto-generated by Fern from our API Definition.

export const UpdateOpenAiCredentialDtoProvider = {
    Openai: "openai",
} as const;
export type UpdateOpenAiCredentialDtoProvider =
    (typeof UpdateOpenAiCredentialDtoProvider)[keyof typeof UpdateOpenAiCredentialDtoProvider];
