// This file was auto-generated by Fern from our API Definition.

export const UpdateHumeCredentialDtoProvider = {
    Hume: "hume",
} as const;
export type UpdateHumeCredentialDtoProvider =
    (typeof UpdateHumeCredentialDtoProvider)[keyof typeof UpdateHumeCredentialDtoProvider];
