// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type UpdateGoHighLevelCalendarAvailabilityToolDtoMessagesItem =
    | Vapi.ToolMessageStart
    | Vapi.ToolMessageComplete
    | Vapi.ToolMessageFailed
    | Vapi.ToolMessageDelayed;
