// This file was auto-generated by Fern from our API Definition.

export interface UpdateSimulationSuiteDto {
    /** This is the name of the simulation suite. */
    name?: string | undefined;
    /** This is the Slack webhook URL for notifications. */
    slackWebhookUrl?: string | undefined;
    /** This is the list of simulation IDs to include in the suite (replaces existing). */
    simulationIds?: string[] | undefined;
    /**
     * Optional folder path for organizing simulation suites.
     * Supports up to 3 levels (e.g., "dept/feature/variant").
     * Set to null to remove from folder.
     */
    path?: (string | null) | undefined;
}
