// This file was auto-generated by Fern from our API Definition.

export const UpdateMicrosoftCredentialDtoProvider = {
    Microsoft: "microsoft",
} as const;
export type UpdateMicrosoftCredentialDtoProvider =
    (typeof UpdateMicrosoftCredentialDtoProvider)[keyof typeof UpdateMicrosoftCredentialDtoProvider];
