// This file was auto-generated by Fern from our API Definition.

export const UpdateAssemblyAiCredentialDtoProvider = {
    AssemblyAi: "assembly-ai",
} as const;
export type UpdateAssemblyAiCredentialDtoProvider =
    (typeof UpdateAssemblyAiCredentialDtoProvider)[keyof typeof UpdateAssemblyAiCredentialDtoProvider];
