// This file was auto-generated by Fern from our API Definition.

export interface UpdateSlackWebhookCredentialDto {
    /** Slack incoming webhook URL. See https://api.slack.com/messaging/webhooks for setup instructions. This is not returned in the API. */
    webhookUrl?: string | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
