// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface UpdateEmailCredentialDto {
    provider?: Vapi.UpdateEmailCredentialDtoProvider | undefined;
    /** The recipient email address for alerts */
    email?: string | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
