// This file was auto-generated by Fern from our API Definition.

import type { UpdateWebhookCredentialDtoAuthenticationPlan } from "./UpdateWebhookCredentialDtoAuthenticationPlan.js";

export interface UpdateWebhookCredentialDto {
    /** This is the authentication plan. Supports OAuth2 RFC 6749, HMAC signing, and Bearer authentication. */
    authenticationPlan?: UpdateWebhookCredentialDtoAuthenticationPlan | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
