// This file was auto-generated by Fern from our API Definition.

/** This is the HTTP method for the request (api-request tool). */
export const UpdateToolDraftDtoMethod = {
    Post: "POST",
    Get: "GET",
    Put: "PUT",
    Patch: "PATCH",
    Delete: "DELETE",
} as const;
export type UpdateToolDraftDtoMethod = (typeof UpdateToolDraftDtoMethod)[keyof typeof UpdateToolDraftDtoMethod];
