// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

/**
 * These are the options for the assistant's LLM.
 */
export type UpdateAssistantDraftDtoModel =
    | Vapi.UpdateAssistantDraftDtoModel.Anthropic
    | Vapi.UpdateAssistantDraftDtoModel.AnthropicBedrock
    | Vapi.UpdateAssistantDraftDtoModel.Anyscale
    | Vapi.UpdateAssistantDraftDtoModel.Cerebras
    | Vapi.UpdateAssistantDraftDtoModel.CustomLlm
    | Vapi.UpdateAssistantDraftDtoModel.Deepinfra
    | Vapi.UpdateAssistantDraftDtoModel.DeepSeek
    | Vapi.UpdateAssistantDraftDtoModel.Google
    | Vapi.UpdateAssistantDraftDtoModel.Groq
    | Vapi.UpdateAssistantDraftDtoModel.InflectionAi
    | Vapi.UpdateAssistantDraftDtoModel.Minimax
    | Vapi.UpdateAssistantDraftDtoModel.Openai
    | Vapi.UpdateAssistantDraftDtoModel.Openrouter
    | Vapi.UpdateAssistantDraftDtoModel.PerplexityAi
    | Vapi.UpdateAssistantDraftDtoModel.TogetherAi
    | Vapi.UpdateAssistantDraftDtoModel.Xai
    | Vapi.UpdateAssistantDraftDtoModel.Vapi;

export namespace UpdateAssistantDraftDtoModel {
    export interface Anthropic extends Vapi.AnthropicModel {
        provider: "anthropic";
    }

    export interface AnthropicBedrock extends Vapi.AnthropicBedrockModel {
        provider: "anthropic-bedrock";
    }

    export interface Anyscale extends Vapi.AnyscaleModel {
        provider: "anyscale";
    }

    export interface Cerebras extends Vapi.CerebrasModel {
        provider: "cerebras";
    }

    export interface CustomLlm extends Vapi.CustomLlmModel {
        provider: "custom-llm";
    }

    export interface Deepinfra extends Vapi.DeepInfraModel {
        provider: "deepinfra";
    }

    export interface DeepSeek extends Vapi.DeepSeekModel {
        provider: "deep-seek";
    }

    export interface Google extends Vapi.GoogleModel {
        provider: "google";
    }

    export interface Groq extends Vapi.GroqModel {
        provider: "groq";
    }

    export interface InflectionAi extends Vapi.InflectionAiModel {
        provider: "inflection-ai";
    }

    export interface Minimax extends Vapi.MinimaxLlmModel {
        provider: "minimax";
    }

    export interface Openai extends Vapi.OpenAiModel {
        provider: "openai";
    }

    export interface Openrouter extends Vapi.OpenRouterModel {
        provider: "openrouter";
    }

    export interface PerplexityAi extends Vapi.PerplexityAiModel {
        provider: "perplexity-ai";
    }

    export interface TogetherAi extends Vapi.TogetherAiModel {
        provider: "together-ai";
    }

    export interface Xai extends Vapi.XaiModel {
        provider: "xai";
    }

    export interface Vapi extends Vapi.VapiModel {
        provider: "vapi";
    }

    /**
     * These are the options for the assistant's LLM.
     */
    export type Response =
        | Vapi.UpdateAssistantDraftDtoModel.Anthropic
        | Vapi.UpdateAssistantDraftDtoModel.AnthropicBedrock
        | Vapi.UpdateAssistantDraftDtoModel.Anyscale
        | Vapi.UpdateAssistantDraftDtoModel.Cerebras
        | Vapi.UpdateAssistantDraftDtoModel.CustomLlm
        | Vapi.UpdateAssistantDraftDtoModel.Deepinfra
        | Vapi.UpdateAssistantDraftDtoModel.DeepSeek
        | Vapi.UpdateAssistantDraftDtoModel.Google
        | Vapi.UpdateAssistantDraftDtoModel.Groq
        | Vapi.UpdateAssistantDraftDtoModel.InflectionAi
        | Vapi.UpdateAssistantDraftDtoModel.Minimax
        | Vapi.UpdateAssistantDraftDtoModel.Openai
        | Vapi.UpdateAssistantDraftDtoModel.Openrouter
        | Vapi.UpdateAssistantDraftDtoModel.PerplexityAi
        | Vapi.UpdateAssistantDraftDtoModel.TogetherAi
        | Vapi.UpdateAssistantDraftDtoModel.Xai
        | Vapi.UpdateAssistantDraftDtoModel.Vapi;
}
