// This file was auto-generated by Fern from our API Definition.

export const UpdateGladiaCredentialDtoProvider = {
    Gladia: "gladia",
} as const;
export type UpdateGladiaCredentialDtoProvider =
    (typeof UpdateGladiaCredentialDtoProvider)[keyof typeof UpdateGladiaCredentialDtoProvider];
