// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface UpdateInflectionAiCredentialDto {
    /** This is the api key for Pi in InflectionAI's console. Get it from here: https://developers.inflection.ai/keys, billing will need to be setup */
    provider?: Vapi.UpdateInflectionAiCredentialDtoProvider | undefined;
    /** This is not returned in the API. */
    apiKey?: string | undefined;
    /** This is the name of credential. This is just for your reference. */
    name?: string | undefined;
}
