// This file was auto-generated by Fern from our API Definition.

export interface VapiPronunciationDictionaryLocator {
    /** The pronunciation dictionary ID */
    pronunciationDictId: string;
    /** Version ID (only required for ElevenLabs, ignored for Cartesia) */
    versionId?: string | undefined;
}
