// This file was auto-generated by Fern from our API Definition.

/**
 * Vapi-managed model version (update channel). When set, this is a Vapi-managed
 * LLM routed by the registry; when absent, this is the legacy workflow form
 * below (`steps` / `workflow`).
 */
export const VapiModelVersion = {
    Latest: "latest",
    One: "1",
} as const;
export type VapiModelVersion = (typeof VapiModelVersion)[keyof typeof VapiModelVersion];
