// This file was auto-generated by Fern from our API Definition.

/** This is the conversation type of the call (ie, voice or chat). */
export const VapiWebsocketTransportConversationType = {
    Voice: "voice",
} as const;
export type VapiWebsocketTransportConversationType =
    (typeof VapiWebsocketTransportConversationType)[keyof typeof VapiWebsocketTransportConversationType];
