// This file was auto-generated by Fern from our API Definition.

export interface VapiVoiceCloneDto {
    /** Display name for the cloned voice. */
    name: string;
    /**
     * Optional language (ISO-639 / BCP-47). When omitted, xAI infers it from the
     * reference audio.
     */
    language?: string | undefined;
    /** Reference audio to clone the voice from (up to 120 seconds). Supported formats: MP3, WAV, OGG/Opus, WebM, AAC, M4A, FLAC, WMA. */
    files: string[];
}
