// This file was auto-generated by Fern from our API Definition.

export interface VoiceLibraryVoiceResponse {
    voiceId: string;
    name: string;
    publicOwnerId?: string | undefined;
    description?: string | undefined;
    gender?: string | undefined;
    age?: Record<string, unknown> | undefined;
    accent?: string | undefined;
}
