// This file was auto-generated by Fern from our API Definition.

export const WellSaidCredentialProvider = {
    Wellsaid: "wellsaid",
} as const;
export type WellSaidCredentialProvider = (typeof WellSaidCredentialProvider)[keyof typeof WellSaidCredentialProvider];
