// This file was auto-generated by Fern from our API Definition.

export const WorkflowUserEditableBackgroundSoundZero = {
    Off: "off",
    Office: "office",
} as const;
export type WorkflowUserEditableBackgroundSoundZero =
    (typeof WorkflowUserEditableBackgroundSoundZero)[keyof typeof WorkflowUserEditableBackgroundSoundZero];
