// This file was auto-generated by Fern from our API Definition.

import type { AnthropicThinkingConfig } from "./AnthropicThinkingConfig.js";
import type { WorkflowAnthropicBedrockModelModel } from "./WorkflowAnthropicBedrockModelModel.js";

export interface WorkflowAnthropicBedrockModel {
    /** This is the specific model that will be used. */
    model: WorkflowAnthropicBedrockModelModel;
    /**
     * This is the optional configuration for Anthropic's thinking feature.
     *
     * - If provided, `maxTokens` must be greater than `thinking.budgetTokens`.
     */
    thinking?: AnthropicThinkingConfig | undefined;
    /** This is the temperature of the model. */
    temperature?: number | undefined;
    /** This is the max tokens of the model. */
    maxTokens?: number | undefined;
}
