// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export type WorkflowUserEditableNodesItem =
    | Vapi.WorkflowUserEditableNodesItem.Conversation
    | Vapi.WorkflowUserEditableNodesItem.Tool;

export namespace WorkflowUserEditableNodesItem {
    export interface Conversation extends Vapi.ConversationNode {
        type: "conversation";
    }

    export interface Tool extends Vapi.ToolNode {
        type: "tool";
    }
}
