// This file was auto-generated by Fern from our API Definition.

export const WorkflowUserEditableVoicemailDetectionZero = {
    Off: "off",
} as const;
export type WorkflowUserEditableVoicemailDetectionZero =
    (typeof WorkflowUserEditableVoicemailDetectionZero)[keyof typeof WorkflowUserEditableVoicemailDetectionZero];
