// This file was auto-generated by Fern from our API Definition.

import type { GoogleVoicemailDetectionPlan } from "./GoogleVoicemailDetectionPlan.js";
import type { OpenAiVoicemailDetectionPlan } from "./OpenAiVoicemailDetectionPlan.js";
import type { TwilioVoicemailDetectionPlan } from "./TwilioVoicemailDetectionPlan.js";
import type { VapiVoicemailDetectionPlan } from "./VapiVoicemailDetectionPlan.js";
import type { WorkflowUserEditableVoicemailDetectionZero } from "./WorkflowUserEditableVoicemailDetectionZero.js";

/**
 * This is the voicemail detection plan for the workflow.
 */
export type WorkflowUserEditableVoicemailDetection =
    | WorkflowUserEditableVoicemailDetectionZero
    | GoogleVoicemailDetectionPlan
    | OpenAiVoicemailDetectionPlan
    | TwilioVoicemailDetectionPlan
    | VapiVoicemailDetectionPlan;
