// This file was auto-generated by Fern from our API Definition.

export const XaiModelProvider = {
    Xai: "xai",
} as const;
export type XaiModelProvider = (typeof XaiModelProvider)[keyof typeof XaiModelProvider];
