// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../index.js";

export interface XaiTranscriber {
    /** The xAI speech-to-text model to use. xAI currently exposes a single STT model — placeholder for future model selection. */
    model?: Vapi.XaiTranscriberModel | undefined;
    /** Single language for transcription as an ISO 639-1 code (e.g., `en`, `es`). Defaults to `en` if not set. xAI auto-detects when omitted via the API but Vapi defaults to English for deterministic behavior. */
    language?: Vapi.XaiTranscriberLanguage | undefined;
    /** This is the plan for transcriber provider fallbacks in the event that the primary transcriber provider fails. */
    fallbackPlan?: Vapi.FallbackTranscriberPlan | undefined;
}
