// This file was auto-generated by Fern from our API Definition.

/** The xAI speech-to-text model to use. xAI currently exposes a single STT model — placeholder for future model selection. */
export const XaiTranscriberModel = {
    Default: "default",
} as const;
export type XaiTranscriberModel = (typeof XaiTranscriberModel)[keyof typeof XaiTranscriberModel];
