// This file was auto-generated by Fern from our API Definition.

/** Built-in voices: eve, ara, rex, sal, leo. Cloned voice IDs are also accepted. */
export const XaiVoiceVoiceId = {
    Eve: "eve",
    Ara: "ara",
    Rex: "rex",
    Sal: "sal",
    Leo: "leo",
} as const;
export type XaiVoiceVoiceId = (typeof XaiVoiceVoiceId)[keyof typeof XaiVoiceVoiceId];
