// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdateSimulationSuiteDto {
    /** The unique identifier of the simulation suite. */
    id: string;
    /** This is the name of the simulation suite. */
    name?: string;
    /** This is the Slack webhook URL for notifications. */
    slackWebhookUrl?: string;
    /** This is the list of simulation IDs to include in the suite (replaces existing). */
    simulationIds?: string[];
    /** Optional assistant or squad assignments (replaces existing). */
    targetAssignments?: Vapi.SimulationSuiteTargetAssignment[];
    /**
     * Optional folder path for organizing simulation suites.
     * Supports up to 3 levels (e.g., "dept/feature/variant").
     * Set to null to remove from folder.
     */
    path?: string | null;
}
