// This file was auto-generated by Fern from our API Definition.

export const CallControllerFindAllPaginatedRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type CallControllerFindAllPaginatedRequestSortOrder =
    (typeof CallControllerFindAllPaginatedRequestSortOrder)[keyof typeof CallControllerFindAllPaginatedRequestSortOrder];
