// This file was auto-generated by Fern from our API Definition.

import type { Call } from "../../../types/Call.js";
import type { CallBatchResponse } from "../../../types/CallBatchResponse.js";

export type CreateCallsResponse = Call | CallBatchResponse;
