// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Vapi from "../../../index.js";

export declare namespace TrafficAllocationsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class TrafficAllocationsClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<TrafficAllocationsClient.Options>;

    constructor(options: TrafficAllocationsClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * The append-only history of an assistant's allocations, newest first. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.
     *
     * @param {Vapi.TrafficAllocationControllerFindAllPaginatedRequest} request
     * @param {TrafficAllocationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vapi.ForbiddenError}
     *
     * @example
     *     await client.trafficAllocations.trafficAllocationControllerFindAllPaginated()
     */
    public trafficAllocationControllerFindAllPaginated(
        request: Vapi.TrafficAllocationControllerFindAllPaginatedRequest = {},
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.TrafficAllocationPaginatedResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__trafficAllocationControllerFindAllPaginated(request, requestOptions),
        );
    }

    private async __trafficAllocationControllerFindAllPaginated(
        request: Vapi.TrafficAllocationControllerFindAllPaginatedRequest = {},
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.TrafficAllocationPaginatedResponse>> {
        const { assistantId, page, limit, sortOrder } = request;
        const _queryParams: Record<string, unknown> = {
            assistantId,
            page,
            limit,
            sortOrder: sortOrder != null ? sortOrder : undefined,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "traffic-allocations",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Vapi.TrafficAllocationPaginatedResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Vapi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VapiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/traffic-allocations");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * Creates a new traffic allocation for an assistant, replacing the one currently in effect. To start or adjust a split, send targets naming published versions (such as "v7") with percentages totaling 100; allocationIntent is inferred as 'explicit'. To stop splitting and send every call to the newest published version, send allocationIntent 'follow-latest' with no targets field; stopping always names its intent, so a dropped targets field can never end a split by accident. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.
     *
     * @param {Vapi.CreateTrafficAllocationDto} request
     * @param {TrafficAllocationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vapi.BadRequestError}
     * @throws {@link Vapi.ForbiddenError}
     * @throws {@link Vapi.NotFoundError}
     * @throws {@link Vapi.ConflictError}
     *
     * @example
     *     await client.trafficAllocations.trafficAllocationControllerCreate({
     *         assistantId: "assistantId"
     *     })
     */
    public trafficAllocationControllerCreate(
        request: Vapi.CreateTrafficAllocationDto,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.TrafficAllocation> {
        return core.HttpResponsePromise.fromPromise(this.__trafficAllocationControllerCreate(request, requestOptions));
    }

    private async __trafficAllocationControllerCreate(
        request: Vapi.CreateTrafficAllocationDto,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.TrafficAllocation>> {
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "traffic-allocations",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.TrafficAllocation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vapi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Vapi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Vapi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 409:
                    throw new Vapi.ConflictError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VapiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/traffic-allocations");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * The allocation currently in effect for the assistant, with its targets. The response carries no allocation field when traffic splitting has never been configured. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.
     *
     * @param {Vapi.TrafficAllocationControllerLatestGetRequest} request
     * @param {TrafficAllocationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vapi.BadRequestError}
     * @throws {@link Vapi.ForbiddenError}
     *
     * @example
     *     await client.trafficAllocations.trafficAllocationControllerLatestGet({
     *         assistantId: "assistantId"
     *     })
     */
    public trafficAllocationControllerLatestGet(
        request: Vapi.TrafficAllocationControllerLatestGetRequest,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.TrafficAllocationLatestResponseDto> {
        return core.HttpResponsePromise.fromPromise(
            this.__trafficAllocationControllerLatestGet(request, requestOptions),
        );
    }

    private async __trafficAllocationControllerLatestGet(
        request: Vapi.TrafficAllocationControllerLatestGetRequest,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.TrafficAllocationLatestResponseDto>> {
        const { assistantId } = request;
        const _queryParams: Record<string, unknown> = {
            assistantId,
        };
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                "traffic-allocations/latest",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Vapi.TrafficAllocationLatestResponseDto,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Vapi.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 403:
                    throw new Vapi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VapiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/traffic-allocations/latest");
    }

    /**
     * @beta This endpoint is in pre-release and may change.
     *
     * Returns a single allocation by id, including its targets and actor attribution. Traffic splitting is in beta, rolling out to select organizations; requests from organizations without access receive a 403.
     *
     * @param {Vapi.TrafficAllocationControllerFindOneRequest} request
     * @param {TrafficAllocationsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Vapi.ForbiddenError}
     * @throws {@link Vapi.NotFoundError}
     *
     * @example
     *     await client.trafficAllocations.trafficAllocationControllerFindOne({
     *         id: "id"
     *     })
     */
    public trafficAllocationControllerFindOne(
        request: Vapi.TrafficAllocationControllerFindOneRequest,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): core.HttpResponsePromise<Vapi.TrafficAllocation> {
        return core.HttpResponsePromise.fromPromise(this.__trafficAllocationControllerFindOne(request, requestOptions));
    }

    private async __trafficAllocationControllerFindOne(
        request: Vapi.TrafficAllocationControllerFindOneRequest,
        requestOptions?: TrafficAllocationsClient.RequestOptions,
    ): Promise<core.WithRawResponse<Vapi.TrafficAllocation>> {
        const { id } = request;
        const _authRequest: core.AuthRequest = await this._options.authProvider.getAuthRequest();
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            _authRequest.headers,
            this._options?.headers,
            requestOptions?.headers,
        );
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.VapiEnvironment.Default,
                `traffic-allocations/${core.url.encodePathParam(id)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Vapi.TrafficAllocation, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new Vapi.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new Vapi.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.VapiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/traffic-allocations/{id}");
    }
}
