// This file was auto-generated by Fern from our API Definition.

export const ChatControllerChatsExportRequestFormat = {
    Csv: "csv",
    Json: "json",
} as const;
export type ChatControllerChatsExportRequestFormat =
    (typeof ChatControllerChatsExportRequestFormat)[keyof typeof ChatControllerChatsExportRequestFormat];
