// This file was auto-generated by Fern from our API Definition.

import type { OpenAiResponsesRequestInputOneItem } from "./OpenAiResponsesRequestInputOneItem.js";

/**
 * This is the input text for the chat.
 * Can be a string or an array of chat messages.
 * This field is REQUIRED for chat creation.
 */
export type OpenAiResponsesRequestInput = string | OpenAiResponsesRequestInputOneItem[];
