// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UpdatePersonalityDto {
    /** The unique identifier of the personality. */
    id: string;
    /** This is the name of the personality. */
    name?: string;
    /** This is the full assistant configuration for this personality. */
    assistant?: Vapi.CreateAssistantDto;
    /**
     * Optional folder path for organizing personalities.
     * Supports up to 3 levels (e.g., "dept/feature/variant").
     * Set to null to remove from folder.
     */
    path?: string | null;
}
