// This file was auto-generated by Fern from our API Definition.

import type { CreateBarInsightFromCallTableDto } from "../../../types/CreateBarInsightFromCallTableDto.js";
import type { CreateLineInsightFromCallTableDto } from "../../../types/CreateLineInsightFromCallTableDto.js";
import type { CreatePieInsightFromCallTableDto } from "../../../types/CreatePieInsightFromCallTableDto.js";
import type { CreateTextInsightFromCallTableDto } from "../../../types/CreateTextInsightFromCallTableDto.js";

export type InsightControllerCreateRequest =
    | InsightControllerCreateRequest.Bar
    | InsightControllerCreateRequest.Pie
    | InsightControllerCreateRequest.Line
    | InsightControllerCreateRequest.Text;

export namespace InsightControllerCreateRequest {
    export interface Bar extends CreateBarInsightFromCallTableDto {
        type: "bar";
    }

    export interface Pie extends CreatePieInsightFromCallTableDto {
        type: "pie";
    }

    export interface Line extends CreateLineInsightFromCallTableDto {
        type: "line";
    }

    export interface Text extends CreateTextInsightFromCallTableDto {
        type: "text";
    }
}
