// This file was auto-generated by Fern from our API Definition.

import { VapiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SimulationsClient", () => {
    test("SimulationGenerateController_generate", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            scenarios: [{ name: "name", instructions: "instructions", category: "happy_path", reasoning: "reasoning" }],
            coverageNotes: "coverageNotes",
        };

        server
            .mockEndpoint()
            .post("/eval/simulation/scenario/generate")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationGenerateControllerGenerate();
        expect(response).toEqual({
            scenarios: [
                {
                    name: "name",
                    instructions: "instructions",
                    category: "happy_path",
                    reasoning: "reasoning",
                },
            ],
            coverageNotes: "coverageNotes",
        });
    });

    test("SimulationController_findAll", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                orgId: "orgId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                name: "Eligible Path with Confused User",
                scenarioId: "scenarioId",
                personalityId: "personalityId",
                path: "path",
            },
        ];

        server.mockEndpoint().get("/eval/simulation").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.simulations.simulationControllerFindAll();
        expect(response).toEqual([
            {
                id: "id",
                orgId: "orgId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                name: "Eligible Path with Confused User",
                scenarioId: "scenarioId",
                personalityId: "personalityId",
                path: "path",
            },
        ]);
    });

    test("SimulationController_create", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { scenarioId: "scenarioId", personalityId: "personalityId" };
        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        };

        server
            .mockEndpoint()
            .post("/eval/simulation")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationControllerCreate({
            scenarioId: "scenarioId",
            personalityId: "personalityId",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        });
    });

    test("SimulationController_findOne", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        };

        server
            .mockEndpoint()
            .get("/eval/simulation/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationControllerFindOne({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        });
    });

    test("SimulationController_remove", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        };

        server
            .mockEndpoint()
            .delete("/eval/simulation/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationControllerRemove({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        });
    });

    test("SimulationController_update", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        };

        server
            .mockEndpoint()
            .patch("/eval/simulation/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationControllerUpdate({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Eligible Path with Confused User",
            scenarioId: "scenarioId",
            personalityId: "personalityId",
            path: "path",
        });
    });

    test("SimulationController_getConcurrency", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            orgId: "orgId",
            concurrencyLimit: 1.1,
            activeSimulations: 1.1,
            availableToStart: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            isDefault: true,
        };

        server
            .mockEndpoint()
            .get("/eval/simulation/concurrency")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulations.simulationControllerGetConcurrency();
        expect(response).toEqual({
            orgId: "orgId",
            concurrencyLimit: 1.1,
            activeSimulations: 1.1,
            availableToStart: 1.1,
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            isDefault: true,
        });
    });
});
