// This file was auto-generated by Fern from our API Definition.

import * as Vapi from "../../src/api/index";
import { VapiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SimulationSuitesClient", () => {
    test("SimulationSuiteController_findAll", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                id: "id",
                orgId: "orgId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                name: "Checkout Flow Tests",
                slackWebhookUrl: "slackWebhookUrl",
                path: "path",
                simulationIds: ["simulationIds"],
                targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
            },
        ];

        server
            .mockEndpoint()
            .get("/eval/simulation/suite")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerFindAll();
        expect(response).toEqual([
            {
                id: "id",
                orgId: "orgId",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
                name: "Checkout Flow Tests",
                slackWebhookUrl: "slackWebhookUrl",
                path: "path",
                simulationIds: ["simulationIds"],
                targetAssignments: [
                    {
                        targetType: "assistant",
                        targetId: "targetId",
                    },
                ],
            },
        ]);
    });

    test("SimulationSuiteController_create", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { name: "Checkout Flow Tests", simulationIds: ["simulationIds"] };
        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
        };

        server
            .mockEndpoint()
            .post("/eval/simulation/suite")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerCreate({
            name: "Checkout Flow Tests",
            simulationIds: ["simulationIds"],
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [
                {
                    targetType: "assistant",
                    targetId: "targetId",
                },
            ],
        });
    });

    test("SimulationSuiteController_duplicate (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
        };

        server
            .mockEndpoint()
            .post("/eval/simulation/suite/id/duplicate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerDuplicate({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [
                {
                    targetType: "assistant",
                    targetId: "targetId",
                },
            ],
        });
    });

    test("SimulationSuiteController_duplicate (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/eval/simulation/suite/id/duplicate")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.simulationSuites.simulationSuiteControllerDuplicate({
                id: "id",
            });
        }).rejects.toThrow(Vapi.NotFoundError);
    });

    test("SimulationSuiteController_duplicate (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/eval/simulation/suite/id/duplicate")
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.simulationSuites.simulationSuiteControllerDuplicate({
                id: "id",
            });
        }).rejects.toThrow(Vapi.ConflictError);
    });

    test("SimulationSuiteController_findOne", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
        };

        server
            .mockEndpoint()
            .get("/eval/simulation/suite/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerFindOne({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [
                {
                    targetType: "assistant",
                    targetId: "targetId",
                },
            ],
        });
    });

    test("SimulationSuiteController_remove", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
        };

        server
            .mockEndpoint()
            .delete("/eval/simulation/suite/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerRemove({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [
                {
                    targetType: "assistant",
                    targetId: "targetId",
                },
            ],
        });
    });

    test("SimulationSuiteController_update", async () => {
        const server = mockServerPool.createServer();
        const client = new VapiClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [{ targetType: "assistant", targetId: "targetId" }],
        };

        server
            .mockEndpoint()
            .patch("/eval/simulation/suite/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.simulationSuites.simulationSuiteControllerUpdate({
            id: "id",
        });
        expect(response).toEqual({
            id: "id",
            orgId: "orgId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            name: "Checkout Flow Tests",
            slackWebhookUrl: "slackWebhookUrl",
            path: "path",
            simulationIds: ["simulationIds"],
            targetAssignments: [
                {
                    targetType: "assistant",
                    targetId: "targetId",
                },
            ],
        });
    });
});
