// This file was auto-generated by Fern from our API Definition.

export const BoardControllerFindAllRequestSortOrder = {
    Asc: "ASC",
    Desc: "DESC",
} as const;
export type BoardControllerFindAllRequestSortOrder =
    (typeof BoardControllerFindAllRequestSortOrder)[keyof typeof BoardControllerFindAllRequestSortOrder];
