// This file was auto-generated by Fern from our API Definition.

import type * as Vapi from "../../../index.js";

export type DeletePhoneNumbersResponse =
    | Vapi.DeletePhoneNumbersResponse.ByoPhoneNumber
    | Vapi.DeletePhoneNumbersResponse.Twilio
    | Vapi.DeletePhoneNumbersResponse.Vonage
    | Vapi.DeletePhoneNumbersResponse.Vapi
    | Vapi.DeletePhoneNumbersResponse.Telnyx;

export namespace DeletePhoneNumbersResponse {
    export interface ByoPhoneNumber extends Vapi.ByoPhoneNumber {
        provider: "byo-phone-number";
    }

    export interface Twilio extends Vapi.TwilioPhoneNumber {
        provider: "twilio";
    }

    export interface Vonage extends Vapi.VonagePhoneNumber {
        provider: "vonage";
    }

    export interface Vapi extends Vapi.VapiPhoneNumber {
        provider: "vapi";
    }

    export interface Telnyx extends Vapi.TelnyxPhoneNumber {
        provider: "telnyx";
    }
}
