// This file was auto-generated by Fern from our API Definition.

import type { ByoPhoneNumber as ByoPhoneNumber_ } from "../../../types/ByoPhoneNumber.js";
import type { TelnyxPhoneNumber } from "../../../types/TelnyxPhoneNumber.js";
import type { TwilioPhoneNumber } from "../../../types/TwilioPhoneNumber.js";
import type { VapiPhoneNumber } from "../../../types/VapiPhoneNumber.js";
import type { VonagePhoneNumber } from "../../../types/VonagePhoneNumber.js";

export type ListPhoneNumbersResponseItem =
    | ListPhoneNumbersResponseItem.ByoPhoneNumber
    | ListPhoneNumbersResponseItem.Twilio
    | ListPhoneNumbersResponseItem.Vonage
    | ListPhoneNumbersResponseItem.Vapi
    | ListPhoneNumbersResponseItem.Telnyx;

export namespace ListPhoneNumbersResponseItem {
    export interface ByoPhoneNumber extends ByoPhoneNumber_ {
        provider: "byo-phone-number";
    }

    export interface Twilio extends TwilioPhoneNumber {
        provider: "twilio";
    }

    export interface Vonage extends VonagePhoneNumber {
        provider: "vonage";
    }

    export interface Vapi extends VapiPhoneNumber {
        provider: "vapi";
    }

    export interface Telnyx extends TelnyxPhoneNumber {
        provider: "telnyx";
    }
}
