// This file was auto-generated by Fern from our API Definition.

export const PhoneNumberControllerFindAllPaginatedRequestSortBy = {
    CreatedAt: "createdAt",
    Duration: "duration",
    Cost: "cost",
} as const;
export type PhoneNumberControllerFindAllPaginatedRequestSortBy =
    (typeof PhoneNumberControllerFindAllPaginatedRequestSortBy)[keyof typeof PhoneNumberControllerFindAllPaginatedRequestSortBy];
