// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         id: "id",
 *         itemId: "itemId",
 *         force: "force"
 *     }
 */
export interface SimulationRunControllerGenerateSuggestionsRequest {
    /** The unique identifier of the simulation run. */
    id: string;
    /** The unique identifier of the run item. */
    itemId: string;
    /** Set to the string `true` to regenerate improvement suggestions even if they already exist. */
    force: string;
    persist?: string;
}
